// Generated by a mechanical split of the original monolithic PaintSoftwareUITests
// class. Test bodies are unchanged; see PaintUITestCase for the shared helpers.

import XCTest

final class LayerUITests: PaintUITestCase {

    /// Regression test: with two layers, activating the bottom (non-topmost) layer and drawing
    /// on the canvas must land the stroke on that layer, not get silently swallowed by the
    /// topmost layer's (inactive but still touch-absorbing) host view.
    func testDrawingOnBottomLayerWhenActiveLandsStrokeOnThatLayer() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))
        layersButton.tap()

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap() // Now two layers; the new one (index 1) is topmost and active by default.

        let bottomRow = app.staticTexts["layerPanel.row.0"]
        XCTAssertTrue(bottomRow.waitForExistence(timeout: 5))
        bottomRow.tap() // Activate the bottom layer while the top layer stays topmost on screen.

        layersButton.tap() // Close the panel so it can't cover any part of the canvas.

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let start = canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.3, dy: 0.4))
        let end = start.withOffset(CGVector(dx: 80, dy: 0))
        start.press(forDuration: 0.1, thenDragTo: end)

        layersButton.tap() // Reopen the panel to read back stroke counts.

        // The vector marker rather than `readLayerStrokeCount`: both layers are vector now that it is
        // the default kind, so the stroke is geometry in the cel's display list and the raster tier
        // stays at zero for *both* — which would make the second assertion below pass vacuously.
        // Which layer the stroke lands on is what this test is about, and that is unchanged.
        let bottomStrokes = readVectorMarker(app, layerIndex: 0)?.strokes
        let topStrokes = readVectorMarker(app, layerIndex: 1)?.strokes
        XCTAssertEqual(bottomStrokes, 1, "Drawing while the bottom layer is active should add a stroke to it, but got \(String(describing: bottomStrokes))")
        XCTAssertEqual(topStrokes, 0, "The inactive top layer should not receive the stroke, but got \(String(describing: topStrokes))")
    }

    /// Regression test for the layer-deletion bug: deleting a layer *below* the currently active
    /// one must not silently reassign "active" to a different layer. Reproduces the scenario by
    /// activating the middle of three layers, deleting the bottom one, and confirming — via the
    /// checkmark badge LayerRow shows on the active row — that the layer which was active before
    /// the deletion (now shifted down to index 0) is still the one marked active, and that the
    /// layer panel and the animation timeline agree on which one that is.
    func testDeletingLayerBelowActiveKeepsSameLayerActive() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))
        layersButton.tap()

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap() // layers: [0, 1], current = 1
        addButton.tap() // layers: [0, 1, 2], current = 2

        let middleRow = app.staticTexts["layerPanel.row.1"]
        XCTAssertTrue(middleRow.waitForExistence(timeout: 5))
        middleRow.tap() // Activate layer 1 (the one we expect to remain active after deleting layer 0).
        XCTAssertTrue(app.images["layerPanel.row.1.current"].waitForExistence(timeout: 5), "Layer 1 should be marked active after tapping it")

        swipeDeleteLayerRow(app, layerIndex: 0) // layers shift: old-1 -> 0, old-2 -> 1

        XCTAssertTrue(app.images["layerPanel.row.0.current"].waitForExistence(timeout: 5), "The layer that was active before the deletion (old index 1) should still be marked active, now at index 0")
        XCTAssertFalse(app.images["layerPanel.row.1.current"].exists, "Active status should not have silently moved to the other surviving layer")

        // The animation timeline reads the same canvasManager.layers/currentLayerIndex; confirm
        // it agrees with the panel on layer count and identity after the deletion.
        let timelineName0 = app.staticTexts["timeline.layerName.0"]
        let timelineName1 = app.staticTexts["timeline.layerName.1"]
        XCTAssertTrue(timelineName0.waitForExistence(timeout: 5))
        XCTAssertTrue(timelineName1.waitForExistence(timeout: 5))
    }

    /// Smoke test: repeatedly add and delete layers, and drag a surviving row's opacity slider
    /// right after a deletion. Guards against index-out-of-range crashes/freezes in LayerRow,
    /// whose controls index back into canvasManager.layers by a captured Int — a value that can
    /// go stale for a row mid-removal during the List's own delete animation.
    func testRepeatedAddDeleteLayersDoesNotCrashOrFreeze() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))
        layersButton.tap()

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        for _ in 0..<4 {
            addButton.tap()
        }
        // layers: [0,1,2,3,4], current = 4

        swipeDeleteLayerRow(app, layerIndex: 4)
        swipeDeleteLayerRow(app, layerIndex: 0)
        swipeDeleteLayerRow(app, layerIndex: 1)

        // The app must still be responsive: both the panel and the timeline must agree there
        // are exactly 2 layers left (indices 0 and 1), and interaction must still work.
        XCTAssertEqual(app.state, .runningForeground, "App should still be running, not crashed")
        XCTAssertTrue(app.staticTexts["layerPanel.row.0"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForExistence(timeout: 5))
        XCTAssertFalse(app.staticTexts["layerPanel.row.2"].exists, "Only 2 layers should remain in the panel")
        XCTAssertTrue(app.staticTexts["timeline.layerName.0"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.staticTexts["timeline.layerName.1"].waitForExistence(timeout: 5))
        XCTAssertFalse(app.staticTexts["timeline.layerName.2"].exists, "Only 2 layers should remain in the timeline, staying in sync with the panel")
    }

    /// A freshly added folder must be visible right away — before any layer has been put in it —
    /// in both the layer panel and the animation timeline's name column.
    func testAddingFolderShowsItInLayerPanelAndTimeline() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        addFolderFromAddMenu(app)

        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 1"].waitForExistence(timeout: 5),
                      "A folder should appear in the layer panel as soon as it's created, with no layers in it")
        XCTAssertTrue(app.staticTexts["timeline.folderName.Folder 1"].waitForExistence(timeout: 5),
                      "The same folder should appear as a row in the animation timeline")
    }

    /// Reordering must work by press-and-hold + drag alone, with no Edit mode to enter, and the row
    /// must stay where it was dropped rather than snapping back to its old slot.
    func testLongPressDragReordersLayersAndDropSticks() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        XCTAssertFalse(app.buttons["layerPanel.editButton"].exists, "Reordering should need no Edit button")

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap()
        addButton.tap()
        // layers bottom-to-top: [Vector 1, Vector 2, Vector 3]; displayed top-to-bottom: 3, 2, 1.
        // Vector is the default kind, so both the canvas's first layer and the `+` produce
        // `addVectorLayer`'s "Vector N" naming.

        XCTAssertEqual(app.staticTexts["layerPanel.row.2"].label, "Vector 3")
        XCTAssertEqual(app.staticTexts["layerPanel.row.0"].label, "Vector 1")

        // Drag the topmost row below the bottom one so it becomes the bottom of the stack.
        dragRow(layerCell(app, layerIndex: 2), onto: layerCell(app, layerIndex: 0), dropDY: 0.95)

        XCTAssertEqual(app.staticTexts["layerPanel.row.0"].label, "Vector 3",
                       "The dragged layer should stay where it was dropped, not revert to its old index")
        XCTAssertEqual(app.staticTexts["layerPanel.row.2"].label, "Vector 2",
                       "The layers it was dragged past should have shifted up by one")
    }

    /// The views control is a dropdown, not a cycling button: it lists the saved views, adds new
    /// ones from its own "+", and each saved view swipes left to reveal a delete button.
    func testViewSelectorDropdownAddsSelectsAndDeletesViews() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let viewsButton = app.buttons["layerPanel.viewsButton"]
        XCTAssertTrue(viewsButton.waitForExistence(timeout: 5))
        viewsButton.tap()

        let addView = app.buttons["viewMenu.addButton"]
        XCTAssertTrue(addView.waitForExistence(timeout: 5), "Tapping the views button should open a dropdown with an add button")
        XCTAssertTrue(app.buttons["viewMenu.row.all"].exists, "The dropdown should list the no-view 'All' entry")

        addView.tap()
        let firstView = app.buttons["viewMenu.row.0"]
        XCTAssertTrue(firstView.waitForExistence(timeout: 5), "Adding a view should list it in the dropdown")
        XCTAssertEqual(firstView.value as? String, "1", "The newly added view should be the active one")

        firstView.swipeLeft()
        let deleteButton = app.buttons["Delete"]
        XCTAssertTrue(deleteButton.waitForExistence(timeout: 5), "Views should slide to reveal a delete button, like layer rows do")
        deleteButton.tap()

        XCTAssertTrue(app.buttons["viewMenu.row.0"].waitForNonExistence(timeout: 5), "Deleting a view should remove it from the dropdown")
        XCTAssertEqual(app.buttons["viewMenu.row.all"].value as? String, "1",
                       "Deleting the active view should fall back to 'All'")
    }

    /// Dropping one layer squarely onto another wraps the pair in a new folder, keeping the order
    /// they were already in.
    func testDroppingLayerOntoLayerCreatesFolderWithBoth() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap() // layers: [Vector 1, Vector 2]

        dragRow(layerCell(app, layerIndex: 1), onto: layerCell(app, layerIndex: 0), dropDY: 0.5)

        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 1"].waitForExistence(timeout: 5),
                      "Dropping a layer onto another should create a folder holding both")
        XCTAssertEqual(rowFolder(app, layerIndex: 0), "Folder 1")
        XCTAssertEqual(rowFolder(app, layerIndex: 1), "Folder 1")
        XCTAssertEqual(app.staticTexts["layerPanel.row.1"].label, "Vector 2",
                       "The dragged layer was above the target and should still be above it")
        XCTAssertEqual(app.staticTexts["layerPanel.row.0"].label, "Vector 1")
    }

    /// Dropping onto a folder header moves the layer inside it — the interaction that used to be
    /// fiddly enough to feel broken.
    func testDroppingLayerOntoFolderMovesItInside() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap() // layers: [Vector 1, Vector 2]
        addFolderFromAddMenu(app)
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 1"].waitForExistence(timeout: 5))
        XCTAssertEqual(rowFolder(app, layerIndex: 0), "", "Sanity: the layer starts outside the folder")

        dragRow(layerCell(app, layerIndex: 0), onto: folderCell(app, named: "Folder 1"), dropDY: 0.5)

        XCTAssertEqual(rowFolder(app, layerIndex: 1), "Folder 1",
                       "Dropping onto the folder header should put the layer in the folder")
        // Its timeline row should now report a span rather than reading as empty.
        let folderTrack = app.otherElements["timeline.folderTrack.Folder 1"]
        XCTAssertTrue(folderTrack.waitForExistence(timeout: 5))
        XCTAssertNotEqual(folderTrack.value as? String, "empty")
    }

    /// Folders nest: dropping one folder onto another puts it inside, and the contained rows
    /// indent a level deeper.
    func testDroppingFolderOntoFolderNestsIt() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addFolderFromAddMenu(app) // Folder 1
        addFolderFromAddMenu(app) // Folder 2
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 2"].waitForExistence(timeout: 5))
        XCTAssertEqual(app.staticTexts["layerPanel.folder.Folder 2"].value as? String, "0",
                       "Sanity: both folders start at the top level")

        dragRow(folderCell(app, named: "Folder 2"), onto: folderCell(app, named: "Folder 1"), dropDY: 0.5)

        XCTAssertEqual(app.staticTexts["layerPanel.folder.Folder 2"].value as? String, "1",
                       "A folder dropped onto another should nest one level inside it")
        XCTAssertEqual(app.staticTexts["layerPanel.folder.Folder 1"].value as? String, "0")
    }

    /// Swiping a layer row reveals Delete and Duplicate — and no Edit, which moved to the options
    /// menu.
    func testSwipeRevealsDeleteAndDuplicateButNotEdit() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        revealSwipeActions(app, layerIndex: 0)
        XCTAssertTrue(app.buttons["Delete"].waitForExistence(timeout: 5))
        let duplicate = app.buttons["Duplicate"]
        XCTAssertTrue(duplicate.exists, "Swipe actions should offer Duplicate")
        XCTAssertFalse(app.buttons["layerPanel.row.0.edit"].exists, "Edit should no longer be a swipe action")

        duplicate.tap()
        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForExistence(timeout: 5),
                      "Duplicating should add a second layer")
        XCTAssertEqual(app.staticTexts["layerPanel.row.1"].label, "Vector 1 copy")
    }

    /// Tapping a layer selects it; tapping the selected one again opens its options menu, which is
    /// where Fill Reference lives now that the Edit sheet is gone.
    func testTappingSelectedLayerOpensOptionsAndTogglesFillReference() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let row = app.staticTexts["layerPanel.row.0"]
        XCTAssertTrue(row.waitForExistence(timeout: 5))
        XCTAssertFalse(app.otherElements["layerOptions.fillReferenceToggle"].exists,
                       "The options menu should not be showing before the second tap")

        row.tap() // select
        row.tap() // open options

        let toggle = app.switches["layerOptions.fillReferenceToggle"]
        XCTAssertTrue(toggle.waitForExistence(timeout: 5), "A second tap on the selected layer should open its options")

        let fillRef = app.staticTexts["layerPanel.row.0.fillRef"]
        XCTAssertEqual(fillRef.value as? String, "1", "Layers start as fill references")
        // Hit the switch itself — tapping a SwiftUI Toggle's label doesn't flip it.
        toggle.coordinate(withNormalizedOffset: CGVector(dx: 0.93, dy: 0.5)).tap()
        XCTAssertEqual(fillRef.value as? String, "0", "Toggling in the options menu should update the row")
    }

    /// Merge Down flattens a layer into the one below it, leaving a single layer behind. Same model
    /// call the two-finger pinch gesture makes.
    func testMergeDownFlattensTwoLayersIntoOne() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let point = safeOutsideCornerPoint(canvas)
        drawLine(on: canvas, from: point, to: CGVector(dx: point.dx + 0.12, dy: point.dy))

        openLayerPanel(app)
        let addLayer = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addLayer.waitForExistence(timeout: 5)) // the panel has to finish presenting first
        addLayer.tap() // layers: [Vector 1 (drawn on), Vector 2]
        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForExistence(timeout: 5))

        let top = app.staticTexts["layerPanel.row.1"]
        top.tap()
        top.tap()
        let mergeDown = app.buttons["layerOptions.mergeDown"]
        XCTAssertTrue(mergeDown.waitForExistence(timeout: 5))
        mergeDown.tap()

        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForNonExistence(timeout: 5),
                      "Merging should leave exactly one layer")
        XCTAssertTrue(app.staticTexts["layerPanel.row.0"].waitForExistence(timeout: 5))
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 0), false,
                       "The surviving layer should hold the flattened pixels in the raster tier, not a separate baked-image tier")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 0), 1,
                       "The flattened pixels of both layers should register as raster content")
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: point.dx + 0.06, dy: point.dy)),
                       "The merged artwork should still be on the canvas")
    }

    /// Merging a vector layer must leave the survivor as a genuine `.raster` layer, not `.vector`
    /// with emptied-out geometry — the inconsistency `rasterizeLayer` exists to prevent.
    func testMergeDownFromVectorLayerRasterizesTheSurvivor() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        app.buttons["toolbar.layersButton"].tap()
        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.press(forDuration: 1.2)
        let vectorItem = app.buttons["Vector Layer"]
        XCTAssertTrue(vectorItem.waitForExistence(timeout: 5))
        vectorItem.tap() // layers: [Vector 1, Vector 2 (active)]
        app.buttons["toolbar.layersButton"].tap() // close panel

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        drawLine(on: canvas, from: CGVector(dx: 0.3, dy: 0.5), to: CGVector(dx: 0.7, dy: 0.5))

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readVectorMarker(app, layerIndex: 1)?.isVector, true, "Setup: should be a vector layer")
        // Raster has to be asked for by name now that the plain `+` makes a vector layer, and a
        // raster layer on top is the whole premise: this test is about what merging one *into* a
        // vector layer leaves behind.
        addButton.press(forDuration: 1.2)
        let rasterItem = app.buttons["Raster Layer"]
        XCTAssertTrue(rasterItem.waitForExistence(timeout: 5), "The add menu should still offer a Raster Layer option")
        rasterItem.tap() // layers: [Vector 1, Vector 2, Layer 3 (active, raster, on top)]
        XCTAssertTrue(app.staticTexts["layerPanel.row.2"].waitForExistence(timeout: 5))

        let top = app.staticTexts["layerPanel.row.2"]
        top.tap()
        top.tap()
        let mergeDown = app.buttons["layerOptions.mergeDown"]
        XCTAssertTrue(mergeDown.waitForExistence(timeout: 5))
        mergeDown.tap() // merges Layer 3 into the vector layer below it

        XCTAssertTrue(app.staticTexts["layerPanel.row.2"].waitForNonExistence(timeout: 5))
        XCTAssertEqual(readVectorMarker(app, layerIndex: 1)?.isVector, false,
                       "The survivor should come out of the merge as a raster layer, not vector with emptied geometry")
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 1), false, "The survivor should hold the flattened pixels in the raster tier, not a separate baked-image tier")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 1), 1, "The flattened pixels should register as raster content")
        app.buttons["toolbar.layersButton"].tap() // close panel

        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: 0.5, dy: 0.5)), "The vector stroke should survive the merge")
    }

    // MARK: - §4.1/§4.2 group properties

    /// The regression phase 4b exists to fix: `toggleFolderVisibility` stopped writing through to
    /// children (§4.1), so the live canvas has to consult `isLayerEffectivelyVisible` per layer
    /// instead of the layer's own flag, or hiding a group does nothing on screen.
    func testHidingFolderHidesContentsOnCanvasAndReshowingRestoresThem() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let point = safeOutsideCornerPoint(canvas)
        drawLine(on: canvas, from: point, to: CGVector(dx: point.dx + 0.12, dy: point.dy))
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: point.dx + 0.06, dy: point.dy)),
                       "Setup: the stroke should be on the canvas")

        openLayerPanel(app)
        addFolderFromAddMenu(app) // Folder 1, empty, at the top
        dragRow(layerCell(app, layerIndex: 0), onto: folderCell(app, named: "Folder 1"), dropDY: 0.5)
        XCTAssertEqual(rowFolder(app, layerIndex: 0), "Folder 1", "Setup: the drawn layer should now be inside the folder")

        app.buttons["layerPanel.folder.Folder 1.visibility"].tap()
        app.buttons["toolbar.layersButton"].tap() // close panel to see the canvas

        XCTAssertTrue(waitUntilBlank(canvas, dx: point.dx + 0.06, dy: point.dy, timeout: 5),
                      "Hiding the folder should hide its contents on the live canvas, not just in the panel")

        app.buttons["toolbar.layersButton"].tap() // reopen
        app.buttons["layerPanel.folder.Folder 1.visibility"].tap() // show again
        app.buttons["toolbar.layersButton"].tap() // close

        XCTAssertTrue(waitUntilFilled(canvas, dx: point.dx + 0.06, dy: point.dy, timeout: 5),
                      "Re-showing the folder should restore its contents")
    }

    /// A folder row's tap already means expand/collapse, so its options — the pass-through toggle
    /// (§4.2) and Rename — live behind the row's own button instead of "tap the already-selected
    /// row again", which is how a layer row opens the same menu.
    func testFolderOptionsButtonOpensPassThroughToggleOffByDefault() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        addFolderFromAddMenu(app)
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 1"].waitForExistence(timeout: 5))
        XCTAssertFalse(app.switches["layerOptions.passThroughToggle"].exists,
                       "The options menu should not be showing before the button is tapped")

        app.buttons["layerPanel.folder.Folder 1.options"].tap()

        let toggle = app.switches["layerOptions.passThroughToggle"]
        XCTAssertTrue(toggle.waitForExistence(timeout: 5), "Tapping the folder's options button should open its menu")
        XCTAssertEqual(toggle.value as? String, "0", "Isolated is the default (§4.2), so Pass Through starts off")

        // Hit the switch itself — tapping a SwiftUI Toggle's label doesn't flip it.
        toggle.coordinate(withNormalizedOffset: CGVector(dx: 0.93, dy: 0.5)).tap()
        XCTAssertEqual(toggle.value as? String, "1", "Toggling should flip the switch")

        // Close and reopen to confirm the flip reached the model (`setFolderIsolated`), not just
        // the switch's own transient state.
        app.buttons["layerOptions.close"].tap()
        app.buttons["layerPanel.folder.Folder 1.options"].tap()
        XCTAssertEqual(app.switches["layerOptions.passThroughToggle"].value as? String, "1",
                       "The toggle should reflect the folder's isIsolated flag, not reset when the panel reopens")
    }

    /// Folder rows get the same opacity slider layer rows already have (§4.1), routed through
    /// `CanvasManager.setFolderOpacity` rather than the raw `layers[i].opacity = value` write the
    /// layer rows use (folders have no such index).
    func testFolderOpacitySliderPersistsThroughSetFolderOpacity() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        addFolderFromAddMenu(app)
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 1"].waitForExistence(timeout: 5))

        let slider = app.sliders["layerPanel.folder.Folder 1.opacity"]
        XCTAssertTrue(slider.waitForExistence(timeout: 5), "Folder rows should show the same opacity slider layer rows have")
        XCTAssertEqual(sliderNumericValue(slider), 100, "A fresh folder starts at full opacity")

        slider.adjust(toNormalizedSliderPosition: 0.3)
        let after = sliderNumericValue(slider)
        XCTAssertLessThan(after, 100, "Dragging the slider down should lower the folder's opacity")

        // Collapsing and re-expanding forces a fresh `configure()` from the model, which only
        // shows the dragged value if it reached `setFolderOpacity` rather than staying local to
        // the control (folder rows have no per-layer index for a raw write to land on).
        app.staticTexts["layerPanel.folder.Folder 1"].tap() // collapse
        app.staticTexts["layerPanel.folder.Folder 1"].tap() // expand
        XCTAssertEqual(sliderNumericValue(app.sliders["layerPanel.folder.Folder 1.opacity"]), after, accuracy: 1,
                       "The opacity should persist on the model, not reset when the row is reconfigured")
    }

    // MARK: - §7 blend modes

    /// The picker (`blendModeRow` in LayerPanel.swift) is a `Menu` grouped by `BlendMode.menuGroups`;
    /// picking an item should reach `CanvasManager.setLayerBlendMode` — not stay local to the control
    /// — show on the row without closing the options panel (§7's whole point: a mode has to be
    /// readable without opening options), and survive the panel closing and reopening.
    func testSettingLayerBlendModeShowsOnRowAndPersists() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let row = app.staticTexts["layerPanel.row.0"]
        XCTAssertTrue(row.waitForExistence(timeout: 5))
        row.tap() // select
        row.tap() // open options

        let picker = app.buttons["layerOptions.blendModeButton"]
        XCTAssertTrue(picker.waitForExistence(timeout: 5))
        XCTAssertEqual(picker.value as? String, "normal", "A fresh layer starts at Normal")

        let rowBlendMode = app.otherElements["layerPanel.row.0.blendMode"]
        XCTAssertEqual(rowBlendMode.value as? String, "normal", "Setup: the row's own marker should agree")

        picker.tap()
        let multiply = app.buttons["layerOptions.blendMode.multiply"]
        XCTAssertTrue(multiply.waitForExistence(timeout: 5), "The menu should list Multiply, grouped under darkening (§7)")
        multiply.tap()

        XCTAssertEqual(picker.value as? String, "multiply", "Picking a mode should update the button's own state")
        XCTAssertEqual(rowBlendMode.value as? String, "multiply",
                       "The row should reflect the new mode immediately — LayerRowModel.blendMode is part of its Equatable conformance, so the diffable data source reconfigures the cell")

        // Close and reopen to confirm the pick reached `setLayerBlendMode`, not just local control state.
        app.buttons["layerOptions.close"].tap()
        row.tap()
        row.tap()
        XCTAssertEqual(app.buttons["layerOptions.blendModeButton"].value as? String, "multiply",
                       "The picker should reflect the layer's blendMode, not reset when the panel reopens")
    }

    /// Same contract as the layer picker above, routed through `setFolderBlendMode` instead — the
    /// group side of §7, which is the same picker (`blendModeRow`) reused rather than a second one.
    func testSettingFolderBlendModeShowsOnRowAndPersists() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        addFolderFromAddMenu(app)
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 1"].waitForExistence(timeout: 5))

        app.buttons["layerPanel.folder.Folder 1.options"].tap()
        let picker = app.buttons["layerOptions.blendModeButton"]
        XCTAssertTrue(picker.waitForExistence(timeout: 5))
        XCTAssertEqual(picker.value as? String, "normal", "A fresh folder starts at Normal")

        picker.tap()
        let screen = app.buttons["layerOptions.blendMode.screen"]
        XCTAssertTrue(screen.waitForExistence(timeout: 5), "The menu should list Screen, grouped under lightening (§7)")
        screen.tap()

        XCTAssertEqual(picker.value as? String, "screen")
        let rowBlendMode = app.otherElements["layerPanel.folder.Folder 1.blendMode"]
        XCTAssertEqual(rowBlendMode.value as? String, "screen",
                       "The folder row should reflect the new mode the same way a layer row does")

        // Close and reopen to confirm the pick reached `setFolderBlendMode`, not just local control state.
        app.buttons["layerOptions.close"].tap()
        app.buttons["layerPanel.folder.Folder 1.options"].tap()
        XCTAssertEqual(app.buttons["layerOptions.blendModeButton"].value as? String, "screen",
                       "The picker should reflect the folder's blendMode, not reset when the panel reopens")
    }

    // MARK: - §5.2's sandwich on the live canvas

    /// Where the two crossed strokes below meet — the one pixel every assertion in this section is
    /// about. Vertically centred, so it is never in the letterbox margin (`visibleCanvasBounds`).
    private var crossing: CGVector { CGVector(dx: 0.45, dy: 0.5) }

    /// Sets the brush colour through the colour panel and closes it again, so it cannot cover the
    /// canvas the next probe screenshots.
    private func setBrushColor(_ app: XCUIApplication, hex: String) {
        let colorButton = app.buttons["toolbar.colorButton"]
        XCTAssertTrue(colorButton.waitForExistence(timeout: 5))
        colorButton.tap()
        let hexField = app.textFields["colorPanel.hexField"]
        XCTAssertTrue(hexField.waitForExistence(timeout: 5))
        setHexField(app, hexField, to: hex)
        colorButton.tap()
    }

    /// Two overlapping strokes on two layers, in colours whose product is nothing like either of
    /// them: cyan underneath, magenta on top. At `crossing` a **Normal** top layer reads magenta
    /// (255, 0, 255) and a **Multiply** one reads blue (0, 0, 255) — the red channel alone is the
    /// whole discriminator, which is what makes this readable through a screenshot's own rounding.
    ///
    /// Both strokes run the same path so the overlap is the width of a stroke rather than the size
    /// of a crossing, and `crossing` is its midpoint — comfortably inside the solid core of both,
    /// away from the antialiased edges.
    private func drawCrossedStrokesOnTwoLayers(_ app: XCUIApplication) -> XCUIElement {
        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))

        setBrushColor(app, hex: "00FFFF")
        drawLine(on: canvas, from: CGVector(dx: 0.35, dy: 0.5), to: CGVector(dx: 0.55, dy: 0.5))

        openLayerPanel(app)
        app.buttons["layerPanel.addButton"].tap() // layer 1, topmost and active
        app.buttons["toolbar.layersButton"].tap()

        setBrushColor(app, hex: "FF00FF")
        drawLine(on: canvas, from: CGVector(dx: 0.35, dy: 0.5), to: CGVector(dx: 0.55, dy: 0.5))
        return canvas
    }

    /// Sets the active layer's blend mode through the options panel, leaving the panel closed.
    private func setBlendMode(_ app: XCUIApplication, layerIndex: Int, to mode: String) {
        openLayerPanel(app)
        let row = app.staticTexts["layerPanel.row.\(layerIndex)"]
        XCTAssertTrue(row.waitForExistence(timeout: 5))
        row.tap() // select
        row.tap() // open options
        app.buttons["layerOptions.blendModeButton"].tap()
        let item = app.buttons["layerOptions.blendMode.\(mode)"]
        XCTAssertTrue(item.waitForExistence(timeout: 5))
        item.tap()
        app.buttons["layerOptions.close"].tap()
        app.buttons["toolbar.layersButton"].tap()
    }

    /// Polls a canvas pixel until `matches` holds. The sandwich composites off the main thread (see
    /// `CanvasView.Coordinator.startSandwichRebuild`), so every assertion about what the canvas shows
    /// after a model change is a wait, exactly as `waitUntilFilled` is for the fill.
    @discardableResult
    private func waitForPixel(_ canvas: XCUIElement, at point: CGVector, timeout: TimeInterval = 10,
                              matches: ((r: UInt8, g: UInt8, b: UInt8, a: UInt8)) -> Bool) -> (r: UInt8, g: UInt8, b: UInt8, a: UInt8)? {
        let deadline = Date().addingTimeInterval(timeout)
        var last: (r: UInt8, g: UInt8, b: UInt8, a: UInt8)?
        while Date() < deadline {
            last = rgbaPixel(of: canvas, dx: Double(point.dx), dy: Double(point.dy))
            if let last, matches(last) { return last }
            Thread.sleep(forTimeInterval: 0.2)
        }
        return last
    }

    /// "off" / "rest" / "stroke" — which rendering path the live canvas is on, published on
    /// `canvas.host`'s label by `CanvasView.Coordinator.SandwichPresentation`.
    private func sandwichState(_ app: XCUIApplication) -> String {
        let label = app.otherElements["canvas.host"].label
        return label.hasPrefix("sandwich:") ? String(label.dropFirst("sandwich:".count)) : "?(\(label))"
    }

    /// **The regression guard for the mask trick, and the reason `LayerHostView.setBlanked` uses a
    /// mask rather than `isHidden`.**
    ///
    /// While the sandwich is engaged every layer host is blanked, including the active one at rest.
    /// `UIView.hitTest` returns nil for a view that is hidden or below alpha 0.01, so blanking that
    /// way would mean the first touch of a stroke never reaches the stroke view — the artist draws
    /// and *nothing happens*, with no error anywhere. The stroke count is the assertion that catches
    /// it: it can only be non-zero if the touch was delivered.
    func testAStrokeStillLandsWhileTheSandwichIsEngaged() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))

        setBlendMode(app, layerIndex: 0, to: "multiply")
        XCTAssertEqual(vectorMarkerViaPanel(app, layerIndex: 0)?.strokes, 0, "Setup: nothing drawn yet")
        XCTAssertEqual(sandwichState(app), "rest",
                       "A blending leaf is exactly the document Core Animation cannot draw, so the compositor should have taken over")

        setBrushColor(app, hex: "00FFFF")
        drawLine(on: canvas, from: CGVector(dx: 0.35, dy: 0.5), to: CGVector(dx: 0.55, dy: 0.5))

        XCTAssertEqual(vectorMarkerViaPanel(app, layerIndex: 0)?.strokes, 1,
                       "The stroke has to reach the blanked host. A zero here means the host was hidden rather than masked and the touch was never delivered")
        XCTAssertNotNil(waitForPixel(canvas, at: crossing) { !isWhitish($0) },
                        "And it has to be visible: on lift the canvas goes back to `composite(full)`, which contains the stroke")
    }

    /// **"I cannot see my paint strokes live" — the one thing no other case in this file looks at.**
    ///
    /// Every other sandwich assertion samples the canvas *after* lift, where `composite(full)`
    /// contains the stroke and the picture is right whether or not a single pixel of ink was on
    /// screen while the artist was drawing. The mid-stroke half of §5.2 is only observable with the
    /// touch still down, so that is what this does: the drag runs on a background queue with a hold
    /// at the far end, and the test thread probes the canvas during the hold.
    ///
    /// **The second stroke, not the first, and that is the whole point.** `updateSandwich` is the
    /// only thing that unblanks the active host, and it runs from a SwiftUI pass. The first stroke on
    /// a frame spawns a cel, which publishes, which causes the pass — so the first stroke draws
    /// visibly and hides the defect. The second stroke publishes nothing (a dab must not, §5.2), so
    /// if nothing applies the mid-stroke presentation at touch-down the host stays blanked for the
    /// whole stroke and the ink appears only on lift.
    func testInkIsVisibleWhileTheSecondStrokeIsStillDown() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))

        setBlendMode(app, layerIndex: 0, to: "multiply")
        XCTAssertEqual(sandwichState(app), "rest", "Setup: a blending leaf puts the canvas on the compositor")
        setBrushColor(app, hex: "00FFFF")

        // Stroke one, lifted normally. It spawns the cel, so it is the stroke that gets a free
        // SwiftUI pass — and it leaves the canvas back at rest with every host blanked again.
        drawLine(on: canvas, from: CGVector(dx: 0.35, dy: 0.5), to: CGVector(dx: 0.55, dy: 0.5))
        XCTAssertNotNil(waitForPixel(canvas, at: crossing) { !isWhitish($0) }, "Setup: the first stroke landed")
        XCTAssertEqual(sandwichState(app), "rest", "Setup: back at rest, so the active host is blanked again")

        // Let the debounced thumbnail regen (400 ms, `CanvasManager`) land and publish before the
        // stroke under test starts. Otherwise it could arrive mid-stroke, cause the SwiftUI pass this
        // test is about the absence of, and mask the defect.
        Thread.sleep(forTimeInterval: 1.5)

        // Stroke two, on fresh paper well clear of stroke one, so the only thing that can put ink at
        // `probe` is the active layer's own host drawing itself.
        let probe = CGVector(dx: 0.40, dy: 0.65)
        XCTAssertTrue(isWhitish(rgbaPixel(of: canvas, dx: probe.dx, dy: probe.dy)),
                      "Setup: nothing has been drawn at the probe yet")

        var midStrokePixel: (r: UInt8, g: UInt8, b: UInt8, a: UInt8)?
        var midStrokeState = "?"
        whileDrawing(on: canvas, from: CGVector(dx: 0.30, dy: probe.dy), to: CGVector(dx: 0.62, dy: probe.dy)) {
            // Poll rather than sample once: the touch is synthesised asynchronously, so the first
            // reads land before the pen has crawled as far as the probe.
            let deadline = Date().addingTimeInterval(8)
            while Date() < deadline {
                let pixel = self.rgbaPixel(of: canvas, dx: probe.dx, dy: probe.dy)
                midStrokePixel = pixel
                midStrokeState = self.sandwichState(app)
                if !self.isWhitish(pixel) { return }
                Thread.sleep(forTimeInterval: 0.2)
            }
        }

        XCTContext.runActivity(named: "mid-stroke probe") { activity in
            activity.add(XCTAttachment(string: "pixel=\(String(describing: midStrokePixel)) state=\(midStrokeState)"))
        }
        XCTAssertEqual(midStrokeState, "stroke",
                       "With a dab down the canvas has to be on the three-view mid-stroke path, not still showing `full`")
        XCTAssertFalse(isWhitish(midStrokePixel),
                       "The artist has to see their ink while the touch is still down. White at \(String(describing: midStrokePixel)) is the blanked active host — the stroke is being recorded into a view §5.2 is hiding, and it appears only on lift")

        // And the lift still snaps to the exact composite, so the fix cannot have been "stop blanking".
        XCTAssertNotNil(waitForPixel(canvas, at: probe) { !isWhitish($0) }, "The stroke survives the lift")
        XCTAssertEqual(sandwichState(app), "rest", "…and the canvas goes back to `composite(full)`")
    }

    /// Runs a deliberately slow drag on a background queue and calls `probe` on the test thread while
    /// the touch is still down, joining before it returns.
    ///
    /// XCUITest's gesture APIs are synchronous — `press(forDuration:thenDragTo:…)` returns only once
    /// the touch has lifted — so there is no other way to look at the screen mid-gesture, and
    /// mid-gesture is the only place §5.2's mid-stroke state exists.
    ///
    /// **A crawling drag rather than `thenHoldForDuration`, and that is not a style choice.** Holding
    /// the pen still for 0.8 s is the smart-shape gesture (`Coordinator.startShapeDetection`): the
    /// hold timer fires, a straight drag detects as a line, and `fireShapeDetection` *reverts the
    /// stroke it was painting*. The probe would then be reading a canvas the app had deliberately
    /// cleared. A drag that never stops moving resets that timer on every sample instead.
    private func whileDrawing(on element: XCUIElement, from: CGVector, to: CGVector, probe: () -> Void) {
        let start = element.coordinate(withNormalizedOffset: from)
        let end = element.coordinate(withNormalizedOffset: to)
        let finished = DispatchSemaphore(value: 0)
        DispatchQueue.global(qos: .userInitiated).async {
            start.press(forDuration: 0.1, thenDragTo: end,
                        withVelocity: XCUIGestureVelocity(rawValue: 40), thenHoldForDuration: 0.1)
            finished.signal()
        }
        probe()
        _ = finished.wait(timeout: .now() + 60)
    }

    /// **§11's done-criterion for phase 5b: a Multiply layer looks multiplied on the canvas the
    /// artist is drawing on.** Before the sandwich, `reconcileLayers` handed every layer to Core
    /// Animation as a flat sibling, so the mode showed on the layer row and in the project thumbnail
    /// and changed nothing on canvas.
    ///
    /// Doubles as the "a blend change brings the canvas back in sync" case: the mode is picked with
    /// both strokes already on the canvas, so the pixel has to *move* rather than merely start right.
    func testAMultiplyLayerLooksMultipliedOnTheLiveCanvas() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        let canvas = drawCrossedStrokesOnTwoLayers(app)

        XCTAssertEqual(sandwichState(app), "off", "Two Normal layers are still Core Animation's own case")
        guard let normal = waitForPixel(canvas, at: crossing, matches: { $0.r > 200 && $0.b > 200 }) else {
            return XCTFail("Setup: the magenta stroke should cover the cyan one at the crossing")
        }
        XCTAssertLessThan(normal.g, 80, "Setup: magenta over cyan, source-over, is magenta")

        setBlendMode(app, layerIndex: 1, to: "multiply")

        XCTAssertEqual(sandwichState(app), "rest")
        guard let multiplied = waitForPixel(canvas, at: crossing, matches: { $0.r < 80 }) else {
            return XCTFail("The canvas never showed the multiply")
        }
        XCTAssertLessThan(multiplied.r, 80,
                          "Magenta multiplied into cyan has no red left — this is the assertion the whole phase exists for, and \(multiplied) is what an unblended flat sibling still looks like")
        XCTAssertGreaterThan(multiplied.b, 200, "Blue survives both, so it is what tells a multiply from a layer that simply vanished")
    }

    /// **The risk containment, stated as a test.** Every document that could exist before phase 5a
    /// has to keep taking today's exact code path — one host per layer, no compositor, no cached
    /// images — and `needsCompositorOnCanvas` is what guarantees it. If this ever reads anything but
    /// "off", every project ever made starts rendering through a path it has never rendered through.
    func testAnAllNormalDocumentNeverEngagesTheSandwich() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        let canvas = drawCrossedStrokesOnTwoLayers(app)

        XCTAssertEqual(sandwichState(app), "off", "Two Normal layers on a flat stack")
        XCTAssertEqual(vectorMarkerViaPanel(app, layerIndex: 1)?.strokes, 1, "Drawing behaves as before")

        // A folder at its defaults is a transparent parenthesis — opacity 1, normal, isolated over
        // nothing that blends — so nesting must not engage anything either.
        openLayerPanel(app)
        addFolderFromAddMenu(app)
        dragRow(layerCell(app, layerIndex: 1), onto: folderCell(app, named: "Folder 1"), dropDY: 0.5)
        XCTAssertEqual(rowFolder(app, layerIndex: 1), "Folder 1", "Setup: the top layer should now be inside the folder")
        app.buttons["toolbar.layersButton"].tap()

        XCTAssertEqual(sandwichState(app), "off", "An untouched folder changes nothing Core Animation cannot express")
        drawLine(on: canvas, from: CGVector(dx: 0.35, dy: 0.42), to: CGVector(dx: 0.55, dy: 0.42))
        XCTAssertEqual(vectorMarkerViaPanel(app, layerIndex: 1)?.strokes, 2,
                       "And drawing still lands, on the same path it always did")
        XCTAssertEqual(sandwichState(app), "off", "Drawing is not what engages it either")
    }

    /// The invalidation contract from the other side: everything *except* the live stroke has to
    /// move the cached composites. A layer switch re-cuts the tree, a visibility toggle changes what
    /// is in it, and undo changes a layer's pixels — each has to reach the canvas, and each would sit
    /// there showing a stale composite if it were missing from `SandwichKey`.
    func testTheBlendedCanvasComesBackInSyncAfterLayerSwitchVisibilityToggleAndUndo() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        let canvas = drawCrossedStrokesOnTwoLayers(app)
        setBlendMode(app, layerIndex: 1, to: "multiply")
        XCTAssertNotNil(waitForPixel(canvas, at: crossing, matches: { $0.r < 80 }), "Setup: multiplied")

        // A layer switch changes only where the tree is cut, so the picture must not change with it.
        openLayerPanel(app)
        app.staticTexts["layerPanel.row.0"].tap()
        app.buttons["toolbar.layersButton"].tap()
        XCTAssertNotNil(waitForPixel(canvas, at: crossing, matches: { $0.r < 80 }),
                        "Selecting the layer underneath re-cuts the sandwich; at rest it is still `composite(full)` and still multiplied")

        // Hiding the cyan layer leaves the magenta one multiplying against nothing, which is itself.
        openLayerPanel(app)
        app.buttons["layerPanel.row.0.visibility"].tap()
        app.buttons["toolbar.layersButton"].tap()
        XCTAssertNotNil(waitForPixel(canvas, at: crossing, matches: { $0.r > 200 && $0.b > 200 }),
                        "With nothing underneath to multiply into, the top layer reads as its own colour again")

        // And undo, which is the same change arriving from the history rather than from a tap.
        // `toggleLayerVisibility` goes through `withStructureUndo`, so the hide above is the newest
        // step and one tap is deterministic — no counting how many of the steps before it were
        // undoable.
        let undo = app.buttons["sideToolbar.undoButton"]
        XCTAssertTrue(undo.waitForExistence(timeout: 5))
        undo.tap()
        XCTAssertNotNil(waitForPixel(canvas, at: crossing, matches: { $0.r < 80 }),
                        "Undoing the hide should bring the multiply back, not leave a composite that still remembers the layer as hidden")
    }

    /// The playhead is the last of §5.2's invalidation triggers, and the one that changes *which*
    /// pixels a layer contributes rather than what they are. The top layer's block is shortened so
    /// that a frame past its end is a frame it does not cover: the canvas has to drop back to the
    /// cyan layer alone there. A sandwich that never rebuilt on a frame change would still be
    /// showing the multiplied composite of frame 1.
    func testMovingThePlayheadRebuildsTheBlendedCanvas() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        let canvas = drawCrossedStrokesOnTwoLayers(app)
        setBlendMode(app, layerIndex: 1, to: "multiply")
        XCTAssertNotNil(waitForPixel(canvas, at: crossing, matches: { $0.r < 80 }), "Setup: multiplied at frame 1")

        // Shrink the magenta layer's block. Read the result rather than assuming the drag's reach —
        // XCUITest's synthetic drags undershoot by a timing-dependent amount (see `performDrag`).
        performDrag(app, identifier: "timeline.cel.1.0.rightHandle", totalDelta: -260)
        guard let block = readCel(app, layerIndex: 1, celIndex: 0) else {
            return XCTFail("Could not read the shortened block")
        }
        XCTAssertLessThan(block.length, 12, "Setup: the drag should have shortened the block")

        let ruler = app.otherElements["timeline.ruler"]
        XCTAssertTrue(ruler.waitForExistence(timeout: 5))
        let start = ruler.coordinate(withNormalizedOffset: CGVector(dx: 0.02, dy: 0.5))
        // 30pt per frame, and one frame past the block's end is enough.
        start.press(forDuration: 0.2,
                    thenDragTo: start.withOffset(CGVector(dx: CGFloat(block.start + block.length + 1) * 30, dy: 0)),
                    withVelocity: .slow, thenHoldForDuration: 0.2)
        guard let (current, _) = readFrameLabel(app) else { return XCTFail("Could not read the frame label") }
        XCTAssertGreaterThan(current, block.start + block.length,
                             "Setup: the playhead has to land past the shortened block for this to test anything")

        XCTAssertNotNil(waitForPixel(canvas, at: crossing, matches: { $0.g > 200 && $0.b > 200 && $0.r < 120 }),
                        "Past the magenta block there is nothing to multiply, so the canvas is the cyan layer alone — a stale composite would still read blue")
    }

    // MARK: - §4.3 compositor nodes
    //
    // A node and its input slots are stored as ordinary `LayerFolder`s, so every one of these would
    // pass trivially against three identical folder rows. What each asserts is the *difference* the
    // panel draws on top of that sameness — which is the whole of phase 8's UI.

    /// One tap creates the node and both its operands: a node without its slots is a shape none of
    /// the tree's guards would accept, so `addCompositorNode` never leaves one on screen.
    func testAddingMixNodeShowsTheNodeAndBothInputSlotsWithTheBackdropLowest() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        addMixNodeFromAddMenu(app)

        XCTAssertTrue(app.staticTexts["layerPanel.folder.Mix 1"].waitForExistence(timeout: 5),
                      "The node row should appear as soon as it's created, with nothing in it")
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Input A"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Input B"].waitForExistence(timeout: 5))

        XCTAssertEqual(app.otherElements["layerPanel.folder.Mix 1.compositor"].value as? String, "node,normal",
                       "The row has to say it is a node — nothing structural distinguishes it from a folder")
        XCTAssertEqual(app.otherElements["layerPanel.folder.Input A.compositor"].value as? String, "slot,0")
        XCTAssertEqual(app.otherElements["layerPanel.folder.Input B.compositor"].value as? String, "slot,1")

        // §4.3 fixes slot 0 as the backdrop, and the panel expresses that by position alone — an
        // empty Input A floating to the top of its node the way any other empty folder would is the
        // trap the ordering rule exists to close.
        XCTAssertGreaterThan(folderCell(app, named: "Input A").frame.minY,
                             folderCell(app, named: "Input B").frame.minY,
                             "Input A is the backdrop, so it presents below Input B")
    }

    /// A node that cannot be filled is decoration. The drop goes through the same restack the folder
    /// drops use — a slot is an ordinary container, and only the *node header* refuses a drop.
    func testALayerDropsIntoAnInputSlotAndReportsItAsItsFolder() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        addMixNodeFromAddMenu(app)
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Input A"].waitForExistence(timeout: 5))
        XCTAssertEqual(rowFolder(app, layerIndex: 0), "", "Setup: the layer starts outside the node")

        dragRow(layerCell(app, layerIndex: 0), onto: folderCell(app, named: "Input A"), dropDY: 0.5)

        XCTAssertEqual(rowFolder(app, layerIndex: 0), "Input A",
                       "A slot takes a drop like any other folder — that is the whole point of storing it as one")
    }

    /// The mode is the entire content of a Mix's op, so it is editable, it shows on the row without
    /// opening options (§7's rule, applied to a node), and it is a *different* pick from the node's
    /// own blend mode — which the same folder also carries, and which must not move with it.
    func testMixNodeModeIsEditableSeparatelyFromTheNodesOwnBlendMode() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        addMixNodeFromAddMenu(app)
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Mix 1"].waitForExistence(timeout: 5))

        app.buttons["layerPanel.folder.Mix 1.options"].tap()
        let mixPicker = app.buttons["layerOptions.mixModeButton"]
        XCTAssertTrue(mixPicker.waitForExistence(timeout: 5), "A node's options lead with its op")
        XCTAssertEqual(mixPicker.value as? String, "normal", "A fresh Mix starts at Normal")
        XCTAssertEqual(app.buttons["layerOptions.blendModeButton"].value as? String, "normal",
                       "Setup: the node's own blend into its parent is a second, separate control")

        mixPicker.tap()
        let multiply = app.buttons["layerOptions.mixMode.multiply"]
        XCTAssertTrue(multiply.waitForExistence(timeout: 5))
        multiply.tap()

        XCTAssertEqual(mixPicker.value as? String, "multiply")
        XCTAssertEqual(app.buttons["layerOptions.blendModeButton"].value as? String, "normal",
                       "Picking a Mix mode must not move the node's own blend mode — they are different questions")
        XCTAssertEqual(app.otherElements["layerPanel.folder.Mix 1.compositor"].value as? String, "node,multiply",
                       "And the row shows it immediately, the way a layer's blend mode does")

        // Close and reopen to confirm the pick reached `setMixBlendMode` rather than staying local
        // to the control.
        app.buttons["layerOptions.close"].tap()
        app.buttons["layerPanel.folder.Mix 1.options"].tap()
        XCTAssertEqual(app.buttons["layerOptions.mixModeButton"].value as? String, "multiply",
                       "The picker should reflect the node's op, not reset when the panel reopens")
    }

    /// A slot's options menu is where "this is not an ordinary folder" has to be visible: it cannot
    /// be deleted, it is always isolated (§4.3), and its own blend mode would be a second answer to
    /// the question its node's op already answers. Rename is the control that proves the panel
    /// actually opened rather than the assertions passing on an empty screen.
    func testInputSlotOptionsOfferNeitherDeleteNorPassThroughNorItsOwnBlendMode() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        addMixNodeFromAddMenu(app)
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Input A"].waitForExistence(timeout: 5))

        app.buttons["layerPanel.folder.Input A.options"].tap()
        XCTAssertTrue(app.buttons["layerOptions.rename"].waitForExistence(timeout: 5),
                      "Sanity: the slot's options menu opened")

        XCTAssertFalse(app.buttons["layerOptions.deleteFolder"].exists,
                       "A slot exists because its node's arity says so — `deleteFolder` refuses one, so the panel must not offer it")
        XCTAssertFalse(app.switches["layerOptions.passThroughToggle"].exists,
                       "A slot is always isolated (§4.3); the derivation overrides the flag, so a switch here would do nothing")
        XCTAssertFalse(app.buttons["layerOptions.blendModeButton"].exists,
                       "The node's op is what combines its inputs — a per-slot mode is the same lever twice")

        // The node itself keeps all three, which is what makes the absences above a decision about
        // slots rather than about compositor folders generally.
        app.buttons["layerOptions.close"].tap()
        app.buttons["layerPanel.folder.Mix 1.options"].tap()
        XCTAssertTrue(app.buttons["layerOptions.deleteFolder"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.switches["layerOptions.passThroughToggle"].exists)
        XCTAssertTrue(app.buttons["layerOptions.blendModeButton"].exists)
    }

}
