// Generated by a mechanical split of the original monolithic PaintSoftwareUITests
// class. Test bodies are unchanged; see PaintUITestCase for the shared helpers.

import XCTest

final class LayerUITests: PaintUITestCase {

    /// Regression test: with two layers, activating the bottom (non-topmost) layer and drawing
    /// on the canvas must land the stroke on that layer, not get silently swallowed by the
    /// topmost layer's (inactive but still touch-absorbing) host view.
    func testDrawingOnBottomLayerWhenActiveLandsStrokeOnThatLayer() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))
        layersButton.tap()

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap() // Now two layers; the new one (index 1) is topmost and active by default.

        let bottomRow = app.staticTexts["layerPanel.row.0"]
        XCTAssertTrue(bottomRow.waitForExistence(timeout: 5))
        bottomRow.tap() // Activate the bottom layer while the top layer stays topmost on screen.

        layersButton.tap() // Close the panel so it can't cover any part of the canvas.

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let start = canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.3, dy: 0.4))
        let end = start.withOffset(CGVector(dx: 80, dy: 0))
        start.press(forDuration: 0.1, thenDragTo: end)

        layersButton.tap() // Reopen the panel to read back stroke counts.

        // The vector marker rather than `readLayerStrokeCount`: both layers are vector now that it is
        // the default kind, so the stroke is geometry in the cel's display list and the raster tier
        // stays at zero for *both* — which would make the second assertion below pass vacuously.
        // Which layer the stroke lands on is what this test is about, and that is unchanged.
        let bottomStrokes = readVectorMarker(app, layerIndex: 0)?.strokes
        let topStrokes = readVectorMarker(app, layerIndex: 1)?.strokes
        XCTAssertEqual(bottomStrokes, 1, "Drawing while the bottom layer is active should add a stroke to it, but got \(String(describing: bottomStrokes))")
        XCTAssertEqual(topStrokes, 0, "The inactive top layer should not receive the stroke, but got \(String(describing: topStrokes))")
    }

    /// Regression test for the layer-deletion bug: deleting a layer *below* the currently active
    /// one must not silently reassign "active" to a different layer. Reproduces the scenario by
    /// activating the middle of three layers, deleting the bottom one, and confirming — via the
    /// checkmark badge LayerRow shows on the active row — that the layer which was active before
    /// the deletion (now shifted down to index 0) is still the one marked active, and that the
    /// layer panel and the animation timeline agree on which one that is.
    func testDeletingLayerBelowActiveKeepsSameLayerActive() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))
        layersButton.tap()

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap() // layers: [0, 1], current = 1
        addButton.tap() // layers: [0, 1, 2], current = 2

        let middleRow = app.staticTexts["layerPanel.row.1"]
        XCTAssertTrue(middleRow.waitForExistence(timeout: 5))
        middleRow.tap() // Activate layer 1 (the one we expect to remain active after deleting layer 0).
        XCTAssertTrue(app.images["layerPanel.row.1.current"].waitForExistence(timeout: 5), "Layer 1 should be marked active after tapping it")

        swipeDeleteLayerRow(app, layerIndex: 0) // layers shift: old-1 -> 0, old-2 -> 1

        XCTAssertTrue(app.images["layerPanel.row.0.current"].waitForExistence(timeout: 5), "The layer that was active before the deletion (old index 1) should still be marked active, now at index 0")
        XCTAssertFalse(app.images["layerPanel.row.1.current"].exists, "Active status should not have silently moved to the other surviving layer")

        // The animation timeline reads the same canvasManager.layers/currentLayerIndex; confirm
        // it agrees with the panel on layer count and identity after the deletion.
        let timelineName0 = app.staticTexts["timeline.layerName.0"]
        let timelineName1 = app.staticTexts["timeline.layerName.1"]
        XCTAssertTrue(timelineName0.waitForExistence(timeout: 5))
        XCTAssertTrue(timelineName1.waitForExistence(timeout: 5))
    }

    /// Smoke test: repeatedly add and delete layers, and drag a surviving row's opacity slider
    /// right after a deletion. Guards against index-out-of-range crashes/freezes in LayerRow,
    /// whose controls index back into canvasManager.layers by a captured Int — a value that can
    /// go stale for a row mid-removal during the List's own delete animation.
    func testRepeatedAddDeleteLayersDoesNotCrashOrFreeze() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))
        layersButton.tap()

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        for _ in 0..<4 {
            addButton.tap()
        }
        // layers: [0,1,2,3,4], current = 4

        swipeDeleteLayerRow(app, layerIndex: 4)
        swipeDeleteLayerRow(app, layerIndex: 0)
        swipeDeleteLayerRow(app, layerIndex: 1)

        // The app must still be responsive: both the panel and the timeline must agree there
        // are exactly 2 layers left (indices 0 and 1), and interaction must still work.
        XCTAssertEqual(app.state, .runningForeground, "App should still be running, not crashed")
        XCTAssertTrue(app.staticTexts["layerPanel.row.0"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForExistence(timeout: 5))
        XCTAssertFalse(app.staticTexts["layerPanel.row.2"].exists, "Only 2 layers should remain in the panel")
        XCTAssertTrue(app.staticTexts["timeline.layerName.0"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.staticTexts["timeline.layerName.1"].waitForExistence(timeout: 5))
        XCTAssertFalse(app.staticTexts["timeline.layerName.2"].exists, "Only 2 layers should remain in the timeline, staying in sync with the panel")
    }

    /// A freshly added folder must be visible right away — before any layer has been put in it —
    /// in both the layer panel and the animation timeline's name column.
    func testAddingFolderShowsItInLayerPanelAndTimeline() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        addFolderFromAddMenu(app)

        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 1"].waitForExistence(timeout: 5),
                      "A folder should appear in the layer panel as soon as it's created, with no layers in it")
        XCTAssertTrue(app.staticTexts["timeline.folderName.Folder 1"].waitForExistence(timeout: 5),
                      "The same folder should appear as a row in the animation timeline")
    }

    /// Reordering must work by press-and-hold + drag alone, with no Edit mode to enter, and the row
    /// must stay where it was dropped rather than snapping back to its old slot.
    func testLongPressDragReordersLayersAndDropSticks() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        XCTAssertFalse(app.buttons["layerPanel.editButton"].exists, "Reordering should need no Edit button")

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap()
        addButton.tap()
        // layers bottom-to-top: [Vector 1, Vector 2, Vector 3]; displayed top-to-bottom: 3, 2, 1.
        // Vector is the default kind, so both the canvas's first layer and the `+` produce
        // `addVectorLayer`'s "Vector N" naming.

        XCTAssertEqual(app.staticTexts["layerPanel.row.2"].label, "Vector 3")
        XCTAssertEqual(app.staticTexts["layerPanel.row.0"].label, "Vector 1")

        // Drag the topmost row below the bottom one so it becomes the bottom of the stack.
        dragRow(layerCell(app, layerIndex: 2), onto: layerCell(app, layerIndex: 0), dropDY: 0.95)

        XCTAssertEqual(app.staticTexts["layerPanel.row.0"].label, "Vector 3",
                       "The dragged layer should stay where it was dropped, not revert to its old index")
        XCTAssertEqual(app.staticTexts["layerPanel.row.2"].label, "Vector 2",
                       "The layers it was dragged past should have shifted up by one")
    }

    /// The views control is a dropdown, not a cycling button: it lists the saved views, adds new
    /// ones from its own "+", and each saved view swipes left to reveal a delete button.
    func testViewSelectorDropdownAddsSelectsAndDeletesViews() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let viewsButton = app.buttons["layerPanel.viewsButton"]
        XCTAssertTrue(viewsButton.waitForExistence(timeout: 5))
        viewsButton.tap()

        let addView = app.buttons["viewMenu.addButton"]
        XCTAssertTrue(addView.waitForExistence(timeout: 5), "Tapping the views button should open a dropdown with an add button")
        XCTAssertTrue(app.buttons["viewMenu.row.all"].exists, "The dropdown should list the no-view 'All' entry")

        addView.tap()
        let firstView = app.buttons["viewMenu.row.0"]
        XCTAssertTrue(firstView.waitForExistence(timeout: 5), "Adding a view should list it in the dropdown")
        XCTAssertEqual(firstView.value as? String, "1", "The newly added view should be the active one")

        firstView.swipeLeft()
        let deleteButton = app.buttons["Delete"]
        XCTAssertTrue(deleteButton.waitForExistence(timeout: 5), "Views should slide to reveal a delete button, like layer rows do")
        deleteButton.tap()

        XCTAssertTrue(app.buttons["viewMenu.row.0"].waitForNonExistence(timeout: 5), "Deleting a view should remove it from the dropdown")
        XCTAssertEqual(app.buttons["viewMenu.row.all"].value as? String, "1",
                       "Deleting the active view should fall back to 'All'")
    }

    /// Dropping one layer squarely onto another wraps the pair in a new folder, keeping the order
    /// they were already in.
    func testDroppingLayerOntoLayerCreatesFolderWithBoth() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap() // layers: [Vector 1, Vector 2]

        dragRow(layerCell(app, layerIndex: 1), onto: layerCell(app, layerIndex: 0), dropDY: 0.5)

        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 1"].waitForExistence(timeout: 5),
                      "Dropping a layer onto another should create a folder holding both")
        XCTAssertEqual(rowFolder(app, layerIndex: 0), "Folder 1")
        XCTAssertEqual(rowFolder(app, layerIndex: 1), "Folder 1")
        XCTAssertEqual(app.staticTexts["layerPanel.row.1"].label, "Vector 2",
                       "The dragged layer was above the target and should still be above it")
        XCTAssertEqual(app.staticTexts["layerPanel.row.0"].label, "Vector 1")
    }

    /// Dropping onto a folder header moves the layer inside it — the interaction that used to be
    /// fiddly enough to feel broken.
    func testDroppingLayerOntoFolderMovesItInside() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap() // layers: [Vector 1, Vector 2]
        addFolderFromAddMenu(app)
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 1"].waitForExistence(timeout: 5))
        XCTAssertEqual(rowFolder(app, layerIndex: 0), "", "Sanity: the layer starts outside the folder")

        dragRow(layerCell(app, layerIndex: 0), onto: folderCell(app, named: "Folder 1"), dropDY: 0.5)

        XCTAssertEqual(rowFolder(app, layerIndex: 1), "Folder 1",
                       "Dropping onto the folder header should put the layer in the folder")
        // Its timeline row should now report a span rather than reading as empty.
        let folderTrack = app.otherElements["timeline.folderTrack.Folder 1"]
        XCTAssertTrue(folderTrack.waitForExistence(timeout: 5))
        XCTAssertNotEqual(folderTrack.value as? String, "empty")
    }

    /// Folders nest: dropping one folder onto another puts it inside, and the contained rows
    /// indent a level deeper.
    func testDroppingFolderOntoFolderNestsIt() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addFolderFromAddMenu(app) // Folder 1
        addFolderFromAddMenu(app) // Folder 2
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 2"].waitForExistence(timeout: 5))
        XCTAssertEqual(app.staticTexts["layerPanel.folder.Folder 2"].value as? String, "0",
                       "Sanity: both folders start at the top level")

        dragRow(folderCell(app, named: "Folder 2"), onto: folderCell(app, named: "Folder 1"), dropDY: 0.5)

        XCTAssertEqual(app.staticTexts["layerPanel.folder.Folder 2"].value as? String, "1",
                       "A folder dropped onto another should nest one level inside it")
        XCTAssertEqual(app.staticTexts["layerPanel.folder.Folder 1"].value as? String, "0")
    }

    /// Swiping a layer row reveals Delete and Duplicate — and no Edit, which moved to the options
    /// menu.
    func testSwipeRevealsDeleteAndDuplicateButNotEdit() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        revealSwipeActions(app, layerIndex: 0)
        XCTAssertTrue(app.buttons["Delete"].waitForExistence(timeout: 5))
        let duplicate = app.buttons["Duplicate"]
        XCTAssertTrue(duplicate.exists, "Swipe actions should offer Duplicate")
        XCTAssertFalse(app.buttons["layerPanel.row.0.edit"].exists, "Edit should no longer be a swipe action")

        duplicate.tap()
        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForExistence(timeout: 5),
                      "Duplicating should add a second layer")
        XCTAssertEqual(app.staticTexts["layerPanel.row.1"].label, "Vector 1 copy")
    }

    /// Tapping a layer selects it; tapping the selected one again opens its options menu, which is
    /// where Fill Reference lives now that the Edit sheet is gone.
    func testTappingSelectedLayerOpensOptionsAndTogglesFillReference() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let row = app.staticTexts["layerPanel.row.0"]
        XCTAssertTrue(row.waitForExistence(timeout: 5))
        XCTAssertFalse(app.otherElements["layerOptions.fillReferenceToggle"].exists,
                       "The options menu should not be showing before the second tap")

        row.tap() // select
        row.tap() // open options

        let toggle = app.switches["layerOptions.fillReferenceToggle"]
        XCTAssertTrue(toggle.waitForExistence(timeout: 5), "A second tap on the selected layer should open its options")

        let fillRef = app.staticTexts["layerPanel.row.0.fillRef"]
        XCTAssertEqual(fillRef.value as? String, "1", "Layers start as fill references")
        // Hit the switch itself — tapping a SwiftUI Toggle's label doesn't flip it.
        toggle.coordinate(withNormalizedOffset: CGVector(dx: 0.93, dy: 0.5)).tap()
        XCTAssertEqual(fillRef.value as? String, "0", "Toggling in the options menu should update the row")
    }

    /// Merge Down flattens a layer into the one below it, leaving a single layer behind. Same model
    /// call the two-finger pinch gesture makes.
    func testMergeDownFlattensTwoLayersIntoOne() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let point = safeOutsideCornerPoint(canvas)
        drawLine(on: canvas, from: point, to: CGVector(dx: point.dx + 0.12, dy: point.dy))

        openLayerPanel(app)
        let addLayer = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addLayer.waitForExistence(timeout: 5)) // the panel has to finish presenting first
        addLayer.tap() // layers: [Vector 1 (drawn on), Vector 2]
        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForExistence(timeout: 5))

        let top = app.staticTexts["layerPanel.row.1"]
        top.tap()
        top.tap()
        let mergeDown = app.buttons["layerOptions.mergeDown"]
        XCTAssertTrue(mergeDown.waitForExistence(timeout: 5))
        mergeDown.tap()

        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForNonExistence(timeout: 5),
                      "Merging should leave exactly one layer")
        XCTAssertTrue(app.staticTexts["layerPanel.row.0"].waitForExistence(timeout: 5))
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 0), false,
                       "The surviving layer should hold the flattened pixels in the raster tier, not a separate baked-image tier")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 0), 1,
                       "The flattened pixels of both layers should register as raster content")
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: point.dx + 0.06, dy: point.dy)),
                       "The merged artwork should still be on the canvas")
    }

    /// Merging a vector layer must leave the survivor as a genuine `.raster` layer, not `.vector`
    /// with emptied-out geometry — the inconsistency `rasterizeLayer` exists to prevent.
    func testMergeDownFromVectorLayerRasterizesTheSurvivor() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        app.buttons["toolbar.layersButton"].tap()
        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.press(forDuration: 1.2)
        let vectorItem = app.buttons["Vector Layer"]
        XCTAssertTrue(vectorItem.waitForExistence(timeout: 5))
        vectorItem.tap() // layers: [Vector 1, Vector 2 (active)]
        app.buttons["toolbar.layersButton"].tap() // close panel

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        drawLine(on: canvas, from: CGVector(dx: 0.3, dy: 0.5), to: CGVector(dx: 0.7, dy: 0.5))

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readVectorMarker(app, layerIndex: 1)?.isVector, true, "Setup: should be a vector layer")
        // Raster has to be asked for by name now that the plain `+` makes a vector layer, and a
        // raster layer on top is the whole premise: this test is about what merging one *into* a
        // vector layer leaves behind.
        addButton.press(forDuration: 1.2)
        let rasterItem = app.buttons["Raster Layer"]
        XCTAssertTrue(rasterItem.waitForExistence(timeout: 5), "The add menu should still offer a Raster Layer option")
        rasterItem.tap() // layers: [Vector 1, Vector 2, Layer 3 (active, raster, on top)]
        XCTAssertTrue(app.staticTexts["layerPanel.row.2"].waitForExistence(timeout: 5))

        let top = app.staticTexts["layerPanel.row.2"]
        top.tap()
        top.tap()
        let mergeDown = app.buttons["layerOptions.mergeDown"]
        XCTAssertTrue(mergeDown.waitForExistence(timeout: 5))
        mergeDown.tap() // merges Layer 3 into the vector layer below it

        XCTAssertTrue(app.staticTexts["layerPanel.row.2"].waitForNonExistence(timeout: 5))
        XCTAssertEqual(readVectorMarker(app, layerIndex: 1)?.isVector, false,
                       "The survivor should come out of the merge as a raster layer, not vector with emptied geometry")
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 1), false, "The survivor should hold the flattened pixels in the raster tier, not a separate baked-image tier")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 1), 1, "The flattened pixels should register as raster content")
        app.buttons["toolbar.layersButton"].tap() // close panel

        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: 0.5, dy: 0.5)), "The vector stroke should survive the merge")
    }

    // MARK: - §4.1/§4.2 group properties

    /// The regression phase 4b exists to fix: `toggleFolderVisibility` stopped writing through to
    /// children (§4.1), so the live canvas has to consult `isLayerEffectivelyVisible` per layer
    /// instead of the layer's own flag, or hiding a group does nothing on screen.
    func testHidingFolderHidesContentsOnCanvasAndReshowingRestoresThem() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let point = safeOutsideCornerPoint(canvas)
        drawLine(on: canvas, from: point, to: CGVector(dx: point.dx + 0.12, dy: point.dy))
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: point.dx + 0.06, dy: point.dy)),
                       "Setup: the stroke should be on the canvas")

        openLayerPanel(app)
        addFolderFromAddMenu(app) // Folder 1, empty, at the top
        dragRow(layerCell(app, layerIndex: 0), onto: folderCell(app, named: "Folder 1"), dropDY: 0.5)
        XCTAssertEqual(rowFolder(app, layerIndex: 0), "Folder 1", "Setup: the drawn layer should now be inside the folder")

        app.buttons["layerPanel.folder.Folder 1.visibility"].tap()
        app.buttons["toolbar.layersButton"].tap() // close panel to see the canvas

        XCTAssertTrue(waitUntilBlank(canvas, dx: point.dx + 0.06, dy: point.dy, timeout: 5),
                      "Hiding the folder should hide its contents on the live canvas, not just in the panel")

        app.buttons["toolbar.layersButton"].tap() // reopen
        app.buttons["layerPanel.folder.Folder 1.visibility"].tap() // show again
        app.buttons["toolbar.layersButton"].tap() // close

        XCTAssertTrue(waitUntilFilled(canvas, dx: point.dx + 0.06, dy: point.dy, timeout: 5),
                      "Re-showing the folder should restore its contents")
    }

    /// A folder row's tap already means expand/collapse, so its options — the pass-through toggle
    /// (§4.2) and Rename — live behind the row's own button instead of "tap the already-selected
    /// row again", which is how a layer row opens the same menu.
    func testFolderOptionsButtonOpensPassThroughToggleOffByDefault() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        addFolderFromAddMenu(app)
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 1"].waitForExistence(timeout: 5))
        XCTAssertFalse(app.switches["layerOptions.passThroughToggle"].exists,
                       "The options menu should not be showing before the button is tapped")

        app.buttons["layerPanel.folder.Folder 1.options"].tap()

        let toggle = app.switches["layerOptions.passThroughToggle"]
        XCTAssertTrue(toggle.waitForExistence(timeout: 5), "Tapping the folder's options button should open its menu")
        XCTAssertEqual(toggle.value as? String, "0", "Isolated is the default (§4.2), so Pass Through starts off")

        // Hit the switch itself — tapping a SwiftUI Toggle's label doesn't flip it.
        toggle.coordinate(withNormalizedOffset: CGVector(dx: 0.93, dy: 0.5)).tap()
        XCTAssertEqual(toggle.value as? String, "1", "Toggling should flip the switch")

        // Close and reopen to confirm the flip reached the model (`setFolderIsolated`), not just
        // the switch's own transient state.
        app.buttons["layerOptions.close"].tap()
        app.buttons["layerPanel.folder.Folder 1.options"].tap()
        XCTAssertEqual(app.switches["layerOptions.passThroughToggle"].value as? String, "1",
                       "The toggle should reflect the folder's isIsolated flag, not reset when the panel reopens")
    }

    /// Folder rows get the same opacity slider layer rows already have (§4.1), routed through
    /// `CanvasManager.setFolderOpacity` rather than the raw `layers[i].opacity = value` write the
    /// layer rows use (folders have no such index).
    func testFolderOpacitySliderPersistsThroughSetFolderOpacity() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        addFolderFromAddMenu(app)
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 1"].waitForExistence(timeout: 5))

        let slider = app.sliders["layerPanel.folder.Folder 1.opacity"]
        XCTAssertTrue(slider.waitForExistence(timeout: 5), "Folder rows should show the same opacity slider layer rows have")
        XCTAssertEqual(sliderNumericValue(slider), 100, "A fresh folder starts at full opacity")

        slider.adjust(toNormalizedSliderPosition: 0.3)
        let after = sliderNumericValue(slider)
        XCTAssertLessThan(after, 100, "Dragging the slider down should lower the folder's opacity")

        // Collapsing and re-expanding forces a fresh `configure()` from the model, which only
        // shows the dragged value if it reached `setFolderOpacity` rather than staying local to
        // the control (folder rows have no per-layer index for a raw write to land on).
        app.staticTexts["layerPanel.folder.Folder 1"].tap() // collapse
        app.staticTexts["layerPanel.folder.Folder 1"].tap() // expand
        XCTAssertEqual(sliderNumericValue(app.sliders["layerPanel.folder.Folder 1.opacity"]), after, accuracy: 1,
                       "The opacity should persist on the model, not reset when the row is reconfigured")
    }

    // MARK: - §7 blend modes

    /// The picker (`blendModeRow` in LayerPanel.swift) is a `Menu` grouped by `BlendMode.menuGroups`;
    /// picking an item should reach `CanvasManager.setLayerBlendMode` — not stay local to the control
    /// — show on the row without closing the options panel (§7's whole point: a mode has to be
    /// readable without opening options), and survive the panel closing and reopening.
    func testSettingLayerBlendModeShowsOnRowAndPersists() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let row = app.staticTexts["layerPanel.row.0"]
        XCTAssertTrue(row.waitForExistence(timeout: 5))
        row.tap() // select
        row.tap() // open options

        let picker = app.buttons["layerOptions.blendModeButton"]
        XCTAssertTrue(picker.waitForExistence(timeout: 5))
        XCTAssertEqual(picker.value as? String, "normal", "A fresh layer starts at Normal")

        let rowBlendMode = app.otherElements["layerPanel.row.0.blendMode"]
        XCTAssertEqual(rowBlendMode.value as? String, "normal", "Setup: the row's own marker should agree")

        picker.tap()
        let multiply = app.buttons["layerOptions.blendMode.multiply"]
        XCTAssertTrue(multiply.waitForExistence(timeout: 5), "The menu should list Multiply, grouped under darkening (§7)")
        multiply.tap()

        XCTAssertEqual(picker.value as? String, "multiply", "Picking a mode should update the button's own state")
        XCTAssertEqual(rowBlendMode.value as? String, "multiply",
                       "The row should reflect the new mode immediately — LayerRowModel.blendMode is part of its Equatable conformance, so the diffable data source reconfigures the cell")

        // Close and reopen to confirm the pick reached `setLayerBlendMode`, not just local control state.
        app.buttons["layerOptions.close"].tap()
        row.tap()
        row.tap()
        XCTAssertEqual(app.buttons["layerOptions.blendModeButton"].value as? String, "multiply",
                       "The picker should reflect the layer's blendMode, not reset when the panel reopens")
    }

    /// Same contract as the layer picker above, routed through `setFolderBlendMode` instead — the
    /// group side of §7, which is the same picker (`blendModeRow`) reused rather than a second one.
    func testSettingFolderBlendModeShowsOnRowAndPersists() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        addFolderFromAddMenu(app)
        XCTAssertTrue(app.staticTexts["layerPanel.folder.Folder 1"].waitForExistence(timeout: 5))

        app.buttons["layerPanel.folder.Folder 1.options"].tap()
        let picker = app.buttons["layerOptions.blendModeButton"]
        XCTAssertTrue(picker.waitForExistence(timeout: 5))
        XCTAssertEqual(picker.value as? String, "normal", "A fresh folder starts at Normal")

        picker.tap()
        let screen = app.buttons["layerOptions.blendMode.screen"]
        XCTAssertTrue(screen.waitForExistence(timeout: 5), "The menu should list Screen, grouped under lightening (§7)")
        screen.tap()

        XCTAssertEqual(picker.value as? String, "screen")
        let rowBlendMode = app.otherElements["layerPanel.folder.Folder 1.blendMode"]
        XCTAssertEqual(rowBlendMode.value as? String, "screen",
                       "The folder row should reflect the new mode the same way a layer row does")

        // Close and reopen to confirm the pick reached `setFolderBlendMode`, not just local control state.
        app.buttons["layerOptions.close"].tap()
        app.buttons["layerPanel.folder.Folder 1.options"].tap()
        XCTAssertEqual(app.buttons["layerOptions.blendModeButton"].value as? String, "screen",
                       "The picker should reflect the folder's blendMode, not reset when the panel reopens")
    }

}
