// Generated by a mechanical split of the original monolithic PaintSoftwareUITests
// class. Test bodies are unchanged; see PaintUITestCase for the shared helpers.
//
// Split further (2026-08-15) into three classes so xcodebuild's per-class parallel
// scheduling doesn't serialize this file's 392s behind one unit. Test bodies are
// unchanged; only which class each method sits in moved.
// testInterpolateModeEndToEndFromGestureToScrub alone measures 189s, so it is isolated
// on its own class rather than dragging four other tests along with it.

import XCTest

final class TimelineGestureUITests: PaintUITestCase {

    func testCreateCanvasReachesEditorWithoutFreezing() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app), "Editor should load promptly after tapping Create Canvas")
    }

    /// **The onion-skin panel's only UI test, deliberately.** What each control *decides* — which cel
    /// a slot shows, what a linked drag does to the other sliders, how large the composite may be —
    /// is `OnionSkinLogicTests`, headless and in two seconds. What XCUITest is needed for, and the
    /// only thing it is asked for here, is that the two-stage button reaches the panel at all and
    /// that every control the owner asked for is on it. A suite that drove ten rotated sliders
    /// through a popover would cost minutes and pin layout rather than behaviour.
    func testTheOnionSkinPanelOpensOnTheSecondTapAndCarriesEveryControl() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let button = app.buttons["timeline.onionSkinToggle"]
        XCTAssertTrue(button.waitForExistence(timeout: 5))

        // Onion skin ships on, so the first tap is already the second stage. The panel is not up
        // before it — otherwise "the tap opened it" is not what this observed.
        XCTAssertFalse(app.buttons["onionPanel.turnOff"].exists, "Setup: the panel starts closed")
        button.tap()

        let turnOff = app.buttons["onionPanel.turnOff"]
        XCTAssertTrue(turnOff.waitForExistence(timeout: 5), "a tap while onion skin is on opens the panel")

        for identifier in ["onionPanel.neighbourhoodPicker",
                           "onionPanel.placementPicker",
                           "onionPanel.previousCountSlider",
                           "onionPanel.loopToggle",
                           "onionPanel.nextCountSlider",
                           "onionPanel.colouringPicker",
                           "onionPanel.resolutionPicker",
                           // Both halves of the owner's 2026-08-18 ruling: each option's real
                           // composite size, always visible, and the note line under it that carries
                           // the caution when there is one.
                           "onionPanel.resolutionSizes",
                           "onionPanel.resolutionNote",
                           "onionPanel.tintBar",
                           "onionPanel.linkOpacityToggle",
                           "onionPanel.previous.opacity1",
                           "onionPanel.next.opacity1"] {
            XCTAssertTrue(app.descendants(matching: .any)[identifier].waitForExistence(timeout: 3),
                          "\(identifier) is on the panel")
        }

        // Linked is the owner's default and the panel must say so out loud, since it is the one
        // setting whose effect is invisible until a slider is dragged.
        XCTAssertEqual(app.descendants(matching: .any)["onionPanel.linkOpacityToggle"].value as? String, "on",
                       "linked opacity is on by default")

        // And the off switch really is the off switch: turning it off closes the panel with it, so
        // the button cannot leave the artist with a panel describing something that is not drawing.
        turnOff.tap()
        XCTAssertTrue(waitForDisappearance(of: turnOff, timeout: 5),
                      "turning onion skin off dismisses its panel")
    }

    /// **What the artist sees, driven rather than modelled** — TODO (40), the owner's placement
    /// ruling, at the pixel.
    ///
    /// Behind and In Front both draw the ghost *on top of the compositor* now, so the only thing
    /// separating them is the clip: Behind subtracts the current drawing's own alpha, In Front does
    /// not. That difference is invisible to every headless assertion in `OnionSkinLogicTests`, which
    /// can hold the clip image but cannot see whether it reaches Core Animation — so this is the one
    /// test that fails if the mask stops being applied while the picker still reads Behind.
    ///
    /// The probe is where the two drawings cross. Under Behind that pixel must be the artist's own
    /// ink, indistinguishable from a point on the same stroke the ghost never reaches; under In Front
    /// the ghost's tint sits over it and the two points must differ.
    func testABehindGhostIsCutAwayWhereTheArtistsOwnInkCoversItAndAnInFrontGhostIsNot() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5), "canvas.host exists")

        // Drawing A — a horizontal line through the middle. This is what the ghost will show.
        drawLine(on: canvas, from: CGVector(dx: 0.30, dy: 0.50), to: CGVector(dx: 0.70, dy: 0.50))
        let crossing = (dx: 0.50, dy: 0.50)
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: crossing.dx, dy: crossing.dy)),
                       "Setup: drawing A crosses the probe point")

        // Split the block so there is a second drawing to stand on, and add it.
        performDrag(app, identifier: "timeline.cel.0.0.rightHandle", totalDelta: -260)
        let firstBlock = app.otherElements["timeline.cel.0.0"]
        let shrunk = try XCTUnwrap(readCel(app, layerIndex: 0, celIndex: 0),
                                   "Could not read the block after shrinking it")
        XCTAssertLessThan(shrunk.length, 12, "Setup: the drag has to leave a gap to add a drawing into")
        let gapSlot = firstBlock.coordinate(withNormalizedOffset:
            CGVector(dx: (Double(shrunk.length) + 2.0) / Double(shrunk.length), dy: 0.5))
        gapSlot.tap()
        gapSlot.tap()
        let addDrawing = app.buttons["Add Drawing"]
        XCTAssertTrue(addDrawing.waitForExistence(timeout: 5), "a second tap on the empty slot opens its menu")
        addDrawing.tap()

        // Onion skin ships on and Behind is its default placement, so the ghost of drawing A is
        // already on screen over an otherwise blank drawing B.
        let ghostOnly = try XCTUnwrap(rgbaPixel(of: canvas, dx: crossing.dx, dy: crossing.dy))
        XCTAssertFalse(isWhitish(ghostOnly),
                       "Setup: the ghost of drawing A reaches the probe on the new blank drawing")
        attachScreen("onion-01-behind-ghost-over-blank-drawing")

        // Drawing B — a vertical line crossing A at the probe. Its lower half is ink the ghost
        // never touches, which is the operand every assertion below compares against.
        drawLine(on: canvas, from: CGVector(dx: 0.50, dy: 0.38), to: CGVector(dx: 0.50, dy: 0.64))
        let inkOnly = try XCTUnwrap(rgbaPixel(of: canvas, dx: 0.50, dy: 0.60))
        XCTAssertFalse(isWhitish(inkOnly), "Setup: drawing B's own ink reaches the lower probe")
        XCTAssertGreaterThan(channelDistance(inkOnly, ghostOnly), 40,
                             "Setup: the ghost's tint and the artist's ink are told apart by colour")

        let behind = try XCTUnwrap(rgbaPixel(of: canvas, dx: crossing.dx, dy: crossing.dy))
        attachScreen("onion-02-behind-ghost-cut-by-the-artists-ink")
        XCTAssertLessThan(channelDistance(behind, inkOnly), 20,
                          "Behind: the ghost is masked out where the artist's own ink covers it, so "
                          + "the crossing is the same ink as the stroke's clear half")

        // The same picture with the one setting changed. The panel is two-stage: onion skin is on,
        // so the first tap opens the panel rather than switching it off.
        //
        // **The panel is left open and nothing else is touched.** The first version of this test
        // dismissed the popover by tapping the timeline ruler — which moves the playhead, and moved
        // it clean off both drawings to frame 29. Every assertion below then passed against a blank
        // canvas: "the crossing differs from the ink" is trivially true of white paper. The frame
        // label is read back for exactly that reason.
        let frameBefore = try XCTUnwrap(readFrameLabel(app), "the frame label reads before the change")
        app.buttons["timeline.onionSkinToggle"].tap()
        let placement = app.segmentedControls["onionPanel.placementPicker"]
        XCTAssertTrue(placement.waitForExistence(timeout: 5), "the placement picker is on the panel")
        placement.buttons["In Front"].tap()

        let frameAfter = try XCTUnwrap(readFrameLabel(app), "the frame label reads after the change")
        XCTAssertEqual(frameAfter.current, frameBefore.current,
                       "Setup: changing the placement must not have moved the playhead off the drawing")

        let inFront = try XCTUnwrap(rgbaPixel(of: canvas, dx: crossing.dx, dy: crossing.dy))
        attachScreen("onion-03-in-front-ghost-over-the-artists-ink")
        XCTAssertFalse(isWhitish(inFront),
                       "Setup: there is still something at the crossing — ink, ghost, or both")
        XCTAssertGreaterThan(channelDistance(inFront, inkOnly), 20,
                             "In Front: the ghost draws over the artist's ink, so the crossing is "
                             + "no longer the same colour as the stroke's clear half")
        XCTAssertGreaterThan(channelDistance(inFront, behind), 20,
                             "and the two placements therefore differ at the one pixel that names them")
    }

    /// Largest per-channel difference between two probes — a comparison that survives the ghost's
    /// tint being on one channel rather than all three, which a luminance difference would not.
    private func channelDistance(_ a: (r: UInt8, g: UInt8, b: UInt8, a: UInt8),
                                 _ b: (r: UInt8, g: UInt8, b: UInt8, a: UInt8)) -> Int {
        max(abs(Int(a.r) - Int(b.r)), abs(Int(a.g) - Int(b.g)), abs(Int(a.b) - Int(b.b)))
    }

    /// Kept on success as well as on failure: these three are the "drive it and look at it" record
    /// this change is required to produce, and a `.deleteOnSuccess` lifetime would throw away
    /// exactly the run worth looking at.
    private func attachScreen(_ name: String) {
        let shot = XCTAttachment(screenshot: XCUIScreen.main.screenshot())
        shot.name = name
        shot.lifetime = .keepAlways
        add(shot)
    }

    /// `waitForExistence`'s missing twin. A polling loop was written first and is the wrong shape:
    /// `waitForExistence` returns immediately while the element is still there, so the loop spins the
    /// CPU for the whole timeout in exactly the failing case, on a machine CLAUDE.md records as
    /// returning wrong answers under load.
    private func waitForDisappearance(of element: XCUIElement, timeout: TimeInterval) -> Bool {
        let gone = expectation(for: NSPredicate(format: "exists == false"), evaluatedWith: element)
        return XCTWaiter().wait(for: [gone], timeout: timeout) == .completed
    }

    func testTappingCelBlockMovesPlayheadToTappedFrame() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let cel = app.otherElements["timeline.cel.0.0"]
        XCTAssertTrue(cel.waitForExistence(timeout: 5))

        // Default scene is 12 frames, one cel spanning all of them. Tap at the block's
        // midpoint (safely inside the middle strip, clear of the edge-resize handles) and
        // expect the playhead to land on the frame under that exact point, not some
        // offset/incorrect frame.
        let target = cel.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.5))
        target.tap()

        guard let (current, total) = readFrameLabel(app) else {
            XCTFail("Could not read frame label")
            return
        }
        XCTAssertEqual(total, 12)
        XCTAssertEqual(current, 7, "Tapping the block's midpoint should move the playhead to frame 7 (index 6 of 12), not \(current)")
    }

    func testDraggingRightEdgeHandleShrinksCel() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        guard let before = readCel(app, layerIndex: 0, celIndex: 0) else {
            XCTFail("Could not read initial cel state")
            return
        }
        XCTAssertEqual(before.start, 0)
        XCTAssertEqual(before.length, 12)

        let rightHandle = app.otherElements["timeline.cel.0.0.rightHandle"]
        XCTAssertTrue(rightHandle.waitForExistence(timeout: 5))

        // Drag the right edge well to the left (requesting more than the minimum needed, since
        // XCUITest's synthetic drags can undershoot their requested distance) which should
        // shrink the block from 12 frames without moving its start.
        performDrag(app, identifier: "timeline.cel.0.0.rightHandle", totalDelta: -150)

        guard let after = readCel(app, layerIndex: 0, celIndex: 0) else {
            XCTFail("Could not read cel state after drag")
            return
        }
        XCTAssertEqual(after.start, 0, "Dragging the right edge should not move the start frame")
        XCTAssertLessThan(after.length, before.length, "Dragging the right edge left should shrink the cel, but length stayed at \(after.length)")
    }

    /// Diagnostic: isolates whether XCUITest synthetic drags deliver sustained intermediate
    /// movement at all in this simulator/OS, independent of the edge-handle's nested geometry.
    /// The ruler's own scrub gesture (DragGesture(minimumDistance: 0) reading value.location)
    /// is the simplest possible drag target in this view.
    func testDraggingAcrossRulerMovesPlayheadProgressively() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let ruler = app.otherElements["timeline.ruler"]
        XCTAssertTrue(ruler.waitForExistence(timeout: 5))

        // Start near the ruler's left edge and drag right by ~150pt (5 frames at 30pt/frame).
        let start = ruler.coordinate(withNormalizedOffset: CGVector(dx: 0.02, dy: 0.5))
        let end = start.withOffset(CGVector(dx: 150, dy: 0))
        start.press(forDuration: 0.2, thenDragTo: end, withVelocity: .slow, thenHoldForDuration: 0.2)

        guard let (current, _) = readFrameLabel(app) else {
            XCTFail("Could not read frame label")
            return
        }
        XCTAssertGreaterThan(current, 1, "Dragging across the ruler by 150pt should have moved the playhead well past frame 1, but landed on \(current)")
    }

    func testDraggingLeftEdgeHandleShrinksCelWithoutMovingEnd() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let leftHandle = app.otherElements["timeline.cel.0.0.leftHandle"]
        XCTAssertTrue(leftHandle.waitForExistence(timeout: 5))

        // Drag the left edge well to the right, which should move startFrame forward from 0
        // while keeping the end frame fixed at 12.
        performDrag(app, identifier: "timeline.cel.0.0.leftHandle", totalDelta: 150)

        guard let after = readCel(app, layerIndex: 0, celIndex: 0) else {
            XCTFail("Could not read cel state after drag")
            return
        }
        XCTAssertGreaterThan(after.start, 0, "Dragging the left edge right should move the start frame forward, but it stayed at 0")
        XCTAssertEqual(after.start + after.length, 12, "The end frame should stay fixed at 12 while only the start moves, but start+length was \(after.start + after.length)")
    }

    /// **The keyframe workflow's entry point, and the one thing about it a logic test cannot see** —
    /// KEYFRAMES §2.26: *"select on cel, tap again, tap add keyframe icon in the menu."*
    ///
    /// Everything it decides is pinned in `KeyframeControlLogicTests` and `TimelineKeyMarkersLogicTests`
    /// in seconds. What only a touch can answer is whether the two ends actually meet: that the second
    /// tap raises a menu carrying the item, that the item writes onto **the frame that was tapped**,
    /// and that the mark it leaves is *visible* — which is the half that was missing, because a
    /// keyframe carrying no channel is exactly what this workflow's first step produces and the band
    /// used to draw it as nothing at all.
    ///
    /// The two conditional items are read in both states from one document, which is what makes them
    /// evidence: Remove is absent before the mark exists and present after.
    func testTheCelMenuPlacesAndRemovesAKeyframeAtTheTappedFrame() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let cel = app.otherElements["timeline.cel.0.0"]
        XCTAssertTrue(cel.waitForExistence(timeout: 5))
        let band = app.otherElements["timeline.keyMarkers.0"]
        XCTAssertFalse(band.exists, "PREMISE: an untouched document has no markers and hides the band")

        // The same midpoint `testTappingCelBlockMovesPlayheadToTappedFrame` uses. First tap moves the
        // playhead there, second raises the menu — the gate in `Coordinator.handleTapOnCel`.
        let target = cel.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.5))
        target.tap()
        guard let (tappedFrame, _) = readFrameLabel(app) else {
            XCTFail("Could not read frame label after the first tap")
            return
        }
        target.tap()

        let add = app.buttons["timeline.menu.Add Keyframe"]
        XCTAssertTrue(add.waitForExistence(timeout: 5), "The second tap raises the cel menu")
        XCTAssertFalse(app.buttons["timeline.menu.Remove Keyframe"].exists,
                       "There is no mark on this frame yet, so there is nothing to offer to remove")
        add.tap()

        XCTAssertTrue(band.waitForExistence(timeout: 5), """
            A keyframe carrying no channel drew nothing on the timeline, so the artist places \
            keyframe A blind — which is the whole first step of §2.27's workflow
            """)
        // The label is 1-based and marker frames are 0-based. Asserting against the label rather than
        // against a literal is what makes this a pin on *the frame that was tapped* rather than on
        // where the block happens to sit.
        XCTAssertEqual(band.value as? String, "\(tappedFrame - 1)",
                       "The mark lands on the playhead, and it draws as any other keyframe does")

        // The playhead has not moved, so one tap is now the second stage.
        target.tap()
        let remove = app.buttons["timeline.menu.Remove Keyframe"]
        XCTAssertTrue(remove.waitForExistence(timeout: 5),
                      "The frame carries a mark now, so the menu offers to take it back")
        remove.tap()

        XCTAssertTrue(waitForDisappearance(of: band, timeout: 5),
                      "Removing the only keyframe leaves the row with none, and the band hides again")
    }

}

final class UndoAndLayerHistoryUITests: PaintUITestCase {

    /// The timeline's name column reorders too: press and hold a name, then drag it.
    func testTimelineNameColumnReordersOnPressAndHold() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        let addLayer = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addLayer.waitForExistence(timeout: 5)) // the panel has to finish presenting first
        addVectorLayerFromOpenPanel(app) // layers: [Vector 1, Vector 2] — vector is the default kind
        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForExistence(timeout: 5))
        app.buttons["toolbar.layersButton"].tap() // close the panel so it can't cover the timeline

        let topName = app.staticTexts["timeline.layerName.1"]
        XCTAssertTrue(topName.waitForExistence(timeout: 5))
        XCTAssertEqual(topName.label, "Vector 2")

        // One row down is rowHeight (34) + the 2pt gap between rows.
        let start = topName.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.5))
        start.press(forDuration: 0.9, thenDragTo: start.withOffset(CGVector(dx: 0, dy: 40)),
                    withVelocity: .slow, thenHoldForDuration: 0.5)

        XCTAssertEqual(app.staticTexts["timeline.layerName.0"].label, "Vector 2",
                       "Dragging a timeline name down should restack that layer")
    }

    /// The core regression this feature addresses: undo used to be scoped to whichever layer's
    /// private UndoManager was "active," and switching the active layer cleared that layer's
    /// history. With a single global stack, undo must keep walking back through every action in
    /// the order it happened, even after the active layer has changed since.
    func testUndoWalksBackAcrossLayersRegardlessOfActiveLayer() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))
        layersButton.tap()

        layersButton.tap() // close so drawing isn't blocked by the panel
        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        var start = canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.3, dy: 0.3))
        var end = start.withOffset(CGVector(dx: 80, dy: 0))
        start.press(forDuration: 0.1, thenDragTo: end) // stroke on layer 0

        layersButton.tap() // reopen
        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addVectorLayerFromOpenPanel(app) // layer 1 added and made active

        layersButton.tap() // close to draw again
        start = canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.6, dy: 0.6))
        end = start.withOffset(CGVector(dx: 80, dy: 0))
        start.press(forDuration: 0.1, thenDragTo: end) // stroke on layer 1 (now active)

        layersButton.tap() // reopen to verify + switch active layer back
        // Vector markers, not `readLayerStrokeCount`: both layers are vector now that it is the
        // default kind, so their strokes are geometry and the raster tier reads 0 on both. What is
        // under test — that one global undo stack walks back in action order regardless of which
        // layer is active — does not change.
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 1, "Layer 0 should have its own stroke")
        XCTAssertEqual(readVectorMarker(app, layerIndex: 1)?.strokes, 1, "Layer 1 should have its own stroke")

        // Switch the active layer back to layer 0 — under the old per-layer design this would
        // have repointed (and cleared) whatever stack "undo" operates on.
        let bottomRow = app.staticTexts["layerPanel.row.0"]
        XCTAssertTrue(bottomRow.waitForExistence(timeout: 5))
        bottomRow.tap()
        XCTAssertTrue(app.images["layerPanel.row.0.current"].waitForExistence(timeout: 5), "Layer 0 should now be active")

        // Three actions sit on the global stack in this order: stroke on layer 0, adding layer 1
        // (itself now undoable — a "layer change" this overhaul covers), stroke on layer 1.
        let undo = app.buttons["sideToolbar.undoButton"]
        XCTAssertTrue(undo.waitForExistence(timeout: 5))
        XCTAssertTrue(undo.isEnabled)
        undo.tap()

        XCTAssertEqual(readVectorMarker(app, layerIndex: 1)?.strokes, 0,
                       "The first undo (with layer 0 active) should still undo the most recent action — layer 1's stroke — not silently no-op or hit layer 0's history")
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 1,
                       "Layer 0's stroke should be untouched by the first undo")

        undo.tap()
        XCTAssertFalse(app.staticTexts["layerPanel.row.1"].exists,
                       "The second undo should reach back to adding layer 1 and remove it entirely")
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 1,
                       "Layer 0's stroke should still be untouched by the second undo")

        undo.tap()
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 0,
                       "The third undo should reach back further still and undo layer 0's stroke")
    }

    /// Deleting a layer must be undoable, restoring both its existence and its content — the
    /// operation had no undo registration at all before this feature.
    func testDeletingLayerIsUndoableAndRestoresContent() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))
        layersButton.tap()

        layersButton.tap() // close to draw
        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let start = canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.3, dy: 0.3))
        let end = start.withOffset(CGVector(dx: 80, dy: 0))
        start.press(forDuration: 0.1, thenDragTo: end) // stroke on layer 0

        layersButton.tap() // reopen
        // The vector marker, not `readLayerStrokeCount`: that reads the *raster* tier, and vector is
        // the default layer kind now, so this stroke is geometry in the cel's display list. What the
        // test is about — that undo brings the deleted layer's content back — is unchanged.
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 1)

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addVectorLayerFromOpenPanel(app) // layer 1 added, becomes active; layer 0 keeps its stroke

        swipeDeleteLayerRow(app, layerIndex: 0)
        XCTAssertTrue(app.staticTexts["layerPanel.row.0"].waitForExistence(timeout: 5))
        XCTAssertFalse(app.staticTexts["layerPanel.row.1"].exists, "Only the surviving layer should remain")

        let undo = app.buttons["sideToolbar.undoButton"]
        XCTAssertTrue(undo.waitForExistence(timeout: 5))
        XCTAssertTrue(undo.isEnabled, "Deleting a layer should be undoable")
        undo.tap()

        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForExistence(timeout: 5), "Undo should restore the deleted layer")
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 1,
                       "The restored layer's stroke content should come back intact, not blank")
    }

    /// Drag-reordering layers must be undoable, restoring the original stacking order.
    func testReorderingLayersIsUndoable() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addVectorLayerFromOpenPanel(app)
        addVectorLayerFromOpenPanel(app)
        // layers bottom-to-top: [Vector 1, Vector 2, Vector 3]; displayed top-to-bottom: 3, 2, 1.

        let bottomRow = app.staticTexts["layerPanel.row.0"]
        XCTAssertTrue(bottomRow.waitForExistence(timeout: 5))
        XCTAssertEqual(bottomRow.label, "Vector 1")

        dragRow(layerCell(app, layerIndex: 2), onto: layerCell(app, layerIndex: 0), dropDY: 0.95)
        XCTAssertEqual(app.staticTexts["layerPanel.row.0"].label, "Vector 3", "Sanity-check the drag actually landed")

        let undo = app.buttons["sideToolbar.undoButton"]
        XCTAssertTrue(undo.waitForExistence(timeout: 5))
        XCTAssertTrue(undo.isEnabled, "Reordering layers should be undoable")
        undo.tap()

        XCTAssertEqual(app.staticTexts["layerPanel.row.0"].label, "Vector 1", "Undo should restore the original bottom-to-top order")
        XCTAssertEqual(app.staticTexts["layerPanel.row.2"].label, "Vector 3", "Undo should restore the original top layer too")
    }

    /// A cel resize drag must register as ONE undo step for the whole gesture, not one per
    /// intermediate frame position it passes through — otherwise a single undo would only
    /// partially reverse the drag instead of fully restoring the cel's original bounds.
    func testCelResizeDragUndoesInOneStep() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        guard let before = readCel(app, layerIndex: 0, celIndex: 0) else {
            XCTFail("Could not read initial cel state")
            return
        }
        XCTAssertEqual(before.start, 0)
        XCTAssertEqual(before.length, 12)

        performDrag(app, identifier: "timeline.cel.0.0.rightHandle", totalDelta: -150)

        guard let afterDrag = readCel(app, layerIndex: 0, celIndex: 0) else {
            XCTFail("Could not read cel state after drag")
            return
        }
        XCTAssertLessThan(afterDrag.length, before.length, "Sanity-check the drag actually shrank the cel")

        let undo = app.buttons["sideToolbar.undoButton"]
        XCTAssertTrue(undo.waitForExistence(timeout: 5))
        XCTAssertTrue(undo.isEnabled, "The resize should be undoable")
        undo.tap()

        guard let afterUndo = readCel(app, layerIndex: 0, celIndex: 0) else {
            XCTFail("Could not read cel state after undo")
            return
        }
        XCTAssertEqual(afterUndo.start, before.start, "One undo should fully restore the cel's original start")
        XCTAssertEqual(afterUndo.length, before.length,
                       "One undo should fully restore the cel's original length in a single step, not just partially reverse one frame of the drag")
    }

}

final class InterpolationWorkflowUITests: PaintUITestCase {

    /// The one XCUITest for interpolation's gesture path — deliberately one, not a suite.
    ///
    /// XCUITests are 99.3% of this suite's runtime (REFACTOR_BASELINE.md), so everything about
    /// interpolation that can be asserted without a simulator gesture is in
    /// `InterpolationWorkflowLogicTests` instead. What is left here is exactly what a logic test
    /// cannot reach: that the mode's controls are wired up — that Set as Reference on the
    /// interpolate bar flags the block under the playhead, that Generate is reachable from that same
    /// bar, and that dragging the timing slider changes what is on the canvas.
    ///
    /// Structure: two keyframes on one vector layer, and the in-between generated on a *second*
    /// vector layer whose single cel spans the scene. That avoids splitting one layer into three
    /// blocks — the target only has to not be a reference, and it may live on any layer.
    func testInterpolateModeEndToEndFromGestureToScrub() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app), "reached editor")
        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5), "canvas.host exists")

        // Keyframe A: an L on the left of a new vector layer. An L rather than a straight line
        // because parallel strokes pin neither orientation nor position for the registration's ICP —
        // a corner gives the fit something to hold onto.
        addVectorLayer(app)
        drawLine(on: canvas, from: CGVector(dx: 0.22, dy: 0.42), to: CGVector(dx: 0.34, dy: 0.42))
        drawLine(on: canvas, from: CGVector(dx: 0.34, dy: 0.42), to: CGVector(dx: 0.34, dy: 0.56))

        // Split the layer so there is a second block to be the other keyframe.
        performDrag(app, identifier: "timeline.cel.1.0.rightHandle", totalDelta: -260)
        let firstBlock = app.otherElements["timeline.cel.1.0"]
        let shrunk = try XCTUnwrap(readCel(app, layerIndex: 1, celIndex: 0),
                                   "Could not read the vector layer's block after shrinking it")
        XCTAssertLessThan(shrunk.length, 12, "Setup: the drag has to leave a gap to add a block into")

        // Tap two frames past the block's own right edge — an offset beyond the element's bounds,
        // which is the only handle a test has on an empty timeline slot. Two taps, not one: the
        // slot's menu is gated the same way a block's already was (tap once to select the frame,
        // tap the now-selected frame again to open its menu), so the first tap only moves the
        // playhead there and the second is what raises "Add Drawing".
        let gapSlot = firstBlock.coordinate(withNormalizedOffset:
            CGVector(dx: (Double(shrunk.length) + 2.0) / Double(shrunk.length), dy: 0.5))
        gapSlot.tap()
        gapSlot.tap()
        let addDrawing = app.buttons["Add Drawing"]
        XCTAssertTrue(addDrawing.waitForExistence(timeout: 5), "A second tap on the selected empty slot opens its menu")
        addDrawing.tap()

        // Keyframe C: the same L, moved right.
        drawLine(on: canvas, from: CGVector(dx: 0.62, dy: 0.42), to: CGVector(dx: 0.74, dy: 0.42))
        drawLine(on: canvas, from: CGVector(dx: 0.74, dy: 0.42), to: CGVector(dx: 0.74, dy: 0.56))

        // The cel the in-between lands on: a second vector layer, spanning the whole scene.
        addVectorLayer(app)

        // One tap on the timeline's own interpolate button *is* entering the mode — there is no
        // panel and no switch in the way. A second tap would open the options popover instead.
        let interpolateButton = app.buttons["timeline.interpolateButton"]
        XCTAssertTrue(interpolateButton.waitForExistence(timeout: 5), "timeline.interpolateButton exists")
        interpolateButton.tap()

        // The controls under test. Set as Reference acts on the block under the playhead, so each
        // reference is "tap the block to go there, then press the button" — and the bar is on screen
        // the whole time, which is the point of it living above the timeline rather than in a panel.
        let setReference = app.buttons["interpolate.setReference"]
        XCTAssertTrue(setReference.waitForExistence(timeout: 5),
                      "The interpolate bar appears above the timeline once the mode is on")
        XCTAssertFalse(readCelIsReference(app, layerIndex: 1, celIndex: 0),
                       "Setup: nothing is a reference yet")
        app.otherElements["timeline.cel.1.0"].tap()
        setReference.tap()
        app.otherElements["timeline.cel.1.1"].tap()
        setReference.tap()
        XCTAssertTrue(readCelIsReference(app, layerIndex: 1, celIndex: 0),
                      "Set as Reference should flag the block under the playhead")
        XCTAssertTrue(readCelIsReference(app, layerIndex: 1, celIndex: 1), "second block flagged as reference")

        // Make the second vector layer's block the target — a plain tap still means "go here".
        app.otherElements["timeline.cel.2.0"].tap()

        // Interpolate mode's onion skin draws *both* references, so leaving it on would put ink at
        // each keyframe's position and make a pixel probe unable to tell the in-between from the
        // skin. The skin has its own logic test; this one is about the in-between.
        let onionSkin = app.buttons["timeline.onionSkinToggle"]
        XCTAssertTrue(onionSkin.waitForExistence(timeout: 5), "timeline.onionSkinToggle exists")
        // **Two taps, not one, and the second is not optional.** The button is two-stage since the
        // onion-skin panel landed (2026-08-17): onion skin is on by default, so the first tap opens
        // the panel rather than switching it off, and the off switch lives inside the panel — see
        // `AnimationTimeline.onionSkinButton` and `OnionSkinPanel`. A single tap here would leave the
        // skin drawing and the probe below unable to tell an in-between from a keyframe's ghost.
        onionSkin.tap()
        let turnOff = app.buttons["onionPanel.turnOff"]
        XCTAssertTrue(turnOff.waitForExistence(timeout: 5), "the onion-skin panel opens on the second stage")
        turnOff.tap()

        let probe = (dx: 0.48, dy: 0.42)
        XCTAssertTrue(isWhitish(rgbaPixel(of: canvas, dx: probe.dx, dy: probe.dy)),
                      "Setup: the middle of the canvas is blank before the in-between exists")

        let generate = app.buttons["interpolate.generate"]
        XCTAssertTrue(generate.waitForExistence(timeout: 5), "interpolate.generate exists")
        XCTAssertTrue(generate.isEnabled, "Two references and an empty target cel — Generate should be live")
        generate.tap()

        // Built only on failure — it costs ~20 element screenshots, and "no ink at one point" is
        // almost impossible to diagnose from a bare assertion. Where the ink actually landed, and what
        // the timeline looked like when it did, is the whole diagnosis: ink at the keyframes but not
        // between them means the warp is identity, and a block reading `nil` means the setup drifted.
        func inkReport() -> String {
            let sweep = stride(from: 0.14, through: 0.86, by: 0.04).map { x in
                String(format: "%.2f:%@", x, isWhitish(rgbaPixel(of: canvas, dx: x, dy: probe.dy)) ? "." : "#")
            }.joined(separator: " ")
            let blocks = [(1, 0), (1, 1), (2, 0)].map { l, c -> String in
                let cel = readCel(app, layerIndex: l, celIndex: c)
                let ref = readCelIsReference(app, layerIndex: l, celIndex: c) ? "*" : ""
                return "\(l).\(c)=\(cel.map { "\($0.start)+\($0.length)" } ?? "nil")\(ref)"
            }.joined(separator: " ")
            return "sweep at dy=\(probe.dy): \(sweep) | blocks \(blocks) "
                + "| frame \(readFrameLabel(app).map { "\($0.current)/\($0.total)" } ?? "?")"
        }

        if isWhitish(rgbaPixel(of: canvas, dx: probe.dx, dy: probe.dy)) {
            XCTFail("At t = 0.5 the in-between should have ink about halfway between the keyframes. \(inkReport())")
        }

        // Scrub to t = 0, where the frame *is* keyframe A — so the midpoint goes back to blank.
        let slider = app.sliders["interpolate.tSlider"]
        XCTAssertTrue(slider.waitForExistence(timeout: 5), "interpolate.tSlider exists")
        slider.adjust(toNormalizedSliderPosition: 0)

        if !isWhitish(rgbaPixel(of: canvas, dx: probe.dx, dy: probe.dy)) {
            XCTFail("Dragging the slider to 0 should move the drawing back onto keyframe A. \(inkReport())")
        }

        // --- Editing *at* the in-between ---
        //
        // This half is here rather than in a logic test for one reason: everything below the gesture
        // is already covered by `InterpolationWorkflowLogicTests`, and what is not covered anywhere
        // else is `StrokeCanvasView`'s routing — that a touch on an interpolated cel becomes a
        // `LocalEdit` instead of ink in a display list nothing renders, and that the memoized preview
        // notices. A bug in `addCel` is the precedent: it was invisible until a gesture ran
        // through the real path.
        slider.adjust(toNormalizedSliderPosition: 0.5)

        // A row just below the L, clear of every keyframe's ink at every `t`, so anything found on it
        // can only be the edit. It is also outside the lattice, which puts the lattice-expansion path
        // under the same test rather than needing its own.
        let editRow = 0.60
        func inkedColumns() -> [Double] {
            stride(from: 0.14, through: 0.92, by: 0.02).filter {
                !isWhitish(rgbaPixel(of: canvas, dx: $0, dy: editRow))
            }
        }
        func meanColumn(_ columns: [Double]) -> Double {
            columns.reduce(0, +) / Double(max(1, columns.count))
        }
        XCTAssertTrue(inkedColumns().isEmpty,
                      "Setup: the row the edit is drawn on has to start blank")

        drawLine(on: canvas, from: CGVector(dx: 0.42, dy: editRow), to: CGVector(dx: 0.50, dy: editRow))

        let editAtHalf = inkedColumns()
        if editAtHalf.isEmpty {
            XCTFail("A stroke drawn at the in-between has to appear on it. Either it was committed "
                    + "to the cel's own display list, which nothing renders, or the preview key did "
                    + "not notice the recipe changed. \(inkReport())")
        }

        // The claim the inverse map exists to earn: move the slider and the edit **follows the
        // motion**. The keyframes are 0.40 of
        // the canvas apart, so half that span is 0.20 — an edit that had been stored at the
        // in-between instead of in keyframe space would not move at all.
        slider.adjust(toNormalizedSliderPosition: 1)
        let editAtOne = inkedColumns()
        if editAtOne.isEmpty {
            XCTFail("The edit has τ = 0.5, so it must still be there at t = 1. \(inkReport())")
        }
        XCTAssertGreaterThan(meanColumn(editAtOne), meanColumn(editAtHalf) + 0.05,
                             "The edit must ride the drawing's motion rather than sit still — "
                             + "columns at t=0.5 \(editAtHalf) vs at t=1 \(editAtOne)")

        // --- Guide strokes ---
        //
        // Here for the same reason as the block above: everything below the gesture is covered by
        // `InterpolationGuideLogicTests`, and what is covered nowhere else is the view-layer routing —
        // that arming the toggle turns a canvas drag into a *guide* instead of ink, and that
        // `GuideOverlayView` claims a handle's hitbox and nothing else. A handle drag that fell
        // through to the stroke view would land as a local edit instead, which is exactly the failure
        // the assertions below distinguish from "nothing happened".
        //
        // **The trajectory is asserted and the easing is not**, deliberately. A guide's timing comes
        // from `UITouch.timestamp` and a synthetic drag can hand every sample the same one, which
        // `GuidePath.spacingCurve` answers with `.linear` on purpose. The arc is geometry and survives
        // synthetic input; the velocity may not.
        slider.adjust(toNormalizedSliderPosition: 0.5)

        // Columns carrying ink at the drawing's own row, rather than one point: XCUITest's synthetic
        // drags undershoot by a timing-dependent amount (`performDrag`'s own comment), so the guide's
        // pull is asserted as a direction and a magnitude floor, never as an exact landing place.
        //
        // The sweep stops at 0.26 on the left, which is what keeps the dashed guide overlay — drawn
        // at 0.20 and pulled to 0.08 — out of every reading. A teal dash is not whitish, so a guide
        // crossing the sweep would read as ink.
        func guideColumns() -> [Double] {
            stride(from: 0.26, through: 0.74, by: 0.02).filter {
                !isWhitish(rgbaPixel(of: canvas, dx: $0, dy: probe.dy))
            }
        }
        func guideReport() -> String {
            let sweep = stride(from: 0.04, through: 0.80, by: 0.02).map { x in
                String(format: "%.2f:%@", x, isWhitish(rgbaPixel(of: canvas, dx: x, dy: probe.dy)) ? "." : "#")
            }.joined(separator: " ")
            return "columns at dy=\(probe.dy): \(sweep) | guide toggle "
                + "\(app.buttons["interpolate.guide"].label)"
        }

        let columnsBeforeGuide = guideColumns()
        XCTAssertFalse(columnsBeforeGuide.isEmpty,
                       "Setup: back at t = 0.5 there is ink to move. \(guideReport())")

        // A **vertical** guide down the left, spanning only rows this test has already put ink on —
        // 0.42 and 0.60 both demonstrably reach the stroke view, so 0.36…0.64 is known-live canvas.
        // Its distance from the drawing is not a shortcut but the behaviour §5.16 predicts: only the
        // guide's *shape* is read, so an arc drawn clear of the character moves it exactly as one
        // drawn over it.
        let guideColumn = 0.20
        let guideToggle = app.buttons["interpolate.guide"]
        XCTAssertTrue(guideToggle.waitForExistence(timeout: 5), "interpolate.guide exists")
        guideToggle.tap()
        // Asserted here rather than left to surface as "no guide was recorded" two steps later: the
        // toggle is what decides whether the next drag is a guide or ink, and the two failures want
        // completely different investigations.
        XCTAssertTrue(guideToggle.label.hasPrefix("Drawing Guide"),
                      "Tapping Guide has to arm guide drawing — the label is the armed state. "
                      + "label=\(guideToggle.label) hittable=\(guideToggle.isHittable) "
                      + "frame=\(guideToggle.frame) enabled=\(guideToggle.isEnabled) "
                      + "refusal=\(app.staticTexts["interpolate.refusal"].exists ? app.staticTexts["interpolate.refusal"].label : "none")")
        dragOnCanvas(app, from: CGVector(dx: guideColumn, dy: 0.36),
                     to: CGVector(dx: guideColumn, dy: 0.64))

        // Item 7's list reporting what the frame ended up with — and here it doubles as proof that
        // the drag was captured as a guide rather than laid down as ink, which is the one thing a
        // pixel probe well clear of the drawing could not tell apart from a stray stroke.
        let guideChip = app.descendants(matching: .any)["interpolate.guideChip.1"]
        XCTAssertTrue(guideChip.waitForExistence(timeout: 5),
                      "Drawing with Guide armed should record a guide and list it on the bar. "
                      + "\(guideReport())")

        // Disarm. The toggle's promise is that every canvas drag draws a guide, so the handles are
        // deliberately neither live nor drawn while it is lit — disarming is what says "done drawing".
        guideToggle.tap()

        // The baseline for everything below is taken **with the guide already on**, not before it,
        // and the difference is real rather than pedantic: a guide's role is `.both`, so merely
        // drawing one hands the frame the stylus velocity as its easing (item 4), and at t = 0.5 an
        // eased motion does not sit where a linear one did. Comparing the handle drag against the
        // no-guide state charges it for that shift as well, which cost a run to find out.
        let columnsWithGuide = guideColumns()
        XCTAssertFalse(columnsWithGuide.isEmpty,
                       "Drawing a guide must not blank the in-between. \(guideReport())")

        // Drag the guide's **start** handle, which is the one position in this test that is known
        // exactly: it is where the guide-drawing press began, and a synthetic drag's *start* is
        // reliable where its end is not (`performDrag`'s undershoot note). Aiming at the middle
        // handle was the first attempt and it missed — the guide-drawing drag had undershot, so the
        // arc midpoint was some way above 0.50 and outside the handle's hitbox.
        //
        // Pulling the start **left** moves the drawing **right**, and that is the chord-relative
        // constraint (§5.16) showing its working: the path's middle does not move, but the chord it
        // is measured against now tilts, so the deviation at the midpoint is about half the pull in
        // the opposite direction. An absolute reading of the guide would have moved it left.
        dragOnCanvas(app, from: CGVector(dx: guideColumn, dy: 0.36),
                     to: CGVector(dx: 0.02, dy: 0.36))

        // **What is asserted is that the handle drag reached the frame, not which way it went.** The
        // direction is chord-relative geometry and is pinned at zero tolerance by
        // `InterpolationGuideLogicTests`; predicting it here would mean re-deriving, in a comment,
        // where a tilted chord puts the midpoint — and getting it wrong once already cost a run. What
        // no logic test can reach is the routing: that the overlay claimed the touch instead of the
        // stroke view underneath, which is exactly the bug this found (`bringSubviewToFront`).
        let columnsAfterGuide = guideColumns()
        XCTAssertNotEqual(columnsAfterGuide, columnsWithGuide,
                          "Dragging a guide handle has to move the in-between. Unchanged means the "
                          + "touch fell through to the stroke view instead of being claimed by the "
                          + "overlay's handle hitbox. \(guideReport())")

        // One undo puts the whole drag back, **exactly** — which is the strong half of this: it says
        // the gesture was one step and that the frame came back intact rather than merely moving
        // again. The guide itself stays, because the step is the drag and not the guide.
        let undo = app.buttons["sideToolbar.undoButton"]
        XCTAssertTrue(undo.waitForExistence(timeout: 5), "sideToolbar.undoButton exists")
        undo.tap()
        XCTAssertTrue(guideChip.waitForExistence(timeout: 5),
                      "Undoing the handle drag must not delete the guide")
        XCTAssertEqual(guideColumns(), columnsWithGuide,
                       "One undo should put the whole handle drag back — and only it, leaving the "
                       + "guide and its timing in place. \(guideReport())")

        // --- Commit ---
        //
        // Here for the seam no logic test can reach, and it is a real one. Until now every pixel on
        // screen came from `setInterpolationImage` — the evaluated bitmap the coordinator pushes.
        // Committing drops the recipe, so `updateInterpolationPreviews` takes its no-recipe branch and
        // clears that image to nil; from the next pass on, the same drawing has to be coming out of
        // the cel's **own** display list instead. If the bake wrote anywhere else, the frame goes
        // blank here and nowhere earlier.
        let commit = app.buttons["interpolate.commit"]
        XCTAssertTrue(commit.waitForExistence(timeout: 5), "interpolate.commit exists")
        commit.tap()

        // The one wait in this file that is not 5 seconds, and the asymmetry is deliberate. Every
        // other one here guards a cheap transition — a panel presenting, a button appearing. This one
        // guards the view catching up with a **synchronous ARAP solve**: the tap runs `evaluate` on
        // the main actor for every motion group before the recipe is dropped, and only then does
        // SwiftUI re-run and the accessibility tree lose the slider. Sizing it like the cheap waits
        // was wrong when it was written, not merely unlucky.
        XCTAssertTrue(slider.waitForNonExistence(timeout: 20),
                      "The timing row is gated on there being a recipe, so it must go with it.")
        let afterCommit = inkedColumns()
        if afterCommit.isEmpty {
            XCTFail("After Commit the frame has to keep its ink, now from the cel's own display "
                    + "list rather than from the evaluated preview. \(inkReport())")
        }
    }

}
