// Generated by a mechanical split of the original monolithic PaintSoftwareUITests
// class. Test bodies are unchanged; see PaintUITestCase for the shared helpers.

import XCTest

final class TimelineAndUndoUITests: PaintUITestCase {

    func testCreateCanvasReachesEditorWithoutFreezing() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app), "Editor should load promptly after tapping Create Canvas")
    }

    func testTappingCelBlockMovesPlayheadToTappedFrame() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let cel = app.otherElements["timeline.cel.0.0"]
        XCTAssertTrue(cel.waitForExistence(timeout: 5))

        // Default scene is 12 frames, one cel spanning all of them. Tap at the block's
        // midpoint (safely inside the middle strip, clear of the edge-resize handles) and
        // expect the playhead to land on the frame under that exact point, not some
        // offset/incorrect frame.
        let target = cel.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.5))
        target.tap()

        guard let (current, total) = readFrameLabel(app) else {
            XCTFail("Could not read frame label")
            return
        }
        XCTAssertEqual(total, 12)
        XCTAssertEqual(current, 7, "Tapping the block's midpoint should move the playhead to frame 7 (index 6 of 12), not \(current)")
    }

    func testDraggingRightEdgeHandleShrinksCel() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        guard let before = readCel(app, layerIndex: 0, celIndex: 0) else {
            XCTFail("Could not read initial cel state")
            return
        }
        XCTAssertEqual(before.start, 0)
        XCTAssertEqual(before.length, 12)

        let rightHandle = app.otherElements["timeline.cel.0.0.rightHandle"]
        XCTAssertTrue(rightHandle.waitForExistence(timeout: 5))

        // Drag the right edge well to the left (requesting more than the minimum needed, since
        // XCUITest's synthetic drags can undershoot their requested distance) which should
        // shrink the block from 12 frames without moving its start.
        performDrag(app, identifier: "timeline.cel.0.0.rightHandle", totalDelta: -150)

        guard let after = readCel(app, layerIndex: 0, celIndex: 0) else {
            XCTFail("Could not read cel state after drag")
            return
        }
        XCTAssertEqual(after.start, 0, "Dragging the right edge should not move the start frame")
        XCTAssertLessThan(after.length, before.length, "Dragging the right edge left should shrink the cel, but length stayed at \(after.length)")
    }

    /// Diagnostic: isolates whether XCUITest synthetic drags deliver sustained intermediate
    /// movement at all in this simulator/OS, independent of the edge-handle's nested geometry.
    /// The ruler's own scrub gesture (DragGesture(minimumDistance: 0) reading value.location)
    /// is the simplest possible drag target in this view.
    func testDraggingAcrossRulerMovesPlayheadProgressively() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let ruler = app.otherElements["timeline.ruler"]
        XCTAssertTrue(ruler.waitForExistence(timeout: 5))

        // Start near the ruler's left edge and drag right by ~150pt (5 frames at 30pt/frame).
        let start = ruler.coordinate(withNormalizedOffset: CGVector(dx: 0.02, dy: 0.5))
        let end = start.withOffset(CGVector(dx: 150, dy: 0))
        start.press(forDuration: 0.2, thenDragTo: end, withVelocity: .slow, thenHoldForDuration: 0.2)

        guard let (current, _) = readFrameLabel(app) else {
            XCTFail("Could not read frame label")
            return
        }
        XCTAssertGreaterThan(current, 1, "Dragging across the ruler by 150pt should have moved the playhead well past frame 1, but landed on \(current)")
    }

    func testDraggingLeftEdgeHandleShrinksCelWithoutMovingEnd() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let leftHandle = app.otherElements["timeline.cel.0.0.leftHandle"]
        XCTAssertTrue(leftHandle.waitForExistence(timeout: 5))

        // Drag the left edge well to the right, which should move startFrame forward from 0
        // while keeping the end frame fixed at 12.
        performDrag(app, identifier: "timeline.cel.0.0.leftHandle", totalDelta: 150)

        guard let after = readCel(app, layerIndex: 0, celIndex: 0) else {
            XCTFail("Could not read cel state after drag")
            return
        }
        XCTAssertGreaterThan(after.start, 0, "Dragging the left edge right should move the start frame forward, but it stayed at 0")
        XCTAssertEqual(after.start + after.length, 12, "The end frame should stay fixed at 12 while only the start moves, but start+length was \(after.start + after.length)")
    }

    /// The timeline's name column reorders too: press and hold a name, then drag it.
    func testTimelineNameColumnReordersOnPressAndHold() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)
        let addLayer = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addLayer.waitForExistence(timeout: 5)) // the panel has to finish presenting first
        addLayer.tap() // layers: [Layer 1, Layer 2]
        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForExistence(timeout: 5))
        app.buttons["toolbar.layersButton"].tap() // close the panel so it can't cover the timeline

        let topName = app.staticTexts["timeline.layerName.1"]
        XCTAssertTrue(topName.waitForExistence(timeout: 5))
        XCTAssertEqual(topName.label, "Layer 2")

        // One row down is rowHeight (34) + the 2pt gap between rows.
        let start = topName.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.5))
        start.press(forDuration: 0.9, thenDragTo: start.withOffset(CGVector(dx: 0, dy: 40)),
                    withVelocity: .slow, thenHoldForDuration: 0.5)

        XCTAssertEqual(app.staticTexts["timeline.layerName.0"].label, "Layer 2",
                       "Dragging a timeline name down should restack that layer")
    }

    /// The core regression this feature addresses: undo used to be scoped to whichever layer's
    /// private UndoManager was "active," and switching the active layer cleared that layer's
    /// history. With a single global stack, undo must keep walking back through every action in
    /// the order it happened, even after the active layer has changed since.
    func testUndoWalksBackAcrossLayersRegardlessOfActiveLayer() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))
        layersButton.tap()

        layersButton.tap() // close so drawing isn't blocked by the panel
        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        var start = canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.3, dy: 0.3))
        var end = start.withOffset(CGVector(dx: 80, dy: 0))
        start.press(forDuration: 0.1, thenDragTo: end) // stroke on layer 0

        layersButton.tap() // reopen
        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap() // layer 1 added and made active

        layersButton.tap() // close to draw again
        start = canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.6, dy: 0.6))
        end = start.withOffset(CGVector(dx: 80, dy: 0))
        start.press(forDuration: 0.1, thenDragTo: end) // stroke on layer 1 (now active)

        layersButton.tap() // reopen to verify + switch active layer back
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 0), 1, "Layer 0 should have its own stroke")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 1), 1, "Layer 1 should have its own stroke")

        // Switch the active layer back to layer 0 — under the old per-layer design this would
        // have repointed (and cleared) whatever stack "undo" operates on.
        let bottomRow = app.staticTexts["layerPanel.row.0"]
        XCTAssertTrue(bottomRow.waitForExistence(timeout: 5))
        bottomRow.tap()
        XCTAssertTrue(app.images["layerPanel.row.0.current"].waitForExistence(timeout: 5), "Layer 0 should now be active")

        // Three actions sit on the global stack in this order: stroke on layer 0, adding layer 1
        // (itself now undoable — a "layer change" this overhaul covers), stroke on layer 1.
        let undo = app.buttons["sideToolbar.undoButton"]
        XCTAssertTrue(undo.waitForExistence(timeout: 5))
        XCTAssertTrue(undo.isEnabled)
        undo.tap()

        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 1), 0,
                       "The first undo (with layer 0 active) should still undo the most recent action — layer 1's stroke — not silently no-op or hit layer 0's history")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 0), 1,
                       "Layer 0's stroke should be untouched by the first undo")

        undo.tap()
        XCTAssertFalse(app.staticTexts["layerPanel.row.1"].exists,
                       "The second undo should reach back to adding layer 1 and remove it entirely")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 0), 1,
                       "Layer 0's stroke should still be untouched by the second undo")

        undo.tap()
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 0), 0,
                       "The third undo should reach back further still and undo layer 0's stroke")
    }

    /// Deleting a layer must be undoable, restoring both its existence and its content — the
    /// operation had no undo registration at all before this feature.
    func testDeletingLayerIsUndoableAndRestoresContent() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))
        layersButton.tap()

        layersButton.tap() // close to draw
        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let start = canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.3, dy: 0.3))
        let end = start.withOffset(CGVector(dx: 80, dy: 0))
        start.press(forDuration: 0.1, thenDragTo: end) // stroke on layer 0

        layersButton.tap() // reopen
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 0), 1)

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap() // layer 1 added, becomes active; layer 0 keeps its stroke

        swipeDeleteLayerRow(app, layerIndex: 0)
        XCTAssertTrue(app.staticTexts["layerPanel.row.0"].waitForExistence(timeout: 5))
        XCTAssertFalse(app.staticTexts["layerPanel.row.1"].exists, "Only the surviving layer should remain")

        let undo = app.buttons["sideToolbar.undoButton"]
        XCTAssertTrue(undo.waitForExistence(timeout: 5))
        XCTAssertTrue(undo.isEnabled, "Deleting a layer should be undoable")
        undo.tap()

        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForExistence(timeout: 5), "Undo should restore the deleted layer")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 0), 1,
                       "The restored layer's stroke content should come back intact, not blank")
    }

    /// Drag-reordering layers must be undoable, restoring the original stacking order.
    func testReorderingLayersIsUndoable() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        openLayerPanel(app)

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5))
        addButton.tap()
        addButton.tap()
        // layers bottom-to-top: [Layer 1, Layer 2, Layer 3]; displayed top-to-bottom: 3, 2, 1.

        let bottomRow = app.staticTexts["layerPanel.row.0"]
        XCTAssertTrue(bottomRow.waitForExistence(timeout: 5))
        XCTAssertEqual(bottomRow.label, "Layer 1")

        dragRow(layerCell(app, layerIndex: 2), onto: layerCell(app, layerIndex: 0), dropDY: 0.95)
        XCTAssertEqual(app.staticTexts["layerPanel.row.0"].label, "Layer 3", "Sanity-check the drag actually landed")

        let undo = app.buttons["sideToolbar.undoButton"]
        XCTAssertTrue(undo.waitForExistence(timeout: 5))
        XCTAssertTrue(undo.isEnabled, "Reordering layers should be undoable")
        undo.tap()

        XCTAssertEqual(app.staticTexts["layerPanel.row.0"].label, "Layer 1", "Undo should restore the original bottom-to-top order")
        XCTAssertEqual(app.staticTexts["layerPanel.row.2"].label, "Layer 3", "Undo should restore the original top layer too")
    }

    /// A cel resize drag must register as ONE undo step for the whole gesture, not one per
    /// intermediate frame position it passes through — otherwise a single undo would only
    /// partially reverse the drag instead of fully restoring the cel's original bounds.
    func testCelResizeDragUndoesInOneStep() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        guard let before = readCel(app, layerIndex: 0, celIndex: 0) else {
            XCTFail("Could not read initial cel state")
            return
        }
        XCTAssertEqual(before.start, 0)
        XCTAssertEqual(before.length, 12)

        performDrag(app, identifier: "timeline.cel.0.0.rightHandle", totalDelta: -150)

        guard let afterDrag = readCel(app, layerIndex: 0, celIndex: 0) else {
            XCTFail("Could not read cel state after drag")
            return
        }
        XCTAssertLessThan(afterDrag.length, before.length, "Sanity-check the drag actually shrank the cel")

        let undo = app.buttons["sideToolbar.undoButton"]
        XCTAssertTrue(undo.waitForExistence(timeout: 5))
        XCTAssertTrue(undo.isEnabled, "The resize should be undoable")
        undo.tap()

        guard let afterUndo = readCel(app, layerIndex: 0, celIndex: 0) else {
            XCTFail("Could not read cel state after undo")
            return
        }
        XCTAssertEqual(afterUndo.start, before.start, "One undo should fully restore the cel's original start")
        XCTAssertEqual(afterUndo.length, before.length,
                       "One undo should fully restore the cel's original length in a single step, not just partially reverse one frame of the drag")
    }

    /// The one XCUITest for interpolation's gesture path — deliberately one, not a suite.
    ///
    /// XCUITests are 99.3% of this suite's runtime (REFACTOR_BASELINE.md), so everything about
    /// interpolation that can be asserted without a simulator gesture is in
    /// `InterpolationWorkflowLogicTests` instead. What is left here is exactly what a logic test
    /// cannot reach: that the mode's controls are wired up — that Set as Reference on the
    /// interpolate bar flags the block under the playhead, that Generate is reachable from that same
    /// bar, and that dragging the timing slider changes what is on the canvas.
    ///
    /// Structure: two keyframes on one vector layer, and the in-between generated on a *second*
    /// vector layer whose single cel spans the scene. That avoids splitting one layer into three
    /// blocks — the target only has to not be a reference, and it may live on any layer.
    func testInterpolateModeEndToEndFromGestureToScrub() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app), "reached editor")
        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5), "canvas.host exists")

        // Keyframe A: an L on the left of a new vector layer. An L rather than a straight line
        // because parallel strokes pin neither orientation nor position for the registration's ICP
        // (VECTOR_INTERPOLATION_HANDOFF.md §5) — a corner gives the fit something to hold onto.
        addVectorLayer(app)
        drawLine(on: canvas, from: CGVector(dx: 0.22, dy: 0.42), to: CGVector(dx: 0.34, dy: 0.42))
        drawLine(on: canvas, from: CGVector(dx: 0.34, dy: 0.42), to: CGVector(dx: 0.34, dy: 0.56))

        // Split the layer so there is a second block to be the other keyframe.
        performDrag(app, identifier: "timeline.cel.1.0.rightHandle", totalDelta: -260)
        let firstBlock = app.otherElements["timeline.cel.1.0"]
        let shrunk = try XCTUnwrap(readCel(app, layerIndex: 1, celIndex: 0),
                                   "Could not read the vector layer's block after shrinking it")
        XCTAssertLessThan(shrunk.length, 12, "Setup: the drag has to leave a gap to add a block into")

        // Tap two frames past the block's own right edge — an offset beyond the element's bounds,
        // which is the only handle a test has on an empty timeline slot.
        firstBlock.coordinate(withNormalizedOffset:
            CGVector(dx: (Double(shrunk.length) + 2.0) / Double(shrunk.length), dy: 0.5)).tap()
        let addDrawing = app.buttons["Add Drawing"]
        XCTAssertTrue(addDrawing.waitForExistence(timeout: 5), "Tapping an empty slot opens its menu")
        addDrawing.tap()

        // Keyframe C: the same L, moved right.
        drawLine(on: canvas, from: CGVector(dx: 0.62, dy: 0.42), to: CGVector(dx: 0.74, dy: 0.42))
        drawLine(on: canvas, from: CGVector(dx: 0.74, dy: 0.42), to: CGVector(dx: 0.74, dy: 0.56))

        // The cel the in-between lands on: a second vector layer, spanning the whole scene.
        addVectorLayer(app)

        // One tap on the timeline's own interpolate button *is* entering the mode — there is no
        // panel and no switch in the way. A second tap would open the options popover instead.
        let interpolateButton = app.buttons["timeline.interpolateButton"]
        XCTAssertTrue(interpolateButton.waitForExistence(timeout: 5), "timeline.interpolateButton exists")
        interpolateButton.tap()

        // The controls under test. Set as Reference acts on the block under the playhead, so each
        // reference is "tap the block to go there, then press the button" — and the bar is on screen
        // the whole time, which is the point of it living above the timeline rather than in a panel.
        let setReference = app.buttons["interpolate.setReference"]
        XCTAssertTrue(setReference.waitForExistence(timeout: 5),
                      "The interpolate bar appears above the timeline once the mode is on")
        XCTAssertFalse(readCelIsReference(app, layerIndex: 1, celIndex: 0),
                       "Setup: nothing is a reference yet")
        app.otherElements["timeline.cel.1.0"].tap()
        setReference.tap()
        app.otherElements["timeline.cel.1.1"].tap()
        setReference.tap()
        XCTAssertTrue(readCelIsReference(app, layerIndex: 1, celIndex: 0),
                      "Set as Reference should flag the block under the playhead")
        XCTAssertTrue(readCelIsReference(app, layerIndex: 1, celIndex: 1), "second block flagged as reference")

        // Make the second vector layer's block the target — a plain tap still means "go here".
        app.otherElements["timeline.cel.2.0"].tap()

        // Interpolate mode's onion skin draws *both* references, so leaving it on would put ink at
        // each keyframe's position and make a pixel probe unable to tell the in-between from the
        // skin. The skin has its own logic test; this one is about the in-between.
        let onionSkin = app.buttons["timeline.onionSkinToggle"]
        XCTAssertTrue(onionSkin.waitForExistence(timeout: 5), "timeline.onionSkinToggle exists")
        onionSkin.tap()

        let probe = (dx: 0.48, dy: 0.42)
        XCTAssertTrue(isWhitish(rgbaPixel(of: canvas, dx: probe.dx, dy: probe.dy)),
                      "Setup: the middle of the canvas is blank before the in-between exists")

        let generate = app.buttons["interpolate.generate"]
        XCTAssertTrue(generate.waitForExistence(timeout: 5), "interpolate.generate exists")
        XCTAssertTrue(generate.isEnabled, "Two references and an empty target cel — Generate should be live")
        generate.tap()

        // Built only on failure — it costs ~20 element screenshots, and "no ink at one point" is
        // almost impossible to diagnose from a bare assertion. Where the ink actually landed, and what
        // the timeline looked like when it did, is the whole diagnosis: ink at the keyframes but not
        // between them means the warp is identity, and a block reading `nil` means the setup drifted.
        func inkReport() -> String {
            let sweep = stride(from: 0.14, through: 0.86, by: 0.04).map { x in
                String(format: "%.2f:%@", x, isWhitish(rgbaPixel(of: canvas, dx: x, dy: probe.dy)) ? "." : "#")
            }.joined(separator: " ")
            let blocks = [(1, 0), (1, 1), (2, 0)].map { l, c -> String in
                let cel = readCel(app, layerIndex: l, celIndex: c)
                let ref = readCelIsReference(app, layerIndex: l, celIndex: c) ? "*" : ""
                return "\(l).\(c)=\(cel.map { "\($0.start)+\($0.length)" } ?? "nil")\(ref)"
            }.joined(separator: " ")
            return "sweep at dy=\(probe.dy): \(sweep) | blocks \(blocks) "
                + "| frame \(readFrameLabel(app).map { "\($0.current)/\($0.total)" } ?? "?")"
        }

        if isWhitish(rgbaPixel(of: canvas, dx: probe.dx, dy: probe.dy)) {
            XCTFail("At t = 0.5 the in-between should have ink about halfway between the keyframes. \(inkReport())")
        }

        // Scrub to t = 0, where the frame *is* keyframe A — so the midpoint goes back to blank.
        let slider = app.sliders["interpolate.tSlider"]
        XCTAssertTrue(slider.waitForExistence(timeout: 5), "interpolate.tSlider exists")
        slider.adjust(toNormalizedSliderPosition: 0)

        if !isWhitish(rgbaPixel(of: canvas, dx: probe.dx, dy: probe.dy)) {
            XCTFail("Dragging the slider to 0 should move the drawing back onto keyframe A. \(inkReport())")
        }

        // --- Phase 6 items 2 and 3: editing *at* the in-between ---
        //
        // This half is here rather than in a logic test for one reason: everything below the gesture
        // is already covered by `InterpolationWorkflowLogicTests`, and what is not covered anywhere
        // else is `StrokeCanvasView`'s routing — that a touch on an interpolated cel becomes a
        // `LocalEdit` instead of ink in a display list nothing renders, and that the memoized preview
        // notices. Phase 4's `addCel` bug is the precedent: it was invisible until a gesture ran
        // through the real path (`HANDOFF.md` §5).
        slider.adjust(toNormalizedSliderPosition: 0.5)

        // A row just below the L, clear of every keyframe's ink at every `t`, so anything found on it
        // can only be the edit. It is also outside the lattice, which puts the expansion path
        // (`PLAN.md` §5.4 step 2) under the same test rather than needing its own.
        let editRow = 0.60
        func inkedColumns() -> [Double] {
            stride(from: 0.14, through: 0.92, by: 0.02).filter {
                !isWhitish(rgbaPixel(of: canvas, dx: $0, dy: editRow))
            }
        }
        func meanColumn(_ columns: [Double]) -> Double {
            columns.reduce(0, +) / Double(max(1, columns.count))
        }
        XCTAssertTrue(inkedColumns().isEmpty,
                      "Setup: the row the edit is drawn on has to start blank")

        drawLine(on: canvas, from: CGVector(dx: 0.42, dy: editRow), to: CGVector(dx: 0.50, dy: editRow))

        let editAtHalf = inkedColumns()
        if editAtHalf.isEmpty {
            XCTFail("A stroke drawn at the in-between has to appear on it. Either it was committed "
                    + "to the cel's own display list, which nothing renders, or the preview key did "
                    + "not notice the recipe changed. \(inkReport())")
        }

        // The claim the inverse map exists to earn, and the test `IMPLEMENTATION.md` Phase 6 asks
        // for by hand: move the slider and the edit **follows the motion**. The keyframes are 0.40 of
        // the canvas apart, so half that span is 0.20 — an edit that had been stored at the
        // in-between instead of in keyframe space would not move at all.
        slider.adjust(toNormalizedSliderPosition: 1)
        let editAtOne = inkedColumns()
        if editAtOne.isEmpty {
            XCTFail("The edit has τ = 0.5, so it must still be there at t = 1. \(inkReport())")
        }
        XCTAssertGreaterThan(meanColumn(editAtOne), meanColumn(editAtHalf) + 0.05,
                             "The edit must ride the drawing's motion rather than sit still — "
                             + "columns at t=0.5 \(editAtHalf) vs at t=1 \(editAtOne)")
    }

}
