// Generated by a mechanical split of the original monolithic PaintSoftwareUITests
// class. Test bodies are unchanged; see PaintUITestCase for the shared helpers.
//
// Originally a single ToolsAndSelectionUITests class (424s measured); split into three
// classes below so xcodebuild's per-class parallel distribution doesn't serialize all 14
// tests behind one worker. No shared helpers/setUp/tearDown to move — every test here only
// ever used PaintUITestCase's base-class helpers.

import XCTest

final class ToolPanelsUITests: PaintUITestCase {

    /// The second half of the owner's 2026-08-27 ask — *"Same for the add text menu, make it the same
    /// type of menu"* — as behaviour rather than as a layout constant.
    ///
    /// **What this pins and what it deliberately does not.** It pins the end of the screen the panel
    /// is at, which is the whole of the request, and the fact that Add Text still reaches it. It does
    /// not pin the card's size: 560×360 is a judgement about how much artwork a bar may cover, and a
    /// test that failed when that judgement was revised would be a test defending an arbitrary number.
    ///
    /// The probe is `textPanel.fontButton`, not the panel's own `panel.textSettings`: that identifier
    /// sits on a plain SwiftUI container, which UIKit does not surface as an element of any queryable
    /// type — the sibling test in `SelectionAndMoveUITests` records the same finding at its own probe.
    func testAddTextSettingsOpenAsABottomBar() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        app.buttons["toolbar.actionsButton"].tap()
        let addText = app.buttons["actions.addTextRow"]
        XCTAssertTrue(addText.waitForExistence(timeout: 5))
        addText.tap()

        let fontButton = app.buttons["textPanel.fontButton"]
        XCTAssertTrue(fontButton.waitForExistence(timeout: 5), "Add Text opens the text settings panel")

        let window = app.windows.element(boundBy: 0).frame
        XCTAssertGreaterThan(fontButton.frame.minY, window.midY, """
            The text settings are still a dropdown under the top toolbar. The owner asked for the \
            same bottom-docked bar the lasso and Move tools raise — see DrawingView.bottomDock.
            """)
    }

    /// Task 3: the fill tool's settings menu only opens on the *second* tap of its icon; the first tap
    /// just selects the tool (so switching tools never pops a menu over the canvas).
    func testFillMenuOpensOnlyOnSecondTap() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let fillButton = app.buttons["toolbar.fillButton"]
        XCTAssertTrue(fillButton.waitForExistence(timeout: 5))

        fillButton.tap() // First tap: select only.
        let menuSlider = app.sliders["fillPanel.gapClosingSlider"] // lives only in the dropdown menu
        XCTAssertFalse(menuSlider.waitForExistence(timeout: 1.5), "First tap should select the fill tool without opening its menu")

        fillButton.tap() // Second tap: open the menu.
        XCTAssertTrue(menuSlider.waitForExistence(timeout: 5), "Second tap on the already-selected fill tool should open its menu")
    }

    /// Task 3: tapping the canvas (anywhere off the toolbar and the open menu) dismisses an open menu.
    func testTappingCanvasDismissesOpenMenu() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))
        layersButton.tap()

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5), "Layers menu should open")

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.35, dy: 0.6)).tap() // off the menu

        XCTAssertTrue(addButton.waitForNonExistence(timeout: 3), "Tapping off an open menu should dismiss it")
    }

    /// Task 3: the left rail's sliders are Size / Opacity for the brush and swap to Gap Closing /
    /// Threshold / Edge Overlap when the fill tool is active.
    func testLeftRailSlidersSwapWithTool() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        // Default tool is the brush.
        XCTAssertTrue(app.sliders["sideToolbar.brushSizeSlider"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.staticTexts["Size"].exists)
        XCTAssertTrue(app.staticTexts["Opacity"].exists)
        XCTAssertFalse(app.sliders["sideToolbar.gapClosingSlider"].exists)

        app.buttons["toolbar.fillButton"].tap() // select fill

        XCTAssertTrue(app.sliders["sideToolbar.gapClosingSlider"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.sliders["sideToolbar.thresholdSlider"].exists)
        XCTAssertTrue(app.sliders["sideToolbar.edgeOverlapSlider"].exists)
        XCTAssertTrue(app.staticTexts["Gap Closing"].exists)
        XCTAssertTrue(app.staticTexts["Threshold"].exists)
        XCTAssertTrue(app.staticTexts["Edge Overlap"].exists)
        XCTAssertFalse(app.sliders["sideToolbar.brushSizeSlider"].exists)
    }

    /// Task: opening a tool's settings dropdown must not block drawing — continuing to draw should
    /// both dismiss the menu and land the stroke in one motion, instead of the first touch being
    /// silently swallowed and requiring a separate tap to close the menu first.
    func testDrawingWhileBrushMenuOpenDismissesMenuAndDraws() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        // Brush is the default tool, so a single tap opens its brushes menu directly. The probe is
        // the menu's own two columns; the sliders it used to carry are behind the editor now
        // (BRUSH.md §2.20), and this test is about the menu, not about them.
        let brushButton = app.buttons["toolbar.brushButton"]
        XCTAssertTrue(brushButton.waitForExistence(timeout: 5))
        brushButton.tap()
        let library = app.otherElements["brushPanel.library"]
        XCTAssertTrue(library.waitForExistence(timeout: 5), "Brush menu should be open")

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let p = safeOutsideCornerPoint(canvas)
        drawLine(on: canvas, from: p, to: CGVector(dx: p.dx + 0.12, dy: p.dy))

        XCTAssertTrue(library.waitForNonExistence(timeout: 3), "Continuing to draw should dismiss the open brush menu")
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: p.dx + 0.06, dy: p.dy)), "The stroke should have actually been drawn, not swallowed by the menu")
    }

    /// Task: brush/eraser/fill/select highlighting must be mutually exclusive — switching to Select
    /// must turn off whichever paint tool's icon was previously highlighted, not show both at once.
    func testSelectingSelectToolStopsHighlightingBrush() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let brushButton = app.buttons["toolbar.brushButton"]
        let selectButton = app.buttons["toolbar.selectButton"]
        XCTAssertTrue(brushButton.waitForExistence(timeout: 5))
        XCTAssertTrue(selectButton.waitForExistence(timeout: 5))

        // Brush is the default tool.
        XCTAssertTrue(brushButton.isSelected, "Brush should read as the active tool by default")
        XCTAssertFalse(selectButton.isSelected)

        selectButton.tap()
        XCTAssertTrue(selectButton.isSelected, "Select should now read as active")
        XCTAssertFalse(brushButton.isSelected, "Brush must stop reading as active once Select is engaged — only one tool highlighted at a time")

        // Switching back to Brush should restore exclusivity the other way. Nothing was ever
        // selected here, so the lasso icon has nothing to stay lit *for* — the near-miss twin where
        // a selection is live is `testSelectIconStaysLitWhileAnotherToolIsCurrent` below, and the
        // two together are what pin "blue means a lasso is on" rather than "blue means the panel is
        // open".
        brushButton.tap()
        XCTAssertTrue(brushButton.isSelected)
        XCTAssertFalse(selectButton.isSelected)
    }

    /// The owner's ask of 2026-08-21: "when you click the lasso icon, lasso, then pick eraser or
    /// brush or fill, the lasso icon should still stay blue. Blue means the lasso is currently on."
    ///
    /// `SelectionPersistenceLogicTests` pins the predicate (`CanvasManager.selectIconIsActive`) and
    /// pins that no paint tool clears `selection`, but it cannot see the toolbar: `TopToolbar.swift`
    /// is a `View` file and is not compiled into the logic-test target, so nothing headless can
    /// catch the icon being wired back to `activePanel == .select`. That is this test's whole job.
    func testSelectIconStaysLitWhileAnotherToolIsCurrent() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let selectButton = app.buttons["toolbar.selectButton"]
        XCTAssertTrue(selectButton.waitForExistence(timeout: 5))
        XCTAssertFalse(selectButton.isSelected, "Control: nothing is selected yet, so the icon must start unlit")

        selectButton.tap()
        let rectangleMode = app.buttons["selectPanel.mode.rectangle"]
        XCTAssertTrue(rectangleMode.waitForExistence(timeout: 5))
        rectangleMode.tap()
        // Upper portion of the canvas, clear of the Select menu's bottom-docked bar — same reason as
        // the selection tests in `SelectionAndMoveUITests`.
        dragOnCanvas(app, from: CGVector(dx: 0.3, dy: 0.2), to: CGVector(dx: 0.55, dy: 0.35))

        for identifier in ["toolbar.brushButton", "toolbar.eraserButton", "toolbar.fillButton"] {
            let tool = app.buttons[identifier]
            tool.tap()
            XCTAssertTrue(tool.isSelected, "Premise: \(identifier) must actually have become the current tool")
            XCTAssertTrue(selectButton.isSelected,
                          "The selection is still live while \(identifier) paints into it, so the lasso icon must stay blue")
        }

        // …and it is reporting the selection rather than stuck on: deselect, leave the panel, and the
        // highlight drops. (Deselect leaves the Select panel open, which lights the icon on its own —
        // hence tapping Brush before reading it.)
        selectButton.tap()
        let deselect = app.buttons["selectPanel.deselectButton"]
        XCTAssertTrue(deselect.waitForExistence(timeout: 5))
        deselect.tap()
        app.buttons["toolbar.brushButton"].tap()
        XCTAssertFalse(selectButton.isSelected, "With the selection gone the icon must go back to unlit")
    }

    /// The owner's ask is specifically that the real-size stamp preview appears when the size slider
    /// is **pressed**, before any drag — and that is the one half of it no logic test can reach.
    ///
    /// It cannot be observed directly either: the window is on screen only while a finger is down,
    /// and XCUITest cannot query the tree in the middle of its own gesture. So the fact is made to
    /// outlive the lift — `CanvasManager.sizePreviewRaiseCount`, surfaced by `DrawingView` as
    /// `sizePreview.raiseCount`, exactly as `midStrokeEntryCount` is surfaced for the sandwich.
    func testPressingTheBrushSizeSliderRaisesTheRealSizeStampPreview() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let raiseCount = app.staticTexts["sizePreview.raiseCount"]
        XCTAssertTrue(raiseCount.waitForExistence(timeout: 5), "The preview's observability marker must exist")
        XCTAssertEqual(raiseCount.label, "0", "PREMISE: nothing has been held yet")
        XCTAssertFalse(app.otherElements["sizePreview.window"].exists,
                       "PREMISE: and no preview is on screen at rest")

        // The Size slider moved into the brush editor with every other brush parameter (BRUSH.md
        // §2.20), so reaching it is now the menu's second tap. The preview window it raises is drawn
        // by `DrawingView`'s overlay against the slider's own frame, which is why the editor is a
        // push inside the panel rather than a sheet over it — see `StrokeSettingsPanel`.
        openBrushEditor(app)
        let sizeSlider = app.sliders["brushPanel.sizeSlider"]
        XCTAssertTrue(sizeSlider.waitForExistence(timeout: 5), "Brush editor should be open")

        // Park the thumb under the middle of the track, so the press below lands on the thumb
        // rather than on bare track — which a slider ignores, and which would make this test pass
        // or fail on where the default brush size happens to put the thumb.
        sizeSlider.adjust(toNormalizedSliderPosition: 0.5)
        let afterDrag = Int(raiseCount.label) ?? 0
        XCTAssertGreaterThanOrEqual(afterDrag, 1, "Dragging the slider must have raised the preview")

        // The ask itself: a press that never moves.
        sizeSlider.press(forDuration: 0.6)
        XCTAssertEqual(Int(raiseCount.label) ?? -1, afterDrag + 1,
                       "Touch-down with no drag at all must raise the preview exactly once more")
        XCTAssertFalse(app.otherElements["sizePreview.window"].exists,
                       "…and the lift must take it away again rather than stranding it on screen")
    }

    /// TODO item (9), CANVAS_RESIZE.md stage 1: **"Resize Canvas" exists in the Actions menu and
    /// applies.** The only genuinely UI-shaped part of that stage — the map, the per-tier walk and the
    /// two fixes are all pinned headlessly in `CanvasResizeLogicTests`, which is the tier to add to.
    ///
    /// What is only reachable from here: that the row is in the menu at all, that a `.sheet` raised
    /// from inside a `DrawingView` dropdown panel actually presents (the panel is swapped in and out
    /// by `activePanel`, so a sheet anchored to it is not obviously safe), and that the artist's typed
    /// number reaches the document.
    ///
    /// **The row's own title is the probe, and that is deliberate rather than convenient.** The canvas
    /// extent is not published on `canvas.host`'s label like the transform is, so there is no other
    /// way to read it from a UI test — and the title showing the live artwork size is a feature in its
    /// own right (the menu answers "how big is this canvas" without opening anything), so a test that
    /// reads it is testing something the artist relies on rather than a back door.
    func testResizeCanvasIsInTheActionsMenuAndAppliesTheTypedSize() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        app.buttons["toolbar.actionsButton"].tap()
        let row = app.buttons["actions.resizeCanvasRow"]
        XCTAssertTrue(row.waitForExistence(timeout: 5), "Resize Canvas is a row in the Actions menu")
        XCTAssertTrue(row.label.contains("2048"),
                      "PREMISE: the row shows the live artwork size, which is the default 2048 here "
                      + "(label: \(row.label))")
        row.tap()

        let widthField = app.textFields["resizeCanvas.widthField"]
        XCTAssertTrue(widthField.waitForExistence(timeout: 5),
                      "the row opens the resize sheet — a sheet raised from inside the Actions panel presents")
        let heightField = app.textFields["resizeCanvas.heightField"]
        XCTAssertTrue(heightField.exists)
        XCTAssertEqual(widthField.value as? String, "2048", "the fields are prefilled with the current artwork rect")

        // Cleared with `delete` presses rather than a select-all: the fields raise a number pad, which
        // has no selection affordances at all.
        let clear = String(repeating: XCUIKeyboardKey.delete.rawValue, count: 6)
        widthField.tap()
        widthField.typeText(clear + "800")
        heightField.tap()
        heightField.typeText(clear + "600")

        app.buttons["resizeCanvas.applyButton"].tap()
        XCTAssertFalse(widthField.waitForExistence(timeout: 3), "applying dismisses the sheet")

        XCTAssertTrue(row.waitForExistence(timeout: 5), "the Actions menu is still open underneath")
        XCTAssertTrue(row.label.contains("800") && row.label.contains("600"), """
            The typed size never reached the document — the row still reads \(row.label). The two \
            fields are the *artwork* rect (CANVAS_RESIZE.md §5 rule 9), which with no canvas padding \
            is also the buffer.
            """)
    }

    /// **Export, end to end in the running app** — RENDER.md §3.9, and the half no logic test can
    /// reach.
    ///
    /// `FrameExportSessionLogicTests` owns the driver: the walk, the focus hand-back, the phases,
    /// every failure. What is only true here is that the artist can *get* to it — that the row is in
    /// the Actions menu, that a sheet raised from inside that panel presents at all, that the
    /// running view is drawn while the wait happens, and that the wait ends somewhere the file can
    /// be picked up from. A session driven straight from a test would agree happily with a row
    /// nobody can tap and a `ShareLink` that never appears.
    ///
    /// **In an existing class on purpose**: `xcodebuild` distributes parallel work per test *class*,
    /// so a new class lengthens the suite's critical path and pays its own setup. This one is the
    /// resize test's twin — a row in the Actions menu that opens a sheet — so it belongs beside it.
    ///
    /// The progress view is polled tightly rather than asserted on the next line: §2.13's ruling
    /// that a moment of staleness is acceptable applies to every wait in this feature, and how long
    /// a fresh document's single frame takes to bake and encode is a property of the machine.
    func testExportIsInTheActionsMenuAndRunsThroughToAShareableFile() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        app.buttons["toolbar.actionsButton"].tap()
        let row = app.buttons["actions.exportRow"]
        XCTAssertTrue(row.waitForExistence(timeout: 5), "Export is a row in the Actions menu")
        XCTAssertTrue(row.isEnabled, "…and a document with a canvas can be exported")
        row.tap()

        let video = app.buttons["export.videoButton"]
        XCTAssertTrue(video.waitForExistence(timeout: 5),
                      "the row opens the export sheet — a sheet raised from inside the Actions panel presents")
        XCTAssertTrue(app.buttons["export.frameButton"].exists, "…offering both products (§3.9)")
        let caption = app.staticTexts["export.caption"]
        XCTAssertTrue(caption.exists)
        XCTAssertTrue(caption.label.contains("fps"), """
            The caption is where §2.8 becomes visible — the pixel size the knob produces and the \
            rate, at the moment the artist is about to hand a file to somebody. It reads \
            \(caption.label).
            """)

        video.tap()

        // The wait, which is the reason this is a sheet at all. Polled without a sleep so a fast
        // machine is still caught; `export.status` and the bar are the two halves of the running
        // view and either one appearing means the phase reached the artist.
        let progress = app.progressIndicators["export.progress"]
        let status = app.staticTexts["export.status"]
        let share = app.buttons["export.share"]
        var sawRunning = false
        let deadline = Date().addingTimeInterval(120)
        while Date() < deadline {
            if progress.exists || status.exists { sawRunning = true }
            if share.exists { break }
        }
        XCTAssertTrue(sawRunning, """
            The export never showed the artist that it was working. §3.9 asks for visible progress, \
            and a sheet that goes straight from the two buttons to a Share button is an export whose \
            phase never reached the view.
            """)
        XCTAssertTrue(share.waitForExistence(timeout: 120), """
            The export never finished. Nothing else in the app can say this: the driver's own tests \
            run headless, so a bake that never reaches the sheet, or a sheet that never re-renders \
            on the finished phase, looks like a pass everywhere but here.
            """)
        XCTAssertTrue(app.buttons["export.doneButton"].exists, "…and it offers a way out")

        share.tap()
        XCTAssertTrue(app.otherElements["ActivityListView"].waitForExistence(timeout: 20),
                      "Delivery is the system share sheet (§3.9), and `ShareLink` is what raises it")
        // Left up rather than dismissed. Every test in this class starts with `launchIntoEditor`,
        // which calls `app.launch()`, so the next one gets a fresh process and none of this — and
        // the obvious tidy-up is a trap: three `PopoverDismissRegion`s are on screen here (the
        // Actions panel's, the sheet's and the activity view's) and a query for the identifier is
        // ambiguous, which MEASURED as a failed tap rather than a clean close.
    }

}

final class SelectionAndMoveUITests: PaintUITestCase {

    /// **A lasso move moves only what is inside the loop** — the whole feature, driven the way the
    /// artist drives it: draw a line, select part of it, tap Move, drag, tap Move again.
    ///
    /// In an existing class rather than a new one on purpose: `xcodebuild` distributes parallel work
    /// per test *class*, so a new heavy class lengthens the critical path of the whole suite.
    ///
    /// What only a UI test can say here is that the wiring holds end to end — the toolbar reaches
    /// `beginVectorLassoMove`, the box takes the drag instead of the canvas painting under it, and
    /// the second Move tap bakes rather than lifting again. The geometry itself is
    /// `LassoMoveLogicTests`' business.
    func testLassoMoveSplitsTheStrokeAndCarriesOnlyTheLassoedHalf() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))

        // One horizontal line across the upper canvas, on the default vector layer.
        dragOnCanvas(app, from: CGVector(dx: 0.2, dy: 0.26), to: CGVector(dx: 0.85, dy: 0.26))
        app.buttons["toolbar.layersButton"].tap()   // the marker lives in the layer panel
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 1, "one stroke to start with")
        app.buttons["toolbar.layersButton"].tap()   // and the panel covers the canvas, so close it

        // Select its right-hand half. Upper canvas, clear of the Select menu's bottom-docked bar.
        app.buttons["toolbar.selectButton"].tap()
        let rectangleMode = app.buttons["selectPanel.mode.rectangle"]
        XCTAssertTrue(rectangleMode.waitForExistence(timeout: 5))
        rectangleMode.tap()
        dragOnCanvas(app, from: CGVector(dx: 0.6, dy: 0.16), to: CGVector(dx: 0.95, dy: 0.36))

        // Move lifts the lassoed half. Nothing visibly changes yet — the float sits exactly over the
        // hole it came out of — so the assertions worth making are about where it *lands*.
        app.buttons["toolbar.moveButton"].tap()
        // Drag the box down by roughly a fifth of the canvas, then Move again to bake it.
        dragOnCanvas(app, from: CGVector(dx: 0.75, dy: 0.26), to: CGVector(dx: 0.75, dy: 0.46))
        app.buttons["toolbar.moveButton"].tap()

        XCTAssertTrue(isWhitish(rgbaPixel(of: canvas, dx: 0.75, dy: 0.26)),
                      "the lassoed half should have left the paper it came off bare")
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: 0.3, dy: 0.26)),
                       "while the half outside the loop is exactly where it was drawn")
        // A band rather than one row: XCUITest's synthetic drags undershoot by a timing-dependent
        // amount (see `dragElement`), so the assertion is "it moved down", not "it moved 0.20".
        let landedRow = stride(from: 0.33, through: 0.52, by: 0.01)
            .first { !isWhitish(rgbaPixel(of: canvas, dx: 0.75, dy: $0)) }
        XCTAssertNotNil(landedRow, "the moved half should have landed somewhere below where it started")
        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 2,
                       "the stroke the loop crossed became two independent strokes")
    }

    /// **The Move menu replaces the Select menu while a lassoed piece is floating, and hands it back
    /// when the piece bakes** — owner, 2026-08-22: *"when moving, there should be an option menu on
    /// the bottom instead of still keeping the select menu."*
    ///
    /// Three things only a UI test can say, and all three were false before this change:
    ///
    ///  * the bar comes up for a **vector** float at all — its gate read `floatingPiece != nil`, the
    ///    raster piece, so a lassoed piece got six grips and no menu;
    ///  * the Select menu stands down while it is up. The two dock at the same place and could both
    ///    be on screen at once;
    ///  * `activePanel` is **not** cleared, so the Select menu is back the moment the piece bakes.
    ///    That is the difference between suppressing a presentation and closing a panel, and it is
    ///    invisible to anything that only checks the first two.
    ///
    /// Watched failing with `DrawingView`'s two gates put back the way they were —
    /// `if canvasManager.floatingPiece != nil` for the bar and a bare `if activePanel == .select` for
    /// the panel: *XCTAssertTrue failed — a lassoed vector piece raises the Move menu, exactly as a
    /// raster piece does*, at the `waitForExistence` on Done, because on the default (vector) layer
    /// kind the bar never came up at all.
    func testTheMoveMenuReplacesTheSelectMenuWhileAPieceFloatsAndGivesItBack() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))

        dragOnCanvas(app, from: CGVector(dx: 0.2, dy: 0.26), to: CGVector(dx: 0.85, dy: 0.26))

        app.buttons["toolbar.selectButton"].tap()
        let rectangleMode = app.buttons["selectPanel.mode.rectangle"]
        XCTAssertTrue(rectangleMode.waitForExistence(timeout: 5))
        rectangleMode.tap()
        dragOnCanvas(app, from: CGVector(dx: 0.6, dy: 0.16), to: CGVector(dx: 0.95, dy: 0.36))
        XCTAssertTrue(rectangleMode.exists, "setup: the Select menu is the one that is up")

        app.buttons["toolbar.moveButton"].tap()

        let doneButton = app.buttons["moveBar.doneButton"]
        XCTAssertTrue(doneButton.waitForExistence(timeout: 5),
                      "a lassoed vector piece raises the Move menu, exactly as a raster piece does")
        XCTAssertFalse(rectangleMode.exists, "and the Select menu stands down rather than stacking under it")
        // Every button the bar offers this piece — a stroke, so Mirror is available — is live rather
        // than decorative. Reset is the one that starts off: nothing has been dragged yet.
        for identifier in ["moveBar.mirrorHorizontalButton", "moveBar.mirrorVerticalButton",
                           "moveBar.rotate45LeftButton", "moveBar.rotate45RightButton",
                           "moveBar.rotate90LeftButton", "moveBar.rotate90RightButton"] {
            XCTAssertTrue(app.buttons[identifier].isEnabled, "\(identifier) should be usable on a lassoed stroke")
        }
        XCTAssertFalse(app.buttons["moveBar.resetButton"].isEnabled,
                       "Reset has nothing to put back until the piece has been moved")

        dragOnCanvas(app, from: CGVector(dx: 0.75, dy: 0.26), to: CGVector(dx: 0.75, dy: 0.44))
        XCTAssertTrue(app.buttons["moveBar.resetButton"].isEnabled, "and turns on once it has")

        doneButton.tap()

        XCTAssertTrue(rectangleMode.waitForExistence(timeout: 5),
                      "baking the piece gives the artist back the panel they were in — `activePanel` was never cleared")
        XCTAssertFalse(doneButton.exists, "and the Move menu goes with the piece")
    }

    /// Rectangle-select a region, then Fill it — the fill should land directly in the raster tier
    /// (Cel.raster), the same tier the eraser stamps into, not a separate Cel.bakedImage layer the
    /// eraser can never reach (see `CanvasManager.registerUndoableCelChange`'s doc comment).
    func testRectangleSelectThenFillBakesPixels() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        // On a vector layer `fillSelection` correctly adds a `VectorFillElement` instead
        // (SelectionModels.swift), so the raster tier this test is about is only reachable on a
        // raster layer — which is no longer what a new canvas starts on (PLAN §8).
        addRasterLayer(app)

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 1), false, "A fresh layer shouldn't have baked content yet")
        app.buttons["toolbar.layersButton"].tap() // close panel so it can't cover the canvas

        app.buttons["toolbar.selectButton"].tap()
        let rectangleMode = app.buttons["selectPanel.mode.rectangle"]
        XCTAssertTrue(rectangleMode.waitForExistence(timeout: 5))
        rectangleMode.tap()

        // Draw the selection in the upper portion of the canvas, clear of the Select menu's bar
        // (which docks at the bottom, covering the lower portion of the screen).
        dragOnCanvas(app, from: CGVector(dx: 0.55, dy: 0.25), to: CGVector(dx: 0.78, dy: 0.42))

        let fillButton = app.buttons["selectPanel.fillButton"]
        XCTAssertTrue(fillButton.waitForExistence(timeout: 5))
        fillButton.tap()

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 1), false, "Filling should land in the raster tier, not a separate baked-image tier")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 1), 1, "Filling the selection should register as raster content, so the eraser can reach it")
    }

    /// Draw a stroke, rectangle-select it, Duplicate: a new **vector** layer should appear
    /// immediately (holding the floating copy), and the Move bottom bar's Done button should commit
    /// it there as geometry, without touching the source layer.
    ///
    /// **This test used to duplicate blank paper and assert the copy was raster** — TODO item (33),
    /// the owner's *"When I select and duplicate, it does not support vector (the duplicated
    /// selection is a raster layer not a vector)."* It was pinning the defect: a new canvas opens on
    /// a vector layer (PLAN §8), `beginDuplicate()` had no kind check, and so the copy arrived as
    /// pixels. It draws a stroke first now because there is nothing to duplicate on blank paper —
    /// the vector arm refuses an empty loop exactly as `beginVectorLassoMove` does.
    ///
    /// `readVectorMarker` is what tells a vector copy from a rasterized one; the images are identical
    /// at the size the copy was taken, which is the whole reason this bug lived for as long as it did.
    func testDuplicateSelectionCreatesNewVectorLayerAndCommits() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        dragOnCanvas(app, from: CGVector(dx: 0.2, dy: 0.26), to: CGVector(dx: 0.85, dy: 0.26))

        app.buttons["toolbar.selectButton"].tap()
        let rectangleMode = app.buttons["selectPanel.mode.rectangle"]
        XCTAssertTrue(rectangleMode.waitForExistence(timeout: 5))
        rectangleMode.tap()

        // Around the whole stroke, in the upper portion of the canvas and clear of the Select menu's
        // bottom-docked bar (see the fill test).
        dragOnCanvas(app, from: CGVector(dx: 0.15, dy: 0.16), to: CGVector(dx: 0.95, dy: 0.38))

        let duplicateButton = app.buttons["selectPanel.duplicateButton"]
        XCTAssertTrue(duplicateButton.waitForExistence(timeout: 5))
        duplicateButton.tap()

        let doneButton = app.buttons["moveBar.doneButton"]
        XCTAssertTrue(doneButton.waitForExistence(timeout: 5), "Duplicate should immediately float the copy, showing the Move bottom bar")
        doneButton.tap()

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForExistence(timeout: 5), "Duplicate should have inserted a second layer")
        let copy = readVectorMarker(app, layerIndex: 1)
        XCTAssertEqual(copy?.isVector, true, "A copy taken from a vector layer is itself a vector layer")
        XCTAssertEqual(copy?.strokes, 1, "and carries the lassoed stroke as geometry, not as pixels")
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 1), false, "Nothing lands in the copy's raster tiers")
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 1, "Duplicate must not modify the source layer")
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 0), false, "Duplicate must not modify the source layer")
    }

    /// A brush stroke that crosses outside the active selection is clipped to it by default ("Paint
    /// Outside Selection" starts denied) — the paint outside the marching ants is discarded, reverting
    /// to blank paper — and flipping that toggle on lets the same stroke shape paint past the boundary.
    func testDenyOutsideSelectionClipsStrokeUntilToggledOn() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        app.buttons["toolbar.selectButton"].tap()
        let rectangleMode = app.buttons["selectPanel.mode.rectangle"]
        XCTAssertTrue(rectangleMode.waitForExistence(timeout: 5))
        rectangleMode.tap()

        // A rectangle selection in the upper-left quadrant; the probe points below straddle its right
        // edge (dx: 0.55) so one lands inside and one lands clearly outside.
        dragOnCanvas(app, from: CGVector(dx: 0.3, dy: 0.2), to: CGVector(dx: 0.55, dy: 0.35))

        let allowToggle = app.buttons["selectPanel.allowOutsideToggle"]
        XCTAssertTrue(allowToggle.waitForExistence(timeout: 5))

        // Switch to the brush tool — exercises the Select-exit fix (TopToolbar's two-stage tap helpers):
        // this must land on plain drawing (activePanel == .none), not pop the brush settings panel open.
        app.buttons["toolbar.brushButton"].tap()
        XCTAssertFalse(app.buttons["selectPanel.mode.rectangle"].exists, "Selecting the brush tool should fully exit Select, not just unhighlight its icon")

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        // A horizontal stroke starting inside the selection (dx 0.4) and ending well outside it (dx 0.75).
        dragOnCanvas(app, from: CGVector(dx: 0.4, dy: 0.275), to: CGVector(dx: 0.75, dy: 0.275))

        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: 0.45, dy: 0.275)), "Paint inside the selection should land normally")
        XCTAssertTrue(isWhitish(rgbaPixel(of: canvas, dx: 0.65, dy: 0.275)), "Paint outside the selection should be discarded while outside interaction is denied")

        // Flip the toggle on and repeat the same stroke — this time it should reach past the boundary.
        app.buttons["toolbar.selectButton"].tap()
        XCTAssertTrue(allowToggle.waitForExistence(timeout: 5))
        allowToggle.tap()

        app.buttons["toolbar.brushButton"].tap()
        dragOnCanvas(app, from: CGVector(dx: 0.4, dy: 0.275), to: CGVector(dx: 0.75, dy: 0.275))
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: 0.65, dy: 0.275)), "With outside interaction allowed, the same stroke should now paint past the selection boundary")
    }

    /// With no active selection, Move lifts the whole current layer; committing bakes it back into
    /// the raster tier (not a separate Cel.bakedImage layer — see `registerUndoableCelChange`'s doc
    /// comment) so the moved content stays reachable by the eraser afterwards.
    func testMoveWithNoSelectionLiftsWholeLayerAndCommits() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        // The *raster* floating-piece path is what this test is about, and a vector layer does not
        // take it: `TopToolbar.toggleMove` sends one to `beginVectorWholeCelMove`, which lifts a
        // `VectorFloat` — geometry, not pixels, and nothing lands in the raster tier. (Until
        // 2026-08-27 it toggled a whole-layer `isVectorTransforming` flag, since deleted, and showed
        // no Move bar at all; either way this test has to ask for the raster layer whose
        // lift-and-bake it is about, vector being the default kind since PLAN §8.)
        addRasterLayer(app)

        dragOnCanvas(app, from: CGVector(dx: 0.3, dy: 0.3), to: CGVector(dx: 0.5, dy: 0.3))

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 1), 1, "Setup: the stroke should have landed as one PencilKit stroke")
        app.buttons["toolbar.layersButton"].tap() // close panel so it can't cover the canvas

        app.buttons["toolbar.moveButton"].tap()
        let doneButton = app.buttons["moveBar.doneButton"]
        // beginMove() rasterizes the whole cel synchronously via PixelOps.rasterize (plain Core
        // Graphics, no PencilKit involved since the Session 11 engine rewrite), so this should be
        // near-instant; kept in line with the suite's other generous waits.
        XCTAssertTrue(doneButton.waitForExistence(timeout: 10), "Move with no selection should float the whole layer")
        doneButton.tap()

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 1), false, "Committing the move should land in the raster tier, not a separate baked-image tier")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 1), 1, "The moved content should still register as raster content, not disappear from the tier the eraser reaches")
    }

    // MARK: - The eyedropper while the Select panel is open (owner, 2026-08-22)

    /// Reads the hex the eyedropper button carries, split into channels, or fails the test.
    /// `sideToolbar.eyedropperButton`'s `accessibilityValue` is `brushColor.hexString` — the rail
    /// shows the colour the *next* pick will replace, so it is also how a completed pick is read back
    /// without opening the colour panel over the canvas that was just sampled.
    private func brushChannels(_ eyedropper: XCUIElement,
                               file: StaticString = #filePath, line: UInt = #line) -> (r: Int, g: Int, b: Int)? {
        guard let hex = eyedropper.value as? String, hex.count >= 6,
              let r = Int(hex.prefix(2), radix: 16),
              let g = Int(hex.dropFirst(2).prefix(2), radix: 16),
              let b = Int(hex.dropFirst(4).prefix(2), radix: 16) else {
            XCTFail("Expected a hex colour on the eyedropper button, got \(String(describing: eyedropper.value))",
                    file: file, line: line)
            return nil
        }
        return (r, g, b)
    }

    /// Paints a red line across the upper canvas and leaves the brush black, so a pick that silently
    /// did nothing is distinguishable from one that worked. Lifted from
    /// `EraserAndPersistenceUITests.testTheSidebarEyedropperPicksTheColourUnderTheTapAndRevertsTheTool`,
    /// including its reason for closing the colour panel with a confirmed wait: the panel is a
    /// dropdown over the right of the canvas and the stroke runs straight under it.
    private func paintRedLineAndReturnToBlack(_ app: XCUIApplication, at dy: Double) {
        let colorButton = app.buttons["toolbar.colorButton"]
        XCTAssertTrue(colorButton.waitForExistence(timeout: 5))

        func closeColorPanel() {
            colorButton.tap()
            XCTAssertTrue(app.otherElements["colorPanel.svSquare"].waitForNonExistence(timeout: 5),
                          "The colour panel must be closed before the canvas is touched")
        }

        colorButton.tap()
        let hexField = app.textFields["colorPanel.hexField"]
        XCTAssertTrue(hexField.waitForExistence(timeout: 5))
        setHexField(app, hexField, to: "FF0000")
        closeColorPanel()

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        drawLine(on: canvas, from: CGVector(dx: 0.3, dy: dy), to: CGVector(dx: 0.7, dy: dy))

        // Back to black through the SV square rather than the hex field: the field needs the
        // keyboard, and a second visit to it mid-test is a focus race this test has nothing to do
        // with. Bottom-left of the square is saturation 0, brightness 0.
        colorButton.tap()
        let svSquare = app.otherElements["colorPanel.svSquare"]
        XCTAssertTrue(svSquare.waitForExistence(timeout: 5))
        dragWithinElement(svSquare, from: CGVector(dx: 0.5, dy: 0.5), to: CGVector(dx: 0.0, dy: 1.0))
        closeColorPanel()
    }

    /// **The owner's bug** (2026-08-22): *"The pick tool does not work when the lasso select tool is
    /// selected."*
    ///
    /// There is no `.select` case in `Tool` — Select is a *panel*, and `selectedTool` stays whatever
    /// it was — so with the panel open two things were true at once: `updateActiveLayerAndTool` left
    /// `eyedropperTapRecognizer` disabled (its guard read `activePanel != .select`), and
    /// `updateSelectionOverlay` kept the selection overlay capturing (its condition never consulted
    /// `selectedTool`). Recogniser off, overlay eating the touch: the pick was dead, and arming the
    /// tool does not close the panel, so nothing re-enabled it.
    ///
    /// `Tool.eyedropper`'s own doc comment is the ruling this encodes: the tool is momentary, and the
    /// artist "reaches for this one in the middle of doing something else". So while it is armed it
    /// wins over the Select overlay — and hands straight back, which is the second half of this test.
    /// The panel is still open afterwards, so the artist carries on lassoing with the colour they
    /// just took.
    func testTheEyedropperPicksWhileTheSelectPanelIsOpenAndHandsTheLassoBack() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        // Well up the canvas, clear of the Select panel's bottom-docked bar.
        paintRedLineAndReturnToBlack(app, at: 0.30)

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))

        app.buttons["toolbar.selectButton"].tap()
        let lassoMode = app.buttons["selectPanel.mode.lasso"]
        XCTAssertTrue(lassoMode.waitForExistence(timeout: 5))
        lassoMode.tap()

        let eyedropper = app.buttons["sideToolbar.eyedropperButton"]
        XCTAssertTrue(eyedropper.waitForExistence(timeout: 5))
        XCTAssertEqual(eyedropper.value as? String, "000000", "Sanity: the brush is black before the pick")

        eyedropper.tap()
        XCTAssertTrue(eyedropper.isSelected, "Tapping the rail button arms the tool")
        // The state the bug needs, asserted rather than assumed: arming the eyedropper must NOT close
        // the Select panel. If a later change makes it close, this test stops covering the bug and
        // this line is what says so.
        XCTAssertTrue(lassoMode.exists,
                      "Arming the eyedropper must leave the Select panel open — that is the reported situation")

        // The tap that does the picking, right on the red line.
        canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.30)).tap()

        // The composite runs off the main thread, so the colour lands a beat after the tap.
        expectation(for: NSPredicate(format: "value != %@", "000000"), evaluatedWith: eyedropper)
        waitForExpectations(timeout: 10)

        guard let c = brushChannels(eyedropper) else { return }
        XCTAssertGreaterThan(c.r, 200, """
            The pick did nothing with the Select panel open. That is the owner's report of \
            2026-08-22: `CanvasView.updateActiveLayerAndTool` disabled the eyedropper's recognizer \
            whenever `activePanel == .select`, and `updateSelectionOverlay` kept the selection \
            overlay capturing regardless of the tool, so the tap became the start of a lasso. See \
            `Tool.eyedropper` for why an armed eyedropper outranks the overlay.
            """)
        XCTAssertLessThan(c.g, 80, "…the pick should be the red line's colour")
        XCTAssertLessThan(c.b, 80, "…the pick should be the red line's colour")

        XCTAssertFalse(eyedropper.isSelected,
                       "A completed pick hands the canvas back to the previous tool (Tool.eyedropper)")

        // The second half, and the reason the overlay yields rather than being switched off: the
        // artist picked a colour *so that* they could carry on. The panel is still up…
        XCTAssertTrue(lassoMode.exists, "The Select panel is still open after the pick")
        let fillButton = app.buttons["selectPanel.fillButton"]
        XCTAssertTrue(fillButton.waitForExistence(timeout: 5))
        XCTAssertFalse(fillButton.isEnabled, "Sanity: the pick itself must not have created a selection")

        // …and the overlay is capturing again, so a drag lassoes.
        dragOnCanvas(app, from: CGVector(dx: 0.30, dy: 0.20), to: CGVector(dx: 0.60, dy: 0.42))
        XCTAssertTrue(fillButton.isEnabled, """
            The selection overlay never resumed capturing after the pick. It yields *while the \
            eyedropper is armed* and the revert is what hands it back, so if this fails while the \
            pick above passed, the yield is keyed off something that outlives the pick.
            """)
    }

    /// The other side of the same guard: with the Select panel open and the eyedropper **not** armed,
    /// the overlay owns the canvas exactly as it always has. This is the assertion that stops the fix
    /// above from being spelled "the overlay stops capturing whenever Select is open", which would
    /// delete the Select tool.
    func testTheSelectOverlayStillOwnsTheCanvasWhileTheEyedropperIsNotArmed() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        paintRedLineAndReturnToBlack(app, at: 0.30)

        app.buttons["toolbar.selectButton"].tap()
        let lassoMode = app.buttons["selectPanel.mode.lasso"]
        XCTAssertTrue(lassoMode.waitForExistence(timeout: 5))
        lassoMode.tap()

        let eyedropper = app.buttons["sideToolbar.eyedropperButton"]
        XCTAssertTrue(eyedropper.waitForExistence(timeout: 5))
        XCTAssertFalse(eyedropper.isSelected, "The eyedropper is not armed — this is the ordinary case")

        let fillButton = app.buttons["selectPanel.fillButton"]
        XCTAssertTrue(fillButton.waitForExistence(timeout: 5))
        XCTAssertFalse(fillButton.isEnabled, "Sanity: no selection yet")

        // A drag straight over the red line: the overlay must take it as a lasso, and nothing must
        // sample a colour off it.
        dragOnCanvas(app, from: CGVector(dx: 0.30, dy: 0.20), to: CGVector(dx: 0.60, dy: 0.42))

        XCTAssertTrue(fillButton.isEnabled,
                      "With the eyedropper unarmed, a canvas drag must still make a selection")
        XCTAssertEqual(eyedropper.value as? String, "000000", """
            The brush colour changed without the eyedropper being armed. The overlay must yield only \
            while `selectedTool == .eyedropper`; if this fails, the recognizer was left live for \
            every tool.
            """)
    }

    /// What the `floatingPiece == nil` half of the two guards is worth, pinned as behaviour: the rail
    /// button calls `commitAllInteractiveState()` **before** `selectEyedropper()`
    /// (`SideToolbar.eyedropperButton`), and that calls `commitFloatingPieceIfNeeded()` — so arming
    /// the eyedropper bakes a floating piece on the way in and the two states never coexist through
    /// this door. The guard clause is therefore already unreachable rather than load-bearing, and
    /// this test is what would notice if the bake were ever removed from that button.
    func testArmingTheEyedropperBakesAFloatingPieceRatherThanRacingIt() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        // The *raster* floating-piece path this test is about is not what a vector layer takes —
        // `TopToolbar.toggleMove` sends one to `beginVectorWholeCelMove` and it floats geometry — and
        // vector is the default kind, so ask for a raster layer explicitly.
        addRasterLayer(app)

        dragOnCanvas(app, from: CGVector(dx: 0.3, dy: 0.3), to: CGVector(dx: 0.5, dy: 0.3))

        app.buttons["toolbar.moveButton"].tap()
        let doneButton = app.buttons["moveBar.doneButton"]
        XCTAssertTrue(doneButton.waitForExistence(timeout: 10), "Setup: Move with no selection floats the whole layer")

        let eyedropper = app.buttons["sideToolbar.eyedropperButton"]
        XCTAssertTrue(eyedropper.waitForExistence(timeout: 5))
        eyedropper.tap()

        XCTAssertTrue(doneButton.waitForNonExistence(timeout: 5), """
            Arming the eyedropper must settle a floating piece, not sit alongside one. \
            `SideToolbar.eyedropperButton` calls `commitAllInteractiveState()` first for exactly \
            this reason — the tool samples the composite, and a piece still in the air is content \
            the artist can see and would expect to pick from.
            """)
        XCTAssertTrue(eyedropper.isSelected, "…and the tool is armed once the piece is down")
    }

    /// Why the identical `activePanel != .select` guard on `textTapRecognizer` (CanvasView) is **not**
    /// the same bug: text is entered from the Actions menu, and `ActionsMenu.addTextRow` follows
    /// `enterTextMode()` with `$activePanel.toggleSettingsPanel(.text)`. Both of the guard's clauses
    /// cannot be true at once through that door, because arriving in text mode *is* what closes the
    /// Select panel.
    ///
    /// Left as behaviour rather than a comment because the reasoning is entirely about a call order
    /// two files apart: reversing those two statements, or dropping the panel toggle, would reopen it.
    func testEnteringTextModeClosesTheSelectPanelSoTextsOwnGuardCannotBite() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        app.buttons["toolbar.selectButton"].tap()
        let lassoMode = app.buttons["selectPanel.mode.lasso"]
        XCTAssertTrue(lassoMode.waitForExistence(timeout: 5))
        lassoMode.tap()

        app.buttons["toolbar.actionsButton"].tap()
        let addText = app.buttons["actions.addTextRow"]
        XCTAssertTrue(addText.waitForExistence(timeout: 5))
        XCTAssertTrue(addText.isEnabled, "Sanity: Add Text is available on the default vector layer")
        addText.tap()

        // `textPanel.fontButton` rather than the panel's own `panel.textSettings` identifier: that one
        // sits on a plain SwiftUI container, which UIKit does not surface as an element of any
        // queryable type — it never appeared, which is a wrong *probe* and not a wrong app.
        XCTAssertTrue(app.buttons["textPanel.fontButton"].waitForExistence(timeout: 5),
                      "Add Text opens the text settings panel")
        XCTAssertFalse(lassoMode.exists, """
            Entering text mode left the Select panel open, which puts `textTapRecognizer` in exactly \
            the state the eyedropper was in: disabled by `activePanel != .select` with the selection \
            overlay still eating the canvas touch. See CanvasView.updateActiveLayerAndTool.
            """)
    }

}

final class EraserAndPersistenceUITests: PaintUITestCase {

    /// Save -> relaunch -> reload round trip, exercising the real `ProjectStore.save`/`load` path
    /// (not just the manifest struct in isolation — this UI test target has no `@testable import`
    /// access to call those directly, confirmed by a link failure when tried). Draws a stroke,
    /// returns to the gallery (via the toolbar's gallery button — its SwiftUI `Image(systemName:)`
    /// gets "square.grid.2x2" as its accessibility identifier automatically, since TopToolbar
    /// doesn't set one explicitly), force-quits and relaunches the whole app (so this genuinely
    /// re-reads from disk, not just in-memory state), reopens the one saved project from the
    /// gallery, and asserts the stroke (and therefore the layer/cel raster data) survived.
    ///
    /// This also serves as a build-time-only regression check for the manifest schema additions
    /// (`LayerManifest.kind`, `ProjectManifest.selectedBrush`/`customBrushes`): every save now
    /// encodes those fields and every load decodes them, so a save/load cycle silently failing to
    /// decode (e.g. a typo'd CodingKeys case) would make this test hang or fail outright rather
    /// than passing.
    ///
    /// It now *does* cover a non-raster `LayerKind` end-to-end, which it could not when it was
    /// written: vector is the default layer kind (PLAN §8), so the stroke below is geometry, and a
    /// round trip that survives is `LayerManifest.kind` plus the whole vector payload surviving with
    /// it. Reading the vector marker rather than `readLayerStrokeCount` is what makes that real —
    /// the raster tier stays empty on a vector layer, so the old reader would now assert nothing.
    /// A non-default *brush* is still out of reach here and still covered at the `Codable` level.
    func testSaveAndReloadPersistsStrokesAcrossAppRelaunch() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        dragOnCanvas(app, from: CGVector(dx: 0.3, dy: 0.3), to: CGVector(dx: 0.5, dy: 0.3))

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 1, "Setup: the stroke should have landed before saving")
        app.buttons["toolbar.layersButton"].tap() // close panel

        // Back to gallery, which triggers ContentView.saveIfNeeded() -> ProjectStore.save.
        let galleryButton = app.buttons["square.grid.2x2"]
        XCTAssertTrue(galleryButton.waitForExistence(timeout: 5))
        galleryButton.tap()

        let projectTile = app.staticTexts.matching(NSPredicate(format: "label == %@", "Untitled")).firstMatch
        XCTAssertTrue(projectTile.waitForExistence(timeout: 5), "Setup: the saved project should show up in the gallery")

        // Force-quit and relaunch the whole app so reopening the project genuinely re-reads the
        // manifest + PNGs from disk (ProjectStore.load) instead of reusing in-memory CanvasManager
        // state left over from the editor.
        app.terminate()
        app.launch()
        let reopenedTile = app.staticTexts.matching(NSPredicate(format: "label == %@", "Untitled")).firstMatch
        XCTAssertTrue(reopenedTile.waitForExistence(timeout: 10), "Project should still be listed after relaunch")
        reopenedTile.tap()

        let frameLabel = app.staticTexts["timeline.frameLabel"]
        XCTAssertTrue(frameLabel.waitForExistence(timeout: 10), "Reopening the project should land back in the editor")

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 1, "Stroke drawn before saving should survive a save -> relaunch -> load round trip")
    }

    /// Exercises all three color controls (hue bar, SV square, hex field) and confirms each one
    /// actually lands on `canvasManager.brushColor`: after dragging the hue bar and SV square to a
    /// known corner (full saturation/brightness at a chosen hue), reads the hex field back to
    /// confirm it reactively shows the resulting color, then types a different hex value in
    /// directly and draws a stroke, pixel-sampling it to confirm the *drawn* color matches what was
    /// typed — the strongest possible check that brushColor actually changed and reached the canvas,
    /// not just some intermediate SwiftUI state.
    func testColorPanelControlsChangeBrushColorAndPaintedStroke() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let colorButton = app.buttons["toolbar.colorButton"]
        XCTAssertTrue(colorButton.waitForExistence(timeout: 5))
        colorButton.tap()

        // Hue bar: drag to the far left (hue 0 == red).
        let hueSlider = app.otherElements["colorPanel.hueSlider"]
        XCTAssertTrue(hueSlider.waitForExistence(timeout: 5))
        dragWithinElement(hueSlider, from: CGVector(dx: 0.5, dy: 0.5), to: CGVector(dx: 0.0, dy: 0.5))

        // SV square: drag to the top-right corner (saturation 1, brightness 1) so the result is
        // pure, fully-saturated red rather than some in-between shade.
        let svSquare = app.otherElements["colorPanel.svSquare"]
        XCTAssertTrue(svSquare.waitForExistence(timeout: 5))
        dragWithinElement(svSquare, from: CGVector(dx: 0.5, dy: 0.5), to: CGVector(dx: 1.0, dy: 0.0))

        // The hex field should reactively reflect that as pure red, confirming the hue bar/SV
        // square drags actually updated brushColor (not just their own local indicator).
        let hexField = app.textFields["colorPanel.hexField"]
        XCTAssertTrue(hexField.waitForExistence(timeout: 5))
        let hexAfterDrag = hexField.value as? String
        XCTAssertEqual(hexAfterDrag?.uppercased(), "FF0000", "Dragging hue to red and SV to full saturation/brightness should show FF0000 in the hex field, got \(String(describing: hexAfterDrag))")

        // Now drive the color from the hex field directly, to a distinct color (pure green).
        hexField.tap()
        // Clear the field's existing text ("FF0000") with backspaces before typing the new value —
        // XCUIElement has no built-in "select all and replace", so this deletes character-by-character.
        if let currentValue = hexField.value as? String {
            hexField.typeText(String(repeating: "\u{8}", count: currentValue.count))
        }
        hexField.typeText("00FF00")
        app.keyboards.buttons["Return"].tap()

        colorButton.tap() // Close the panel so it can't cover the canvas.

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        drawLine(on: canvas, from: CGVector(dx: 0.3, dy: 0.5), to: CGVector(dx: 0.7, dy: 0.5))

        guard let pixel = rgbaPixel(of: canvas, dx: 0.5, dy: 0.5) else {
            XCTFail("Could not sample the drawn stroke's pixel color")
            return
        }
        XCTAssertGreaterThan(pixel.g, 200, "Stroke drawn after setting hex to 00FF00 should be green-dominant, got \(pixel)")
        XCTAssertLessThan(pixel.r, 80, "Stroke drawn after setting hex to 00FF00 should have low red, got \(pixel)")
        XCTAssertLessThan(pixel.b, 80, "Stroke drawn after setting hex to 00FF00 should have low blue, got \(pixel)")
    }

    /// **The eyedropper's wiring** (owner, 2026-08-17: a tool you select and then tap the canvas with).
    ///
    /// Deliberately the *only* XCUITest for this feature: everything about the pick that can be
    /// numerically wrong — which pixel a point names, un-premultiplying, the composite-vs-layer
    /// choice, the revert — is swept exactly in `EyedropperLogicTests`, headlessly, in two seconds.
    /// What that cannot reach is whether the button is on the rail, whether selecting it arms the
    /// gesture, and whether a real touch on the real canvas reaches `handleEyedropperPress` at all.
    /// That is what this covers, and it covers it end to end: paint a known colour, change the brush
    /// to a different one, pick the painted colour back.
    ///
    /// The button's `accessibilityValue` is `brushColor`'s hex, so the pick is read off the rail
    /// without reopening the colour panel — the panel would cover the canvas this test just sampled.
    func testTheSidebarEyedropperPicksTheColourUnderTheTapAndRevertsTheTool() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let colorButton = app.buttons["toolbar.colorButton"]
        XCTAssertTrue(colorButton.waitForExistence(timeout: 5))

        /// Closes the colour panel and waits until it is really gone. **Not optional**: the panel is
        /// a dropdown over the right of the canvas, and the stroke this test draws runs straight
        /// under it — an unconfirmed close meant the drag landed on the hue bar instead of the
        /// canvas and repainted the brush a colour nothing had asked for.
        func closeColorPanel() {
            colorButton.tap()
            XCTAssertTrue(app.otherElements["colorPanel.svSquare"].waitForNonExistence(timeout: 5),
                          "The colour panel must be closed before the canvas is touched")
        }

        // Paint a red stroke across the middle of the canvas…
        colorButton.tap()
        let hexField = app.textFields["colorPanel.hexField"]
        XCTAssertTrue(hexField.waitForExistence(timeout: 5))
        setHexField(app, hexField, to: "FF0000")
        closeColorPanel()

        let eyedropper = app.buttons["sideToolbar.eyedropperButton"]
        XCTAssertTrue(eyedropper.waitForExistence(timeout: 5),
                      "The eyedropper sits on the left rail, below the opacity slider")
        XCTAssertEqual(eyedropper.value as? String, "FF0000", "Sanity: the hex reached brushColor")

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        drawLine(on: canvas, from: CGVector(dx: 0.3, dy: 0.5), to: CGVector(dx: 0.7, dy: 0.5))

        // …then move the brush to a colour nothing on the canvas is, so a pick that silently did
        // nothing is distinguishable from one that worked. Through the SV square rather than the hex
        // field: the field needs the keyboard, and a second visit to it mid-test is a focus race the
        // pick has nothing to do with. Bottom-left of the square is saturation 0, brightness 0 —
        // black, whatever the hue happens to be.
        colorButton.tap()
        let svSquare = app.otherElements["colorPanel.svSquare"]
        XCTAssertTrue(svSquare.waitForExistence(timeout: 5))
        dragWithinElement(svSquare, from: CGVector(dx: 0.5, dy: 0.5), to: CGVector(dx: 0.0, dy: 1.0))
        closeColorPanel()

        XCTAssertEqual(eyedropper.value as? String, "000000", "Sanity: the brush is black before the pick")
        XCTAssertFalse(eyedropper.isSelected, "…and the tool is not armed yet")

        eyedropper.tap()
        XCTAssertTrue(eyedropper.isSelected, "Tapping it selects the tool rather than opening a picker")

        // The tap that does the picking, right on the stroke.
        canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.5)).tap()

        // The composite runs off the main thread, so the colour lands a beat after the tap.
        expectation(for: NSPredicate(format: "value != %@", "000000"), evaluatedWith: eyedropper)
        waitForExpectations(timeout: 10)

        // Channel thresholds rather than an exact hex, matching how
        // `testColorPanelControlsChangeBrushColorAndPaintedStroke` reads a drawn stroke back: the
        // sampled pixel is a composited brush dab, so it is red without being bit-identical to the
        // red that was typed.
        guard let hex = eyedropper.value as? String, hex.count >= 6,
              let r = Int(hex.prefix(2), radix: 16),
              let g = Int(hex.dropFirst(2).prefix(2), radix: 16),
              let b = Int(hex.dropFirst(4).prefix(2), radix: 16) else {
            return XCTFail("Expected a hex colour on the eyedropper button, got \(String(describing: eyedropper.value))")
        }
        XCTAssertGreaterThan(r, 200, "The pick took the red stroke's colour, got #\(hex)")
        XCTAssertLessThan(g, 80, "…got #\(hex)")
        XCTAssertLessThan(b, 80, "…got #\(hex)")

        XCTAssertFalse(eyedropper.isSelected,
                       "A completed pick hands the canvas back to the previous tool (Tool.eyedropper)")
        XCTAssertTrue(app.buttons["toolbar.brushButton"].isSelected,
                      "…which here is the brush, the tool that was active when the eyedropper was armed")
    }

    /// **The owner's bug, both halves** (2026-08-17): *"Using the eyedropper initiates a brush
    /// stroke. The intended behaviour is that it doesnt, and the brush stroke only is initiated the
    /// next time the pencil taps."*
    ///
    /// The colour side of the eyedropper was never wrong — the owner confirmed the pick was correct
    /// even on a rotated canvas — so this asserts almost nothing about colour. It asserts the two
    /// things they actually reported: the picking touch commits no stroke, and the touch after it
    /// does.
    ///
    /// **The layer's committed vector-stroke count is the signal, and the obvious alternatives are
    /// traps.** The default layer kind is vector, so a committed stroke is one entry in the cel's
    /// display list and `readVectorMarker(...)?.strokes` is an exact count that cannot be argued
    /// with. (`readLayerStrokeCount` is the raster tier's twin and reads 0 forever on a vector layer
    /// — it fails this test's own sanity assertion, which is how it was caught.)
    ///
    ///  * *The undo button* cannot show a delta: creating a canvas already leaves `canUndo` true, so
    ///    there is no disabled baseline to grow from (measured on this simulator, 2026-08-17).
    ///  * *A pixel* looks decisive and is not, and this is worth stating because the first version of
    ///    this test used one and **passed against the unfixed app**. The colour lands while the
    ///    picking touch is still down — that is the whole reason `handleEyedropperPress` has to hold
    ///    the tool revert back — so a stray stroke is painted in the colour that was *just picked*.
    ///    Pick white off bare paper and the bug paints a white stroke on white paper: invisible,
    ///    green, wrong. The count does not care what colour anything is.
    ///
    /// **The picking gesture is a press-and-drag, not a tap**, because a drag is what a stroke
    /// unambiguously is: it crosses `StrokePathFit`'s deviation tolerance, and it holds the touch
    /// down across the pick's off-main-thread composite — the window in which the revert used to
    /// land, which is the second door `handleEyedropperPress` closes. XCUITest cannot synthesise a
    /// pencil, so this is a finger: the same path, with pencil-only drawing off (the default).
    func testTheEyedroppersOwnTouchCommitsNoStrokeAndTheNextTouchDoes() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))

        /// Opens the layer panel, reads the active layer's committed-stroke count, closes it again.
        /// The panel covers the canvas, so it is never left open across a gesture.
        func committedStrokes() -> Int? {
            layersButton.tap()
            defer { layersButton.tap() }
            return readVectorMarker(app, layerIndex: 0)?.strokes
        }

        // One ordinary stroke first: it fixes the baseline at a number rather than at "empty", and it
        // proves in the same breath that a finger drag on this canvas does commit a stroke — without
        // which every later assertion of "no stroke" would be worth nothing.
        drawLine(on: canvas, from: CGVector(dx: 0.35, dy: 0.42), to: CGVector(dx: 0.65, dy: 0.42))
        XCTAssertEqual(committedStrokes(), 1, "Sanity: a plain drag commits exactly one stroke")

        let eyedropper = app.buttons["sideToolbar.eyedropperButton"]
        XCTAssertTrue(eyedropper.waitForExistence(timeout: 5))
        XCTAssertEqual(eyedropper.value as? String, "000000",
                       "Sanity: the brush starts black, and the paper it is about to pick is white")
        eyedropper.tap()
        XCTAssertTrue(eyedropper.isSelected)

        // Down on bare paper clear of that stroke, dragged across it, lifted.
        let start = canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.35, dy: 0.60))
        let end = canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.65, dy: 0.60))
        start.press(forDuration: 0.15, thenDragTo: end, withVelocity: .slow, thenHoldForDuration: 0.1)

        // The pick resolved — the composite is off the main thread, so it lands a beat after the
        // touch — and with it the tool handed itself back.
        expectation(for: NSPredicate(format: "value != %@", "000000"), evaluatedWith: eyedropper)
        waitForExpectations(timeout: 10)
        guard let hex = eyedropper.value as? String, hex.count >= 6,
              let r = Int(hex.prefix(2), radix: 16) else {
            return XCTFail("Expected a hex colour on the eyedropper button, got \(String(describing: eyedropper.value))")
        }
        XCTAssertGreaterThan(r, 200, "The pick took the white paper's colour, got #\(hex)")
        XCTAssertFalse(eyedropper.isSelected,
                       "A completed pick reverts to the previous tool (Tool.eyedropper)")

        // The assertion this test exists for.
        XCTAssertEqual(committedStrokes(), 1, """
            The eyedropper's own touch committed a stroke. That is the owner's report of 2026-08-17: \
            `CanvasView`'s `shouldInteract` left the active layer's host interactive because its tool \
            clause was a hand-maintained exclusion list that never grew to include the eyedropper, so \
            the picking touch reached the layer's StrokeGestureRecognizer as well as the eyedropper's \
            own. See `Tool.paintsOnCanvas` and `ToolLogicTests`.
            """)

        // …and the touch after it does paint — the half of the report that is a requirement rather
        // than a bug, and the proof that the count above was held down by the fix rather than by the
        // canvas having stopped accepting strokes altogether.
        drawLine(on: canvas, from: CGVector(dx: 0.35, dy: 0.48), to: CGVector(dx: 0.65, dy: 0.48))
        XCTAssertEqual(committedStrokes(), 2, """
            The touch after the pick must draw. If this fails while the assertion above passes, the \
            revert never happened and the artist is stranded in the eyedropper.
            """)
    }

    /// Task: the eraser gets its own settings dropdown (shape/size/opacity/dynamics), functioning like
    /// the brush tool but erasing instead of painting. Also exercises the drawing-dismisses-menu fix
    /// for the eraser specifically: opening its menu then dragging over existing ink should both close
    /// the menu and actually erase.
    func testEraserHasOwnPanelAndErasesStroke() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let p = safeOutsideCornerPoint(canvas)
        let q = CGVector(dx: p.dx + 0.12, dy: p.dy)
        drawLine(on: canvas, from: p, to: q)
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: p.dx + 0.06, dy: p.dy)), "Sanity: the stroke should be drawn before erasing it")

        let eraserButton = app.buttons["toolbar.eraserButton"]
        XCTAssertTrue(eraserButton.waitForExistence(timeout: 5))
        eraserButton.tap() // First tap: select the eraser tool only.
        XCTAssertTrue(eraserButton.isSelected)
        XCTAssertFalse(brushIsSelected(app), "Brush must stop reading as active once the eraser is selected")

        eraserButton.tap() // Second tap: open its brushes menu.
        XCTAssertTrue(app.otherElements["eraserPanel.library"].waitForExistence(timeout: 5),
                      "Eraser menu should be open, mirroring the brush's")
        // Widen it so the drag below fully covers the stroke. The Size slider is behind the editor's
        // door now (BRUSH.md §2.20); `setBrushSize` walks §2.20's second tap to reach it.
        setBrushSize(app, tool: "eraser", normalized: 1.0)
        let sizeSlider = app.sliders["eraserPanel.sizeSlider"]

        drawLine(on: canvas, from: p, to: q) // Drag back over the same stroke to erase it.
        XCTAssertTrue(sizeSlider.waitForNonExistence(timeout: 3), "Continuing to erase should dismiss the open eraser menu")
        XCTAssertTrue(isWhitish(rgbaPixel(of: canvas, dx: p.dx + 0.06, dy: p.dy)), "Erasing over the stroke should restore blank paper")
    }

    /// Regression test for the "ghost layer" bug: a fill used to land in `Cel.bakedImage`, a tier the
    /// eraser (which only ever stamps `Cel.raster`) could never reach, so a filled region was
    /// permanently un-eraseable. Fill now lands directly in `raster` (see
    /// `CanvasManager.registerUndoableCelChange`'s doc comment), so this must actually work.
    func testEraserCanEraseAFilledSelection() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        app.buttons["toolbar.selectButton"].tap()
        let rectangleMode = app.buttons["selectPanel.mode.rectangle"]
        XCTAssertTrue(rectangleMode.waitForExistence(timeout: 5))
        rectangleMode.tap()
        dragOnCanvas(app, from: CGVector(dx: 0.55, dy: 0.25), to: CGVector(dx: 0.78, dy: 0.42))

        let fillButton = app.buttons["selectPanel.fillButton"]
        XCTAssertTrue(fillButton.waitForExistence(timeout: 5))
        fillButton.tap()

        // Deselect before erasing: fillSelection() deliberately leaves the selection active (matching
        // Fill's normal behavior), and with it active "paint outside selection" stays denied by
        // default — clip the eraser stroke to a region matching the fill exactly is a separate,
        // already-covered concern (testDenyOutsideSelectionClipsStrokeUntilToggledOn), not what this
        // regression test is isolating.
        let deselectButton = app.buttons["selectPanel.deselectButton"]
        XCTAssertTrue(deselectButton.waitForExistence(timeout: 5))
        deselectButton.tap()

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: 0.66, dy: 0.33)), "Sanity: the fill should be visible before erasing it")

        let eraserButton = app.buttons["toolbar.eraserButton"]
        XCTAssertTrue(eraserButton.waitForExistence(timeout: 5))
        eraserButton.tap() // select
        setBrushSize(app, tool: "eraser", normalized: 1.0) // menu, second tap, Size slider

        drawLine(on: canvas, from: CGVector(dx: 0.55, dy: 0.33), to: CGVector(dx: 0.78, dy: 0.33))
        XCTAssertTrue(isWhitish(rgbaPixel(of: canvas, dx: 0.66, dy: 0.33)), "Erasing over the filled region should restore blank paper")
    }

    /// Regression test for the "ghost layer" bug: committing a Move used to wipe `Cel.raster` and put
    /// the moved content in `Cel.bakedImage` instead, so it became permanently un-eraseable (and any
    /// stroke drawn afterward was the only thing the eraser could still touch). Move now folds its
    /// result back into `raster`.
    func testEraserCanEraseContentAfterMoveCommits() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        // Raster, for the same reason as `testMoveWithNoSelectionLiftsWholeLayerAndCommits`: the
        // lift-and-bake path this exercises exists only on a raster layer.
        addRasterLayer(app)

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let p = safeOutsideCornerPoint(canvas)
        let q = CGVector(dx: p.dx + 0.12, dy: p.dy)
        drawLine(on: canvas, from: p, to: q)
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: p.dx + 0.06, dy: p.dy)), "Sanity: the stroke should be drawn before moving it")

        app.buttons["toolbar.moveButton"].tap()
        let doneButton = app.buttons["moveBar.doneButton"]
        XCTAssertTrue(doneButton.waitForExistence(timeout: 10), "Move with no selection should float the whole layer")
        doneButton.tap() // commit in place — no drag needed to exercise the bake path

        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: p.dx + 0.06, dy: p.dy)), "Sanity: the stroke should still be visible right after committing the move")

        let eraserButton = app.buttons["toolbar.eraserButton"]
        XCTAssertTrue(eraserButton.waitForExistence(timeout: 5))
        eraserButton.tap() // select
        setBrushSize(app, tool: "eraser", normalized: 1.0) // menu, second tap, Size slider

        drawLine(on: canvas, from: p, to: q)
        XCTAssertTrue(isWhitish(rgbaPixel(of: canvas, dx: p.dx + 0.06, dy: p.dy)), "Erasing after a committed Move should reach the moved content")
    }

}
