// Generated by a mechanical split of the original monolithic PaintSoftwareUITests
// class. Test bodies are unchanged; see PaintUITestCase for the shared helpers.
//
// Originally a single ToolsAndSelectionUITests class (424s measured); split into three
// classes below so xcodebuild's per-class parallel distribution doesn't serialize all 14
// tests behind one worker. No shared helpers/setUp/tearDown to move — every test here only
// ever used PaintUITestCase's base-class helpers.

import XCTest

final class ToolPanelsUITests: PaintUITestCase {

    /// Task 3: the fill tool's settings menu only opens on the *second* tap of its icon; the first tap
    /// just selects the tool (so switching tools never pops a menu over the canvas).
    func testFillMenuOpensOnlyOnSecondTap() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let fillButton = app.buttons["toolbar.fillButton"]
        XCTAssertTrue(fillButton.waitForExistence(timeout: 5))

        fillButton.tap() // First tap: select only.
        let menuSlider = app.sliders["fillPanel.gapClosingSlider"] // lives only in the dropdown menu
        XCTAssertFalse(menuSlider.waitForExistence(timeout: 1.5), "First tap should select the fill tool without opening its menu")

        fillButton.tap() // Second tap: open the menu.
        XCTAssertTrue(menuSlider.waitForExistence(timeout: 5), "Second tap on the already-selected fill tool should open its menu")
    }

    /// Task 3: tapping the canvas (anywhere off the toolbar and the open menu) dismisses an open menu.
    func testTappingCanvasDismissesOpenMenu() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let layersButton = app.buttons["toolbar.layersButton"]
        XCTAssertTrue(layersButton.waitForExistence(timeout: 5))
        layersButton.tap()

        let addButton = app.buttons["layerPanel.addButton"]
        XCTAssertTrue(addButton.waitForExistence(timeout: 5), "Layers menu should open")

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        canvas.coordinate(withNormalizedOffset: CGVector(dx: 0.35, dy: 0.6)).tap() // off the menu

        XCTAssertTrue(addButton.waitForNonExistence(timeout: 3), "Tapping off an open menu should dismiss it")
    }

    /// Task 3: the left rail's sliders are Size / Opacity for the brush and swap to Gap Closing /
    /// Threshold / Edge Overlap when the fill tool is active.
    func testLeftRailSlidersSwapWithTool() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        // Default tool is the brush.
        XCTAssertTrue(app.sliders["sideToolbar.brushSizeSlider"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.staticTexts["Size"].exists)
        XCTAssertTrue(app.staticTexts["Opacity"].exists)
        XCTAssertFalse(app.sliders["sideToolbar.gapClosingSlider"].exists)

        app.buttons["toolbar.fillButton"].tap() // select fill

        XCTAssertTrue(app.sliders["sideToolbar.gapClosingSlider"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.sliders["sideToolbar.thresholdSlider"].exists)
        XCTAssertTrue(app.sliders["sideToolbar.edgeOverlapSlider"].exists)
        XCTAssertTrue(app.staticTexts["Gap Closing"].exists)
        XCTAssertTrue(app.staticTexts["Threshold"].exists)
        XCTAssertTrue(app.staticTexts["Edge Overlap"].exists)
        XCTAssertFalse(app.sliders["sideToolbar.brushSizeSlider"].exists)
    }

    /// Task: opening a tool's settings dropdown must not block drawing — continuing to draw should
    /// both dismiss the menu and land the stroke in one motion, instead of the first touch being
    /// silently swallowed and requiring a separate tap to close the menu first.
    func testDrawingWhileBrushMenuOpenDismissesMenuAndDraws() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        // Brush is the default tool, so a single tap opens its settings menu directly.
        let brushButton = app.buttons["toolbar.brushButton"]
        XCTAssertTrue(brushButton.waitForExistence(timeout: 5))
        brushButton.tap()
        let sizeSlider = app.sliders["brushPanel.sizeSlider"]
        XCTAssertTrue(sizeSlider.waitForExistence(timeout: 5), "Brush menu should be open")

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let p = safeOutsideCornerPoint(canvas)
        drawLine(on: canvas, from: p, to: CGVector(dx: p.dx + 0.12, dy: p.dy))

        XCTAssertTrue(sizeSlider.waitForNonExistence(timeout: 3), "Continuing to draw should dismiss the open brush menu")
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: p.dx + 0.06, dy: p.dy)), "The stroke should have actually been drawn, not swallowed by the menu")
    }

    /// Task: brush/eraser/fill/select highlighting must be mutually exclusive — switching to Select
    /// must turn off whichever paint tool's icon was previously highlighted, not show both at once.
    func testSelectingSelectToolStopsHighlightingBrush() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let brushButton = app.buttons["toolbar.brushButton"]
        let selectButton = app.buttons["toolbar.selectButton"]
        XCTAssertTrue(brushButton.waitForExistence(timeout: 5))
        XCTAssertTrue(selectButton.waitForExistence(timeout: 5))

        // Brush is the default tool.
        XCTAssertTrue(brushButton.isSelected, "Brush should read as the active tool by default")
        XCTAssertFalse(selectButton.isSelected)

        selectButton.tap()
        XCTAssertTrue(selectButton.isSelected, "Select should now read as active")
        XCTAssertFalse(brushButton.isSelected, "Brush must stop reading as active once Select is engaged — only one tool highlighted at a time")

        // Switching back to Brush should restore exclusivity the other way.
        brushButton.tap()
        XCTAssertTrue(brushButton.isSelected)
        XCTAssertFalse(selectButton.isSelected)
    }

}

final class SelectionAndMoveUITests: PaintUITestCase {

    /// Rectangle-select a region, then Fill it — the fill should land directly in the raster tier
    /// (Cel.raster), the same tier the eraser stamps into, not a separate Cel.bakedImage layer the
    /// eraser can never reach (see `CanvasManager.registerUndoableCelChange`'s doc comment).
    func testRectangleSelectThenFillBakesPixels() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        // On a vector layer `fillSelection` correctly adds a `VectorFillElement` instead
        // (SelectionModels.swift), so the raster tier this test is about is only reachable on a
        // raster layer — which is no longer what a new canvas starts on (PLAN §8).
        addRasterLayer(app)

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 1), false, "A fresh layer shouldn't have baked content yet")
        app.buttons["toolbar.layersButton"].tap() // close panel so it can't cover the canvas

        app.buttons["toolbar.selectButton"].tap()
        let rectangleMode = app.buttons["selectPanel.mode.rectangle"]
        XCTAssertTrue(rectangleMode.waitForExistence(timeout: 5))
        rectangleMode.tap()

        // Draw the selection in the upper portion of the canvas, clear of the Select menu's bar
        // (which docks at the bottom, covering the lower portion of the screen).
        dragOnCanvas(app, from: CGVector(dx: 0.55, dy: 0.25), to: CGVector(dx: 0.78, dy: 0.42))

        let fillButton = app.buttons["selectPanel.fillButton"]
        XCTAssertTrue(fillButton.waitForExistence(timeout: 5))
        fillButton.tap()

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 1), false, "Filling should land in the raster tier, not a separate baked-image tier")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 1), 1, "Filling the selection should register as raster content, so the eraser can reach it")
    }

    /// Rectangle-select, Duplicate: a new layer should appear immediately (holding the floating
    /// piece), and the Move bottom bar's Done button should commit it into that new layer's raster
    /// tier, without touching the source layer.
    func testDuplicateSelectionCreatesNewLayerAndCommits() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        app.buttons["toolbar.selectButton"].tap()
        let rectangleMode = app.buttons["selectPanel.mode.rectangle"]
        XCTAssertTrue(rectangleMode.waitForExistence(timeout: 5))
        rectangleMode.tap()

        // Draw in the upper portion of the canvas, clear of the Select menu's bottom-docked bar (see
        // the fill test).
        dragOnCanvas(app, from: CGVector(dx: 0.55, dy: 0.25), to: CGVector(dx: 0.78, dy: 0.42))

        let duplicateButton = app.buttons["selectPanel.duplicateButton"]
        XCTAssertTrue(duplicateButton.waitForExistence(timeout: 5))
        duplicateButton.tap()

        let doneButton = app.buttons["moveBar.doneButton"]
        XCTAssertTrue(doneButton.waitForExistence(timeout: 5), "Duplicate should immediately float the copy, showing the Move bottom bar")
        doneButton.tap()

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertTrue(app.staticTexts["layerPanel.row.1"].waitForExistence(timeout: 5), "Duplicate should have inserted a second layer")
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 1), false, "Committing should land the duplicated piece in the raster tier, not a separate baked-image tier")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 1), 1, "The duplicated piece should register as raster content on the new layer")
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 0), false, "Duplicate must not modify the source layer")
    }

    /// A brush stroke that crosses outside the active selection is clipped to it by default ("Paint
    /// Outside Selection" starts denied) — the paint outside the marching ants is discarded, reverting
    /// to blank paper — and flipping that toggle on lets the same stroke shape paint past the boundary.
    func testDenyOutsideSelectionClipsStrokeUntilToggledOn() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        app.buttons["toolbar.selectButton"].tap()
        let rectangleMode = app.buttons["selectPanel.mode.rectangle"]
        XCTAssertTrue(rectangleMode.waitForExistence(timeout: 5))
        rectangleMode.tap()

        // A rectangle selection in the upper-left quadrant; the probe points below straddle its right
        // edge (dx: 0.55) so one lands inside and one lands clearly outside.
        dragOnCanvas(app, from: CGVector(dx: 0.3, dy: 0.2), to: CGVector(dx: 0.55, dy: 0.35))

        let allowToggle = app.buttons["selectPanel.allowOutsideToggle"]
        XCTAssertTrue(allowToggle.waitForExistence(timeout: 5))

        // Switch to the brush tool — exercises the Select-exit fix (TopToolbar's two-stage tap helpers):
        // this must land on plain drawing (activePanel == .none), not pop the brush settings panel open.
        app.buttons["toolbar.brushButton"].tap()
        XCTAssertFalse(app.buttons["selectPanel.mode.rectangle"].exists, "Selecting the brush tool should fully exit Select, not just unhighlight its icon")

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        // A horizontal stroke starting inside the selection (dx 0.4) and ending well outside it (dx 0.75).
        dragOnCanvas(app, from: CGVector(dx: 0.4, dy: 0.275), to: CGVector(dx: 0.75, dy: 0.275))

        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: 0.45, dy: 0.275)), "Paint inside the selection should land normally")
        XCTAssertTrue(isWhitish(rgbaPixel(of: canvas, dx: 0.65, dy: 0.275)), "Paint outside the selection should be discarded while outside interaction is denied")

        // Flip the toggle on and repeat the same stroke — this time it should reach past the boundary.
        app.buttons["toolbar.selectButton"].tap()
        XCTAssertTrue(allowToggle.waitForExistence(timeout: 5))
        allowToggle.tap()

        app.buttons["toolbar.brushButton"].tap()
        dragOnCanvas(app, from: CGVector(dx: 0.4, dy: 0.275), to: CGVector(dx: 0.75, dy: 0.275))
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: 0.65, dy: 0.275)), "With outside interaction allowed, the same stroke should now paint past the selection boundary")
    }

    /// With no active selection, Move lifts the whole current layer; committing bakes it back into
    /// the raster tier (not a separate Cel.bakedImage layer — see `registerUndoableCelChange`'s doc
    /// comment) so the moved content stays reachable by the eraser afterwards.
    func testMoveWithNoSelectionLiftsWholeLayerAndCommits() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        // The floating-piece path is raster-only by design: `TopToolbar.toggleMove` sends a vector
        // layer down `isVectorTransforming` instead, which writes `VectorCanvas.transform` and never
        // shows the Move bottom bar. Vector is the default kind now (PLAN §8), so this test has to
        // ask for the raster layer whose lift-and-bake it is about.
        addRasterLayer(app)

        dragOnCanvas(app, from: CGVector(dx: 0.3, dy: 0.3), to: CGVector(dx: 0.5, dy: 0.3))

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 1), 1, "Setup: the stroke should have landed as one PencilKit stroke")
        app.buttons["toolbar.layersButton"].tap() // close panel so it can't cover the canvas

        app.buttons["toolbar.moveButton"].tap()
        let doneButton = app.buttons["moveBar.doneButton"]
        // beginMove() rasterizes the whole cel synchronously via PixelOps.rasterize (plain Core
        // Graphics, no PencilKit involved since the Session 11 engine rewrite), so this should be
        // near-instant; kept in line with the suite's other generous waits.
        XCTAssertTrue(doneButton.waitForExistence(timeout: 10), "Move with no selection should float the whole layer")
        doneButton.tap()

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readHasBakedImage(app, layerIndex: 1), false, "Committing the move should land in the raster tier, not a separate baked-image tier")
        XCTAssertEqual(readLayerStrokeCount(app, layerIndex: 1), 1, "The moved content should still register as raster content, not disappear from the tier the eraser reaches")
    }

}

final class EraserAndPersistenceUITests: PaintUITestCase {

    /// Save -> relaunch -> reload round trip, exercising the real `ProjectStore.save`/`load` path
    /// (not just the manifest struct in isolation — this UI test target has no `@testable import`
    /// access to call those directly, confirmed by a link failure when tried). Draws a stroke,
    /// returns to the gallery (via the toolbar's gallery button — its SwiftUI `Image(systemName:)`
    /// gets "square.grid.2x2" as its accessibility identifier automatically, since TopToolbar
    /// doesn't set one explicitly), force-quits and relaunches the whole app (so this genuinely
    /// re-reads from disk, not just in-memory state), reopens the one saved project from the
    /// gallery, and asserts the stroke (and therefore the layer/cel raster data) survived.
    ///
    /// This also serves as a build-time-only regression check for the manifest schema additions
    /// (`LayerManifest.kind`, `ProjectManifest.selectedBrush`/`customBrushes`): every save now
    /// encodes those fields and every load decodes them, so a save/load cycle silently failing to
    /// decode (e.g. a typo'd CodingKeys case) would make this test hang or fail outright rather
    /// than passing.
    ///
    /// It now *does* cover a non-raster `LayerKind` end-to-end, which it could not when it was
    /// written: vector is the default layer kind (PLAN §8), so the stroke below is geometry, and a
    /// round trip that survives is `LayerManifest.kind` plus the whole vector payload surviving with
    /// it. Reading the vector marker rather than `readLayerStrokeCount` is what makes that real —
    /// the raster tier stays empty on a vector layer, so the old reader would now assert nothing.
    /// A non-default *brush* is still out of reach here and still covered at the `Codable` level.
    func testSaveAndReloadPersistsStrokesAcrossAppRelaunch() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        dragOnCanvas(app, from: CGVector(dx: 0.3, dy: 0.3), to: CGVector(dx: 0.5, dy: 0.3))

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 1, "Setup: the stroke should have landed before saving")
        app.buttons["toolbar.layersButton"].tap() // close panel

        // Back to gallery, which triggers ContentView.saveIfNeeded() -> ProjectStore.save.
        let galleryButton = app.buttons["square.grid.2x2"]
        XCTAssertTrue(galleryButton.waitForExistence(timeout: 5))
        galleryButton.tap()

        let projectTile = app.staticTexts.matching(NSPredicate(format: "label == %@", "Untitled")).firstMatch
        XCTAssertTrue(projectTile.waitForExistence(timeout: 5), "Setup: the saved project should show up in the gallery")

        // Force-quit and relaunch the whole app so reopening the project genuinely re-reads the
        // manifest + PNGs from disk (ProjectStore.load) instead of reusing in-memory CanvasManager
        // state left over from the editor.
        app.terminate()
        app.launch()
        let reopenedTile = app.staticTexts.matching(NSPredicate(format: "label == %@", "Untitled")).firstMatch
        XCTAssertTrue(reopenedTile.waitForExistence(timeout: 10), "Project should still be listed after relaunch")
        reopenedTile.tap()

        let frameLabel = app.staticTexts["timeline.frameLabel"]
        XCTAssertTrue(frameLabel.waitForExistence(timeout: 10), "Reopening the project should land back in the editor")

        app.buttons["toolbar.layersButton"].tap()
        XCTAssertEqual(readVectorMarker(app, layerIndex: 0)?.strokes, 1, "Stroke drawn before saving should survive a save -> relaunch -> load round trip")
    }

    /// Exercises all three color controls (hue bar, SV square, hex field) and confirms each one
    /// actually lands on `canvasManager.brushColor`: after dragging the hue bar and SV square to a
    /// known corner (full saturation/brightness at a chosen hue), reads the hex field back to
    /// confirm it reactively shows the resulting color, then types a different hex value in
    /// directly and draws a stroke, pixel-sampling it to confirm the *drawn* color matches what was
    /// typed — the strongest possible check that brushColor actually changed and reached the canvas,
    /// not just some intermediate SwiftUI state.
    func testColorPanelControlsChangeBrushColorAndPaintedStroke() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let colorButton = app.buttons["toolbar.colorButton"]
        XCTAssertTrue(colorButton.waitForExistence(timeout: 5))
        colorButton.tap()

        // Hue bar: drag to the far left (hue 0 == red).
        let hueSlider = app.otherElements["colorPanel.hueSlider"]
        XCTAssertTrue(hueSlider.waitForExistence(timeout: 5))
        dragWithinElement(hueSlider, from: CGVector(dx: 0.5, dy: 0.5), to: CGVector(dx: 0.0, dy: 0.5))

        // SV square: drag to the top-right corner (saturation 1, brightness 1) so the result is
        // pure, fully-saturated red rather than some in-between shade.
        let svSquare = app.otherElements["colorPanel.svSquare"]
        XCTAssertTrue(svSquare.waitForExistence(timeout: 5))
        dragWithinElement(svSquare, from: CGVector(dx: 0.5, dy: 0.5), to: CGVector(dx: 1.0, dy: 0.0))

        // The hex field should reactively reflect that as pure red, confirming the hue bar/SV
        // square drags actually updated brushColor (not just their own local indicator).
        let hexField = app.textFields["colorPanel.hexField"]
        XCTAssertTrue(hexField.waitForExistence(timeout: 5))
        let hexAfterDrag = hexField.value as? String
        XCTAssertEqual(hexAfterDrag?.uppercased(), "FF0000", "Dragging hue to red and SV to full saturation/brightness should show FF0000 in the hex field, got \(String(describing: hexAfterDrag))")

        // Now drive the color from the hex field directly, to a distinct color (pure green).
        hexField.tap()
        // Clear the field's existing text ("FF0000") with backspaces before typing the new value —
        // XCUIElement has no built-in "select all and replace", so this deletes character-by-character.
        if let currentValue = hexField.value as? String {
            hexField.typeText(String(repeating: "\u{8}", count: currentValue.count))
        }
        hexField.typeText("00FF00")
        app.keyboards.buttons["Return"].tap()

        colorButton.tap() // Close the panel so it can't cover the canvas.

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        drawLine(on: canvas, from: CGVector(dx: 0.3, dy: 0.5), to: CGVector(dx: 0.7, dy: 0.5))

        guard let pixel = rgbaPixel(of: canvas, dx: 0.5, dy: 0.5) else {
            XCTFail("Could not sample the drawn stroke's pixel color")
            return
        }
        XCTAssertGreaterThan(pixel.g, 200, "Stroke drawn after setting hex to 00FF00 should be green-dominant, got \(pixel)")
        XCTAssertLessThan(pixel.r, 80, "Stroke drawn after setting hex to 00FF00 should have low red, got \(pixel)")
        XCTAssertLessThan(pixel.b, 80, "Stroke drawn after setting hex to 00FF00 should have low blue, got \(pixel)")
    }

    /// Task: the eraser gets its own settings dropdown (shape/size/opacity/dynamics), functioning like
    /// the brush tool but erasing instead of painting. Also exercises the drawing-dismisses-menu fix
    /// for the eraser specifically: opening its menu then dragging over existing ink should both close
    /// the menu and actually erase.
    func testEraserHasOwnPanelAndErasesStroke() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let p = safeOutsideCornerPoint(canvas)
        let q = CGVector(dx: p.dx + 0.12, dy: p.dy)
        drawLine(on: canvas, from: p, to: q)
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: p.dx + 0.06, dy: p.dy)), "Sanity: the stroke should be drawn before erasing it")

        let eraserButton = app.buttons["toolbar.eraserButton"]
        XCTAssertTrue(eraserButton.waitForExistence(timeout: 5))
        eraserButton.tap() // First tap: select the eraser tool only.
        XCTAssertTrue(eraserButton.isSelected)
        XCTAssertFalse(brushIsSelected(app), "Brush must stop reading as active once the eraser is selected")

        eraserButton.tap() // Second tap: open its settings menu.
        let sizeSlider = app.sliders["eraserPanel.sizeSlider"]
        XCTAssertTrue(sizeSlider.waitForExistence(timeout: 5), "Eraser menu should be open, mirroring the brush's")
        sizeSlider.adjust(toNormalizedSliderPosition: 1.0) // Widen it so the drag below fully covers the stroke.

        drawLine(on: canvas, from: p, to: q) // Drag back over the same stroke to erase it.
        XCTAssertTrue(sizeSlider.waitForNonExistence(timeout: 3), "Continuing to erase should dismiss the open eraser menu")
        XCTAssertTrue(isWhitish(rgbaPixel(of: canvas, dx: p.dx + 0.06, dy: p.dy)), "Erasing over the stroke should restore blank paper")
    }

    /// Regression test for the "ghost layer" bug: a fill used to land in `Cel.bakedImage`, a tier the
    /// eraser (which only ever stamps `Cel.raster`) could never reach, so a filled region was
    /// permanently un-eraseable. Fill now lands directly in `raster` (see
    /// `CanvasManager.registerUndoableCelChange`'s doc comment), so this must actually work.
    func testEraserCanEraseAFilledSelection() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))

        app.buttons["toolbar.selectButton"].tap()
        let rectangleMode = app.buttons["selectPanel.mode.rectangle"]
        XCTAssertTrue(rectangleMode.waitForExistence(timeout: 5))
        rectangleMode.tap()
        dragOnCanvas(app, from: CGVector(dx: 0.55, dy: 0.25), to: CGVector(dx: 0.78, dy: 0.42))

        let fillButton = app.buttons["selectPanel.fillButton"]
        XCTAssertTrue(fillButton.waitForExistence(timeout: 5))
        fillButton.tap()

        // Deselect before erasing: fillSelection() deliberately leaves the selection active (matching
        // Fill's normal behavior), and with it active "paint outside selection" stays denied by
        // default — clip the eraser stroke to a region matching the fill exactly is a separate,
        // already-covered concern (testDenyOutsideSelectionClipsStrokeUntilToggledOn), not what this
        // regression test is isolating.
        let deselectButton = app.buttons["selectPanel.deselectButton"]
        XCTAssertTrue(deselectButton.waitForExistence(timeout: 5))
        deselectButton.tap()

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: 0.66, dy: 0.33)), "Sanity: the fill should be visible before erasing it")

        let eraserButton = app.buttons["toolbar.eraserButton"]
        XCTAssertTrue(eraserButton.waitForExistence(timeout: 5))
        eraserButton.tap() // select
        eraserButton.tap() // open settings
        let sizeSlider = app.sliders["eraserPanel.sizeSlider"]
        XCTAssertTrue(sizeSlider.waitForExistence(timeout: 5))
        sizeSlider.adjust(toNormalizedSliderPosition: 1.0)

        drawLine(on: canvas, from: CGVector(dx: 0.55, dy: 0.33), to: CGVector(dx: 0.78, dy: 0.33))
        XCTAssertTrue(isWhitish(rgbaPixel(of: canvas, dx: 0.66, dy: 0.33)), "Erasing over the filled region should restore blank paper")
    }

    /// Regression test for the "ghost layer" bug: committing a Move used to wipe `Cel.raster` and put
    /// the moved content in `Cel.bakedImage` instead, so it became permanently un-eraseable (and any
    /// stroke drawn afterward was the only thing the eraser could still touch). Move now folds its
    /// result back into `raster`.
    func testEraserCanEraseContentAfterMoveCommits() throws {
        let app = XCUIApplication()
        XCTAssertTrue(launchIntoEditor(app))
        // Raster, for the same reason as `testMoveWithNoSelectionLiftsWholeLayerAndCommits`: the
        // lift-and-bake path this exercises exists only on a raster layer.
        addRasterLayer(app)

        let canvas = app.otherElements["canvas.host"]
        XCTAssertTrue(canvas.waitForExistence(timeout: 5))
        let p = safeOutsideCornerPoint(canvas)
        let q = CGVector(dx: p.dx + 0.12, dy: p.dy)
        drawLine(on: canvas, from: p, to: q)
        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: p.dx + 0.06, dy: p.dy)), "Sanity: the stroke should be drawn before moving it")

        app.buttons["toolbar.moveButton"].tap()
        let doneButton = app.buttons["moveBar.doneButton"]
        XCTAssertTrue(doneButton.waitForExistence(timeout: 10), "Move with no selection should float the whole layer")
        doneButton.tap() // commit in place — no drag needed to exercise the bake path

        XCTAssertFalse(isWhitish(rgbaPixel(of: canvas, dx: p.dx + 0.06, dy: p.dy)), "Sanity: the stroke should still be visible right after committing the move")

        let eraserButton = app.buttons["toolbar.eraserButton"]
        XCTAssertTrue(eraserButton.waitForExistence(timeout: 5))
        eraserButton.tap() // select
        eraserButton.tap() // open settings
        let sizeSlider = app.sliders["eraserPanel.sizeSlider"]
        XCTAssertTrue(sizeSlider.waitForExistence(timeout: 5))
        sizeSlider.adjust(toNormalizedSliderPosition: 1.0)

        drawLine(on: canvas, from: p, to: q)
        XCTAssertTrue(isWhitish(rgbaPixel(of: canvas, dx: p.dx + 0.06, dy: p.dy)), "Erasing after a committed Move should reach the moved content")
    }

}
