import AVFoundation
import XCTest
import UIKit

/// Pure-logic tests for `VideoFrameReader` and `VideoFrameSource` — VIDEO.md stage 3's decoder.
///
/// **Every clip here is generated by `CanvasFixture.writeGreyClip` at test time**, which is the
/// whole reason these tests can say anything. A committed sample clip could only ever prove that
/// *something* decoded; a clip whose frames are flat greys at known levels lets a test name the
/// frame that came back, which is what §4.3 is actually a claim about.
///
/// **The claims, and each one is about the playhead rather than about AVFoundation:**
///
/// 1. Every source frame comes back as itself, addressed by the timestamp the *file* carries.
/// 2. A forward scrub across a whole clip tears the pipe down **once** — §5's whole design.
/// 3. A backward step tears it down again, and that is the cost §5 says this feature owns.
/// 4. Nearest means nearest, with a tie taking the later frame, because `VideoFrameMap`'s
///    arithmetic rounds that way and the two halves of §4.3 must not disagree.
/// 5. Two document instants inside one source frame are **one** decode, because the ring is keyed by
///    the source frame's own timestamp rather than by the instant that was asked for.
@MainActor
final class VideoFrameReaderLogicTests: XCTestCase {

    /// Six levels 42 apart. `FrameExportLogicTests` measures a flat grey surviving one H.264 BT.709
    /// round trip within 14, so nearest-in-palette over this spacing cannot name the wrong frame.
    private static let levels: [UInt8] = [30, 72, 114, 156, 198, 240]

    private var directory: URL!

    override func setUpWithError() throws {
        directory = FileManager.default.temporaryDirectory
            .appendingPathComponent("video-reader-tests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: directory)
        directory = nil
    }

    // MARK: - Fixtures

    private func clip(fps: Int = 6, levels: [UInt8] = VideoFrameReaderLogicTests.levels,
                      named name: String = "clip.mp4") throws -> URL {
        let url = directory.appendingPathComponent(name)
        try CanvasFixture.writeGreyClip(levels: levels, fps: fps, side: 64, to: url)
        return url
    }

    /// Which frame of the palette a decoded frame is.
    private func index(of frame: DecodedFrame, in levels: [UInt8]) -> Int {
        CanvasFixture.nearestLevelIndex(frame.pixels[0], in: levels)
    }

    // MARK: - Claim 1: a frame comes back as itself

    func testEverySourceFrameComesBackAsTheFrameItIs() throws {
        let url = try clip()
        let stamps = CanvasFixture.clipTimestamps(url)
        XCTAssertEqual(stamps.count, Self.levels.count, "The fixture should hold six frames.")
        let reader = try XCTUnwrap(VideoFrameReader(url: url), "The fixture should open.")

        for (expected, stamp) in stamps.enumerated() {
            XCTAssertEqual(reader.locate(stamp), stamp,
                           "Asking for a frame's own timestamp must land on that frame.")
            let frame = try XCTUnwrap(reader.currentFrame())
            XCTAssertEqual(frame.width, 64)
            XCTAssertEqual(frame.height, 64)
            XCTAssertEqual(index(of: frame, in: Self.levels), expected,
                           "Source frame \(expected) came back as \(index(of: frame, in: Self.levels)).")
        }
    }

    /// **The size and rate an import reads off the asset**, without which stage 4 cannot place a
    /// rectangle and stage 6 cannot offer §2.3's frame-for-frame setting.
    func testTheReaderReportsTheAssetsOwnSizeAndRate() throws {
        let url = try clip(fps: 6)
        let reader = try XCTUnwrap(VideoFrameReader(url: url))
        XCTAssertEqual(reader.info.decodedSize, CGSize(width: 64, height: 64))
        XCTAssertEqual(reader.info.displaySize, CGSize(width: 64, height: 64),
                       "An unrotated clip displays at the size it decodes at.")
        XCTAssertEqual(reader.info.nominalFrameRate, 6, accuracy: 0.5)
        XCTAssertEqual(reader.info.duration.seconds, 1, accuracy: 0.2,
                       "Six frames at 6 fps is a second of footage.")
    }

    /// A file that is not there, and a file that is not a video, are both nil rather than a trap.
    /// The first is the missing-asset path `ProjectStore` already degrades through; the second is
    /// what `VideoElementLogicTests`' own fixture is, and it must not become a crash now that
    /// something opens it.
    func testAnAssetThatWillNotOpenIsNilRatherThanACrash() throws {
        XCTAssertNil(VideoFrameReader(url: directory.appendingPathComponent("absent.mp4")))
        let notAVideo = directory.appendingPathComponent("prose.mov")
        try Data("not a video, and stage 3 does ask".utf8).write(to: notAVideo)
        XCTAssertNil(VideoFrameReader(url: notAVideo))
        XCTAssertNil(VideoFrameSource().frame(assetURL: notAVideo, at: .zero),
                     "A source that will not open answers nil, and the caller draws the placeholder.")
    }

    // MARK: - Claims 2 and 3: the playhead, and what a backward scrub costs

    /// **§5's design claim, as a number.** Walking a clip forwards is one pipe, however many frames
    /// it holds — the reader keeps its position rather than re-seeking per request.
    ///
    /// `sampleCount` is asserted beside `seekCount` on purpose: a reader that re-decoded from the
    /// head on every request without formally re-seeking would keep `seekCount` at one and would be
    /// doing exactly the work this test exists to say it does not.
    func testAForwardScrubTearsThePipeDownOnce() throws {
        let url = try clip()
        let stamps = CanvasFixture.clipTimestamps(url)
        let reader = try XCTUnwrap(VideoFrameReader(url: url))
        for stamp in stamps { reader.locate(stamp) }
        XCTAssertEqual(reader.seekCount, 1,
                       "Six frames forward is one pipe; \(reader.seekCount) means it re-seeks per frame.")
        XCTAssertLessThanOrEqual(reader.sampleCount, stamps.count + 2,
                                 "A forward walk pulls each sample once, plus the one held ahead.")
    }

    /// **And what going back costs**, which is the one performance question this feature owns (§9).
    /// Stated as a test so the number is written down rather than assumed.
    func testAStepBackwardsRebuildsThePipe() throws {
        let url = try clip()
        let stamps = CanvasFixture.clipTimestamps(url)
        let reader = try XCTUnwrap(VideoFrameReader(url: url))
        for stamp in stamps { reader.locate(stamp) }
        let forward = reader.seekCount

        XCTAssertEqual(reader.locate(stamps[1]), stamps[1], "A backward scrub still lands correctly.")
        XCTAssertEqual(index(of: try XCTUnwrap(reader.currentFrame()), in: Self.levels), 1)
        XCTAssertEqual(reader.seekCount, forward + 1,
                       "Going back is exactly one rebuild — VIDEO.md §5's cost, and no more than it.")

        // And forward again from there is free, which is what makes a scrub that reverses once
        // cost one seek rather than one per frame.
        let after = reader.seekCount
        for stamp in stamps[2...] { reader.locate(stamp) }
        XCTAssertEqual(reader.seekCount, after,
                       "Resuming forwards after a backward step must not re-seek.")
    }

    /// The head of the clip has nothing behind it, so an instant before the first frame is that
    /// frame rather than nil — a block whose crop starts before the footage does shows its head.
    func testAnInstantBeforeTheFirstFrameIsTheFirstFrame() throws {
        let url = try clip()
        let reader = try XCTUnwrap(VideoFrameReader(url: url))
        XCTAssertNotNil(reader.locate(CMTime(value: -5, timescale: 600)))
        XCTAssertEqual(index(of: try XCTUnwrap(reader.currentFrame()), in: Self.levels), 0)
    }

    /// And the tail has nothing ahead of it, so an instant past the end holds the last frame. That
    /// is what `VideoFrameMap`'s clamp produces at the end of a crop and what a block longer than
    /// its footage shows.
    func testAnInstantPastTheEndIsTheLastFrame() throws {
        let url = try clip()
        let reader = try XCTUnwrap(VideoFrameReader(url: url))
        XCTAssertNotNil(reader.locate(CMTime(seconds: 60, preferredTimescale: 600)))
        XCTAssertEqual(index(of: try XCTUnwrap(reader.currentFrame()), in: Self.levels),
                       Self.levels.count - 1)
    }

    // MARK: - Claim 4: nearest is nearest

    /// **Nearest, not "the frame currently showing".** An instant 60% of the way from frame 2 to
    /// frame 3 is frame 3. A player would answer 2, and §4.3 says nearest — the difference is a bias
    /// of up to a whole source frame on every frame of a resampled clip.
    ///
    /// Built from the file's own timestamps rather than from `index / fps`, so it is a claim about
    /// the reader and not about arithmetic the test did itself.
    func testAnInstantNearerTheNextFrameResolvesToTheNextFrame() throws {
        let url = try clip()
        let stamps = CanvasFixture.clipTimestamps(url)
        let reader = try XCTUnwrap(VideoFrameReader(url: url))

        let span = CMTimeSubtract(stamps[3], stamps[2]).seconds
        let justPastTheMiddle = CMTimeAdd(stamps[2], CMTime(seconds: span * 0.6,
                                                            preferredTimescale: 100_000))
        XCTAssertEqual(reader.locate(justPastTheMiddle), stamps[3])
        XCTAssertEqual(index(of: try XCTUnwrap(reader.currentFrame()), in: Self.levels), 3)

        let justBeforeIt = CMTimeAdd(stamps[2], CMTime(seconds: span * 0.4,
                                                       preferredTimescale: 100_000))
        XCTAssertEqual(reader.locate(justBeforeIt), stamps[2],
                       "And short of the middle it is still the earlier frame.")
    }

    /// A dead-centre instant takes the **later** frame, matching `VideoFrameMap.sourceFrameIndex`'s
    /// round-half-up. 30 fps footage in a 24 fps document lands on this every fifth frame, so the
    /// two halves of §4.3 agreeing about it is not a nicety.
    func testATieTakesTheLaterFrameJustAsTheArithmeticDoes() throws {
        let url = try clip()
        let stamps = CanvasFixture.clipTimestamps(url)
        let reader = try XCTUnwrap(VideoFrameReader(url: url))
        let middle = CMTimeMultiplyByRatio(CMTimeAdd(stamps[1], stamps[2]), multiplier: 1, divisor: 2)
        XCTAssertEqual(reader.locate(middle), stamps[2])

        // The arithmetic's own answer for the same tie, so the two are compared rather than assumed
        // to agree: at 6 fps the midpoint of frames 1 and 2 is 1.5 source frames.
        let time = SourceTime(value: 3, timescale: 12)
        XCTAssertEqual(VideoFrameMap.sourceFrameIndex(at: time, sourceFPS: 6), 2)
    }

    // MARK: - Claim 5: the ring

    /// **Two instants inside one source frame are one decode.** The ring is keyed by the timestamp
    /// the file carries, not by the instant the map asked for, which is what makes a clip played at
    /// half speed cost one decode per source frame rather than two.
    ///
    /// Asserted on resident bytes rather than on a call count, because bytes are what the ring's own
    /// budget is denominated in and a second entry would be visible there.
    func testTwoInstantsInsideOneSourceFrameCostOneDecode() throws {
        let url = try clip()
        let stamps = CanvasFixture.clipTimestamps(url)
        let source = VideoFrameSource()

        let span = CMTimeSubtract(stamps[3], stamps[2])
        let a = try XCTUnwrap(SourceTime(CMTimeAdd(stamps[2],
                                                   CMTimeMultiplyByRatio(span, multiplier: 1, divisor: 8))))
        let b = try XCTUnwrap(SourceTime(CMTimeAdd(stamps[2],
                                                   CMTimeMultiplyByRatio(span, multiplier: 3, divisor: 8))))

        let first = try XCTUnwrap(source.frame(assetURL: url, at: a))
        let second = try XCTUnwrap(source.frame(assetURL: url, at: b))
        XCTAssertEqual(index(of: first, in: Self.levels), 2)
        XCTAssertEqual(index(of: second, in: Self.levels), 2)
        XCTAssertEqual(source.residentBytes, 64 * 64 * 4,
                       "Both instants are source frame 2, so the ring holds one frame and not two.")
    }

    /// The source opens one pipe per asset and keeps it, so two documents (or two layers) showing
    /// one clip share the playhead rather than fighting over it.
    func testOneAssetIsOnePipeHoweverManyTimesItIsAsked() throws {
        let url = try clip()
        let source = VideoFrameSource()
        for _ in 0..<4 { _ = source.frame(assetURL: url, at: .zero) }
        XCTAssertEqual(source.openReaderCount, 1)
        XCTAssertNotNil(source.info(for: url))
    }

    /// A purge drops the pipes and the decoded frames both — a document closing must not leave a
    /// file handle or 64 MB of source frames behind.
    func testPurgeReleasesEveryPipeAndEveryFrame() throws {
        let url = try clip()
        let source = VideoFrameSource()
        XCTAssertNotNil(source.frame(assetURL: url, at: .zero))
        XCTAssertGreaterThan(source.residentBytes, 0)
        source.purge()
        XCTAssertEqual(source.openReaderCount, 0)
        XCTAssertEqual(source.residentBytes, 0)
    }
}
