import UIKit
import CoreGraphics

/// **A tip's alpha mask is square, and that is a ruling rather than an accident of the first
/// asset.** BRUSH.md §3.5's image primitive carries one number for a dab's size, `DabPose` scales
/// it with one multiply, and `StrokeScratch` bounds it with one `abs`. A tip free to be 512×64
/// would put an aspect ratio into all three, and into `BakedDab`, for a shape the artist can
/// express anyway by leaving the mask's margins transparent — which is also what Procreate's
/// square Shape Sources do. `BrushTipImport` letterboxes a non-square PNG into a square mask on the
/// way in; nothing downstream of here ever asks a tip how wide it is.
///
/// The named tips are the ones committed to the app bundle. §12 stage 9 replaces this file's single
/// case with the generated set, and does it by adding cases here — the loader, the cache and the
/// primitive do not move.
enum BuiltInBrushTexture: String, Hashable, CaseIterable {

    /// **The square brush's tip.** A 256×256 straight-alpha RGBA PNG: black throughout, alpha 255
    /// inside an axis-aligned square inset by 2 px, alpha 0 in the 2 px border.
    ///
    /// The border is not padding — it is what a rotated or downscaled draw antialiases *into*.
    /// MEASURED at `.high` interpolation, a 16 pt dab turned 0.4 rad comes back with edge alphas of
    /// 142 and 237 against a saturated core; the same draw from a border-less mask comes back 255
    /// across the whole span, i.e. aliased. 2/256 is 0.78% of the tip, which is 1.6 px at the app's
    /// largest brush (200 pt) and 0.13 px at 16 pt.
    ///
    /// Reproducing it is eleven lines and no dependencies: fill a 256×256 RGBA byte buffer with
    /// `(0, 0, 0, 0)`, set alpha to 255 where `2 <= x < 254 && 2 <= y < 254`, and write it through
    /// `CGImage` + `CGImageDestination` as `CGImageAlphaInfo.last` (straight, not premultiplied).
    ///
    /// **Nothing in §8.6's shipped set names it, and it stays anyway** — it is the specification
    /// every import is normalised against (see `BrushTipImport`), and it is the discriminating
    /// reference `BrushTipGeneratorLogicTests` stamps each generated tip against. A shipped preset
    /// wants bevelled corners and a falloff, which a plain square does not have.
    case square

    // MARK: - §12 stage 9's shipped tips
    //
    // **Every one of these is `BrushTipGenerator`'s output, committed rather than generated at
    // launch** — §12 stage 9's own ruling: *"the generator is a build-time tool whose output is
    // committed, not a runtime cost — a tip is a small alpha bitmap and generating it per launch
    // buys nothing."* The raw value **is** the generator's shape name, so a committed PNG can
    // always be traced back to the twenty lines that drew it and regenerated byte-for-byte;
    // `BrushTipGeneratorLogicTests` is the pin that they still match.
    //
    // They are 256² straight-alpha PNGs at a 2 px transparent border, exactly as `square` is and
    // exactly as `BrushTipImport` normalises an artist's own picture to. ~285 KB in the binary for
    // all eleven.

    /// **Basics ▸ Square.** A 2.5:1 slab, a 0.20 chamfer, and a falloff band that matches Opaque
    /// Round's own — the owner's *"only falls off in the very edges"*. Carried at `angle.base 0.25`
    /// with `directionFollow 1`, so its long side is perpendicular to the travel.
    case squareBevelWide = "square-bevel-wide"

    /// **Basics ▸ Messy Flat.** The same slab with its *ends* torn, faded and combed. The comb runs
    /// across the mask's `u`, which is the across-stroke axis for a nib held at a quarter turn — see
    /// `BrushTipGenerator.comb`, which is where round two had it the other way round.
    case flatMessyEndsDirty = "flat-messy-ends-dirty"

    /// **Sketching ▸ Pencil Hard.** A tight irregular nib under a hard-thresholded mid-frequency
    /// grain. §8.4's exempt case: interior pits are not filled in by a neighbour's boundary.
    case pencilHard = "pencil-hard"

    /// **Sketching ▸ Pencil Soft.** A wider nib whose grain modulates alpha instead of punching it,
    /// which is what makes it a smear rather than a tooth.
    case pencilSoft = "pencil-soft"

    /// **Sketching ▸ Pencil Blunt.** The worn nib with one side ground flat. **This is the mask
    /// §8.4's boundary paragraph was written from** — the owner read its sharp cutoff off the first
    /// contact sheet and named it as what makes a randomised dab blotchy.
    case pencilBlunt = "pencil-blunt"

    /// **Sketching ▸ Pencil Textured.** Coarse pits, drawn to be stamped at a wide spacing so they
    /// survive into the stroke.
    case pencilTextured = "pencil-textured"

    /// **Inking ▸ Brush Pen.** A teardrop lying along the travel, blunter at the trailing end.
    case penBrush = "pen-brush"

    /// **Inking ▸ Rough Ink.** The grossly asymmetric triangular blob the owner named. Useless
    /// without `angle.jitter` and vice versa — §8.4's boundary paragraph is that pair.
    case roughInkTriangle = "rough-ink-triangle"

    /// **Painting ▸ Painterly.** A squarish blotchy nib with a speckled interior and broken edges,
    /// stamped at spacing 0.095 so its pixels are seen one dab at a time.
    case paintDryLoad = "paint-dry-load"

    /// **Painting ▸ Bristle.** Eleven filaments with independent ends and **no shared envelope** —
    /// the owner's *"you can see it fit within a clear oval shape"* was literal, and the shared
    /// ellipse is what this mask removes.
    case bristleOpen = "bristle-open"

    /// **Painting ▸ Streaky.** Six dots, one per band across the nib, at half round two's radius at
    /// the owner's instruction. Carried at `jitter 0`: turning the pattern per dab smears the
    /// ribbons back into a band, which is the one place on the sheet where rotation is wrong.
    case streakDots6 = "streak-dots-6"

    // MARK: - §12 stage 11's shipped tips
    //
    // **The Texture group, and it is generated rather than sourced.** §8.4 ruled *"source CC0 only
    // for Texture, where scanned grunge and splatter are genuinely hard to fake"*; §13 asked
    // whether that was still true after the generator had made eleven tips, and round four's
    // contact sheet answered no. The four below are `BrushTipGenerator`'s output on exactly the
    // terms the eleven above are — named after the shape that drew them, regenerable byte for byte.

    /// **Texture ▸ Grunge.** A lobed, torn crust whose interior reaches **zero** alpha, stamped at
    /// spacing 0.30 — three times anything else this app ships. §8.4's minimum-spacing finding read
    /// the other way round: a crust needs its dabs far enough apart to be seen one at a time.
    case grungeCrust = "grunge-crust"

    /// **Texture ▸ Splatter.** Twenty-six drops off a cube law, each stretched along its own axis,
    /// spread nearly to the mask's edge — one or two carriers and a crowd of flecks, which is the
    /// size *hierarchy* that separates a splatter from a field of dots.
    case splatterDrops = "splatter-drops"

    /// **Texture ▸ Stipple.** Seventeen hard-edged dots of mixed size. The dynamics-only route —
    /// §2.18's dropout on a round tip — is a beaded *line*, because nothing in the engine spreads
    /// ink across the path; the picture is what makes a stipple a field.
    case stippleSpecks = "stipple-specks"

    /// **Texture ▸ Chalk.** A torn squarish stick whose interior is holes. Useless on its own — at
    /// spacing 0.09 the holes union away — and the brush that carries it lays ink through §2.25's
    /// canvas-anchored `paperTooth`, which merges once per stroke and therefore cannot be unioned.
    case chalkBlock = "chalk-block"

    /// **Paper, not a tip** — BRUSH.md §2.25's canvas-anchored sheet, generated rather than
    /// committed. See `kind` and `BrushPaperGenerator`.
    case paperGrain
    /// The second sheet — a woven over/under, which reads as a different *material* from grain
    /// rather than as the same field at a different scale.
    case canvasWeave

    /// **The third sheet, and the one whose valleys reach the floor** — coarse rough paper, added
    /// for §12 stage 11's Texture group. `paperGrain` bottoms out at 0.35 because it is *paper*
    /// under a pencil and a sheet that erased ink outright would leave nothing to dial back with;
    /// this one bottoms out at 0.04, because a **hole** is what the Chalk and Grunge brushes are
    /// after and §8.4's *"a union fills a dimming but not a hole"* applies to a canvas-anchored
    /// sheet the same way it applies to a tip.
    ///
    /// The dialling-back argument survives intact: `depth` scales the *shortfall*, so this sheet at
    /// depth 0.4 is a mottle and `paperGrain` at depth 1 cannot be made deeper than it is authored.
    /// Deep is the expressive end, and it was the missing one.
    case paperTooth

    /// **Which of §2.26's two collections this belongs in.**
    ///
    /// §2.26 rules **two browsable collections, one storage mechanism**, and this is that split for
    /// the bitmaps the app itself ships: a tip is a *shape* one dab stamps, a texture is *paper* a
    /// whole stroke lays ink through. Both are a `BrushTextureRef` and both resolve through
    /// `BrushTextureStore`; what differs is which picker offers them, and offering paper as a tip
    /// would stamp a dab-shaped square of grain.
    enum Collection { case tip, texture }

    /// Exhaustive with no `default:`, so §12 stage 9's next tip is a compile error here rather than
    /// a bitmap that silently shows up in the paper picker.
    var kind: Collection {
        switch self {
        case .square, .squareBevelWide, .flatMessyEndsDirty, .pencilHard, .pencilSoft, .pencilBlunt, .pencilTextured, .penBrush, .roughInkTriangle, .paintDryLoad, .bristleOpen, .streakDots6,
             .grungeCrust, .splatterDrops, .stippleSpecks, .chalkBlock:
            return .tip
        case .paperGrain, .canvasWeave, .paperTooth:
            return .texture
        }
    }

    /// The PNG's basename in the app bundle, or nil for a bitmap the app **generates**.
    ///
    /// The `brushtip-` prefix exists because a synchronized root group flattens `Resources/` into
    /// the bundle root, where a file called `square.png` would be one artist's icon away from a
    /// collision.
    ///
    /// **The two papers carry no file, and that is a deviation from §12 stage 9 rather than an
    /// oversight.** That stage rules a *tip* generated at build time and its bytes committed, on the
    /// grounds that *"a tip is a small alpha bitmap and generating it per launch buys nothing"*. The
    /// argument is about what generation buys, not what it costs, and for paper it points the other
    /// way: committing two 256² sheets is two binary assets plus four `project.pbxproj` object ids —
    /// which this repo has a section on two branches colliding over — against ~30 lines that run once
    /// per process behind `BrushTextureStore`'s memo. A tip also has to be *chosen* from a contact
    /// sheet (§8.6) and a generated paper does not.
    var resourceName: String? {
        switch kind {
        case .tip: return "brushtip-\(rawValue)"
        case .texture: return nil
        }
    }

    /// What a picker calls it. The raw value is a Swift identifier; this is English.
    var displayName: String {
        switch self {
        case .square: return "Square"
        case .squareBevelWide: return "Square Slab"
        case .flatMessyEndsDirty: return "Messy Flat"
        case .pencilHard: return "Pencil Hard"
        case .pencilSoft: return "Pencil Soft"
        case .pencilBlunt: return "Pencil Blunt"
        case .pencilTextured: return "Pencil Textured"
        case .penBrush: return "Brush Pen"
        case .roughInkTriangle: return "Rough Ink Triangle"
        case .paintDryLoad: return "Dry Load"
        case .bristleOpen: return "Bristle"
        case .streakDots6: return "Streak Dots"
        case .grungeCrust: return "Grunge Crust"
        case .splatterDrops: return "Splatter Drops"
        case .stippleSpecks: return "Stipple Specks"
        case .chalkBlock: return "Chalk Block"
        case .paperGrain: return "Paper Grain"
        case .canvasWeave: return "Canvas Weave"
        case .paperTooth: return "Rough Tooth"
        }
    }

    /// The built-ins in one of §2.26's collections, in the order a picker lists them.
    static func all(in collection: Collection) -> [BuiltInBrushTexture] {
        allCases.filter { $0.kind == collection }
    }
}

/// **Which alpha mask a dab stamps, and the name its cache entry is keyed on.**
///
/// RENDER.md §3.8 records three memos in this repo keyed on a buffer's *size*, each of which
/// silently serves one content's pixels for another's at a matching size. `DabImageCache` is the
/// fourth cache of that family and this type is why it is not the fourth bug: the key names the
/// tip, so two tips can never be the same entry however alike their dimensions.
///
/// **Both arms are load-bearing, and neither is built ahead of its use.** BRUSH.md §12 stage 3
/// required the built-in square to load "through the same path an imported texture will use", which
/// is a claim about there being one path — testable only against a second arm that actually
/// resolves a file. Stage 5 made that arm the artist's: `BrushTip.stamp(BrushTextureRef)` is the
/// whole of a brush's shape, and an imported PNG reaches the renderer by being one of these.
enum BrushTextureRef: Hashable {
    /// A tip committed to the app bundle.
    case builtIn(BuiltInBrushTexture)
    /// A PNG in the brush library — `BrushStorage` — written by `BrushTipImport`.
    ///
    /// **A name, never a path**, which is BRUSH.md §2.27's first requirement and the expensive one
    /// to retrofit: nothing stored here encodes where the library happens to be, so moving the
    /// library rewrites no brush, no `library.json`, no `brushtable.json` and no project manifest.
    case imported(fileName: String)
}

extension BuiltInBrushTexture: Codable {}

extension BrushTextureRef: Codable {
    private enum CodingKeys: String, CodingKey { case builtIn, imported }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .builtIn(let tip): try container.encode(tip, forKey: .builtIn)
        case .imported(let fileName): try container.encode(fileName, forKey: .imported)
        }
    }

    /// One key present, and which key it is *is* the case. Strict on anything else, for the reason
    /// `BrushTip`'s own decoder is: there is no earlier spelling of this to be tolerant of, so a
    /// container with neither key is a corrupt file rather than an old one.
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let tip = try container.decodeIfPresent(BuiltInBrushTexture.self, forKey: .builtIn) {
            self = .builtIn(tip)
        } else if let fileName = try container.decodeIfPresent(String.self, forKey: .imported) {
            self = .imported(fileName: fileName)
        } else {
            throw DecodingError.dataCorrupted(
                DecodingError.Context(codingPath: container.codingPath,
                                      debugDescription: "A brush texture is either builtIn or imported"))
        }
    }
}

/// **Every tip's alpha mask, loaded once per process.**
///
/// A mask is colour-independent, small (256² is 256 KB), and decoding one costs a file read plus a
/// PNG decode — so it is cached here rather than in `DabImageCache`, which holds the *tinted*
/// result and therefore has one entry per colour. Splitting the two is what keeps a palette change
/// from re-reading the disk.
///
/// **Thread-safe, unlike the per-dab caches.** Masks are loaded off whichever thread stamps first —
/// live drawing is on main, a bake or an export is not — and unlike `DabGradientCache` this is not
/// on the hot path: after the first dab of the first stroke every call is a dictionary hit under an
/// uncontended lock.
enum BrushTextureStore {

    private static let lock = NSLock()
    /// `nil` for a ref whose file is missing, cached as a negative so a broken import costs one
    /// failed read rather than one per dab.
    private static var masks: [BrushTextureRef: CGImage?] = [:]

    /// The tip's alpha mask, or nil when its file is missing or undecodable.
    ///
    /// A nil answer draws nothing, which is the honest failure for a tip whose PNG the artist
    /// deleted — the same shape `FontLibrary` gives a missing face. It is *not* a silent one: the
    /// dab is skipped rather than substituted, so a stroke that loses its tip disappears instead of
    /// turning into some other brush.
    static func mask(for ref: BrushTextureRef) -> CGImage? {
        lock.lock()
        defer { lock.unlock() }
        if let cached = masks[ref] { return cached }
        let loaded = load(ref)
        masks[ref] = loaded
        return loaded
    }

    /// **Drops everything held**, so the next ask reads the disk again.
    ///
    /// `BrushStorage.relocate(to:)` is the caller and the reason: this memo is keyed on a
    /// `BrushTextureRef`, which is a *name*, and a name means a different file once the library's
    /// root moves. Nothing in the app calls it otherwise — a file under a fixed root does not
    /// change under a name that is minted per import.
    static func removeAll() {
        lock.lock()
        defer { lock.unlock() }
        masks.removeAll()
    }

    /// The one resolution step, and the whole of what "the same path an imported texture will use"
    /// means: two ways to name a file, one way to read it.
    ///
    /// **The artist's arm goes through `BrushStorage`** — BRUSH.md §2.27's third requirement. It
    /// hands back bytes rather than a URL on purpose: a URL that escaped the storage type would be
    /// a read that a future external folder's security-scoped bracket does not cover, which is the
    /// audit that requirement exists to avoid.
    ///
    /// `Bundle(for:)` rather than `Bundle.main` because this file is compiled into the UI-test
    /// target as well as the app — CLAUDE.md's "an app source a logic test touches is compiled a
    /// second time" — and there `Bundle.main` is the XCUITest *runner*, which carries none of the
    /// app's resources. `Bundle(for:)` answers the bundle the code itself came from in both.
    private static func load(_ ref: BrushTextureRef) -> CGImage? {
        let data: Data?
        switch ref {
        case .builtIn(let tip):
            // **A built-in with no `resourceName` is generated rather than read**, which is the one
            // branch this function has that is not "two ways to name a file". It is still one
            // resolution step: everything downstream asks `BrushTextureStore` for a mask and neither
            // knows nor can tell where the bytes came from — the same relationship `.round` has to
            // `.stamp` one level up. See `BuiltInBrushTexture.resourceName` for why the papers are
            // not committed PNGs.
            guard let resource = tip.resourceName else { return BrushPaperGenerator.mask(tip) }
            data = Bundle(for: BrushTextureBundleToken.self)
                .url(forResource: resource, withExtension: "png")
                .flatMap { try? Data(contentsOf: $0) }
        case .imported(let fileName):
            data = BrushStorage.shared.read(fileName)
        }
        guard let data else { return nil }
        return UIImage(data: data)?.cgImage
    }
}

/// Nothing but an address for `Bundle(for:)`. `BrushTextureStore` is an enum and enums have no
/// class to ask.
final class BrushTextureBundleToken {}

// MARK: - BRUSH.md §2.26 — two collections over one storage mechanism

/// **Which of §2.26's two collections a file in the brush library belongs to.**
///
/// The owner: *"it may be worth having a library of textures and sprites to which new sprites can be
/// added into."* §2.26 rules **two browsable collections, one storage mechanism** — *"both are a
/// named bitmap under §2.27's root and `BrushTextureRef` already resolves exactly that"*. So the
/// separation cannot be two directories (that would be two roots, which §2.27 spent a pass removing)
/// and it cannot be a manifest (a second thing to keep in step with the files). It is a **prefix on
/// the name**, read back through `BrushStorage.fileNames()` — the fifth of §2.27's five verbs, which
/// exists for exactly this and had no caller until now.
///
/// **A tip's prefix is `custom-`, which is the name imports have always been written under.** Renaming
/// it to `tip-` would orphan every tip already on an artist's device and every project package that
/// names one: §2.14 makes *documents* expendable and says nothing about the artist's own brushes, and
/// `BrushLibraryDocument.version` exists because of that distinction. The prefix is ugly and the files
/// are real.
enum BrushAssetKind: String, CaseIterable, Hashable {
    case tip
    case texture

    /// What a file of this kind is named. See the type's note for why the tip's is not `tip-`.
    var filePrefix: String {
        switch self {
        case .tip: return "custom-"
        case .texture: return "texture-"
        }
    }

    /// A fresh, unique name for a file of this kind.
    func newFileName() -> String { "\(filePrefix)\(UUID().uuidString).png" }

    /// Whether a name in the library belongs to this collection.
    ///
    /// `library.json` matches neither, which is the point: `fileNames()` answers everything under the
    /// root and a picker must not offer the library file as a sprite.
    func owns(_ fileName: String) -> Bool {
        fileName.hasPrefix(filePrefix) && fileName.hasSuffix(".png")
    }
}

/// **The artist's own paper, turned into a texture** — BRUSH.md §2.25 and §2.26's import half.
///
/// It is `BrushTipImport`'s twin and it is deliberately **not** the same normalisation, because a tip
/// and a paper are different kinds of picture and the tip's rules are wrong for paper in two ways
/// that are visible in one glance:
///
/// 1. **No letterbox.** `BrushTipImport` fits a non-square picture inside the square and leaves
///    transparent margins, which for a *tip* is exactly right — a dab's shape is expressible by
///    leaving its margins clear. A texture is **tiled**, so a transparent margin is not a margin, it
///    is a grid of seams laid across every stroke: `BrushTextureMerge` multiplies with
///    `.destinationIn`, so alpha 0 at depth 1 *removes* the ink there. The picture is aspect-fill
///    cropped instead, which fills the square edge to edge.
/// 2. **No border.** The tip's 2 px transparent frame is what a rotated dab antialiases into. A
///    tiled sheet is never rotated and its edges meet the next tile, so a border would be the same
///    seam as the letterbox, two pixels wide.
///
/// **The luminance rule is kept, and that is deliberate.** An opaque picture is read as
/// `1 - luminance`, exactly as a tip is, so *dark marks keep ink and light ones take it away* on both
/// surfaces. Two conventions for what a grey pixel means would be the same picture behaving in
/// opposite directions depending on which picker it was imported through.
enum BrushTextureImport {

    /// Normalises `image`, writes it into the brush library, and answers the ref that resolves it.
    static func importTexture(from image: UIImage) throws -> BrushTextureRef {
        guard let data = UIImage(cgImage: try mask(from: image)).pngData() else {
            throw BrushTipImport.Failure.unreadableImage
        }
        let fileName = BrushAssetKind.texture.newFileName()
        do {
            try BrushStorage.shared.write(data, to: fileName)
        } catch {
            throw BrushTipImport.Failure.couldNotWrite(error)
        }
        return .imported(fileName: fileName)
    }

    /// The normalisation itself, with no filesystem in it: `image` as a square straight-alpha sheet
    /// that tiles edge to edge.
    static func mask(from image: UIImage) throws -> CGImage {
        let side = BrushTipImport.maskSide
        guard image.size.width > 0, image.size.height > 0 else { throw BrushTipImport.Failure.unreadableImage }
        guard let ctx = CGContext(data: nil, width: side, height: side, bitsPerComponent: 8,
                                  bytesPerRow: side * 4, space: PixelOps.deviceRGBColorSpace,
                                  bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)
        else { throw BrushTipImport.Failure.unreadableImage }
        ctx.interpolationQuality = .high
        let fill = aspectFill(width: image.size.width, height: image.size.height)
        ctx.translateBy(x: 0, y: CGFloat(side))
        ctx.scaleBy(x: 1, y: -1)
        UIGraphicsPushContext(ctx)
        image.draw(in: fill)
        UIGraphicsPopContext()

        guard let raw = ctx.data else { throw BrushTipImport.Failure.unreadableImage }
        let bytes = raw.bindMemory(to: UInt8.self, capacity: side * side * 4)
        // Judged over the whole square, which an aspect-fill makes the whole picture — there is no
        // letterbox to look inside, which is the one simplification this normalisation gets for free.
        var opaqueEverywhere = true
        for i in stride(from: 3, to: side * side * 4, by: 4) where bytes[i] != 255 {
            opaqueEverywhere = false
            break
        }
        var inked = false
        for i in stride(from: 0, to: side * side * 4, by: 4) {
            let a = Int(bytes[i + 3])
            var coverage = a
            if opaqueEverywhere, a > 0 {
                let luminance = (299 * Int(bytes[i]) + 587 * Int(bytes[i + 1]) + 114 * Int(bytes[i + 2])) / 1000
                coverage = (255 - luminance * 255 / a) * a / 255
            }
            coverage = max(0, min(coverage, 255))
            bytes[i] = 0; bytes[i + 1] = 0; bytes[i + 2] = 0
            bytes[i + 3] = UInt8(coverage)
            if coverage > 0 { inked = true }
        }
        // **A blank sheet is refused for a sharper reason than a blank tip.** A tip whose mask is
        // empty draws nothing; a *texture* whose mask is empty multiplies every stroke by zero, so
        // the brush stops painting at all and nothing on screen says why.
        guard inked else { throw BrushTipImport.Failure.blankMask }
        guard let mask = ctx.makeImage() else { throw BrushTipImport.Failure.unreadableImage }
        return mask
    }

    /// The rect, in the sheet's own top-left space, that `image` is drawn into: the smallest
    /// aspect-preserving cover of the whole square, centred. The overflow falls outside the context
    /// and is clipped, which is what "crop" means here.
    static func aspectFill(width: CGFloat, height: CGFloat) -> CGRect {
        let side = CGFloat(BrushTipImport.maskSide)
        let k = max(side / width, side / height)
        let w = width * k, h = height * k
        return CGRect(x: (side - w) / 2, y: (side - h) / 2, width: w, height: h)
    }
}

/// **The two papers the app ships, as arithmetic** — see `BuiltInBrushTexture.resourceName` for why
/// they are generated rather than committed.
///
/// **Both tile seamlessly, and that is a requirement rather than a nicety.**
/// `BrushTextureMerge` lays one draw per repeat, so a field that does not wrap draws a visible grid
/// across every stroke. Everything below is periodic with a period that divides 256 exactly: the
/// noise lattice wraps its cell indices, and the weave's cell pitch is a divisor of the side.
///
/// Deterministic to the byte — no `UUID`, no `Date`, no `arc4random`. A generated sheet that differed
/// between launches would be paper that moved under ink already drawn, which is the whole thing §2.25
/// anchors to the canvas to avoid.
enum BrushPaperGenerator {

    /// The same 256² `BrushTipImport.maskSide` every other mask in the app is, so one resolution path
    /// serves all of them and `BrushTextureMaskCache`'s resident cost is bounded by one number.
    static var side: Int { BrushTipImport.maskSide }

    static func mask(_ paper: BuiltInBrushTexture) -> CGImage? {
        guard paper.kind == .texture else { return nil }
        let side = Self.side
        guard let ctx = CGContext(data: nil, width: side, height: side, bitsPerComponent: 8,
                                  bytesPerRow: side * 4, space: PixelOps.deviceRGBColorSpace,
                                  bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue),
              let raw = ctx.data else { return nil }
        let bytes = raw.bindMemory(to: UInt8.self, capacity: side * side * 4)
        for y in 0..<side {
            for x in 0..<side {
                let survives: Double
                switch paper {
                case .paperGrain: survives = grain(x: x, y: y)
                case .canvasWeave: survives = weave(x: x, y: y)
                case .paperTooth: survives = tooth(x: x, y: y)
                // Unreachable: the `kind == .texture` guard above returns before this. A `default`
                // rather than the twelve tip cases on purpose — `BuiltInBrushTexture.kind` is the
                // exhaustive switch that forces a new case to be *classified*, and duplicating that
                // list here would make every new tip a compile error in a paper generator that will
                // never see one.
                default: survives = 1
                }
                let i = (y * side + x) * 4
                bytes[i] = 0; bytes[i + 1] = 0; bytes[i + 2] = 0
                bytes[i + 3] = UInt8(max(0, min(255, (survives * 255).rounded())))
            }
        }
        return ctx.makeImage()
    }

    /// Three octaves of periodic value noise, mapped into `0.35…1`.
    ///
    /// **The floor is not taste, it is what keeps `depth` the only strength control.** A sheet
    /// authored down to 0 would erase ink outright at depth 1 and leave the artist nothing to dial
    /// back with, since `BrushTextureSettings.depth` scales the *shortfall* — `1 - depth·(1 - a)` —
    /// and cannot undo an authored zero at full depth.
    private static func grain(x: Int, y: Int) -> Double {
        var value = 0.0, amplitude = 1.0, total = 0.0
        for cells in [8, 16, 32] {
            value += amplitude * valueNoise(x: x, y: y, cells: cells)
            total += amplitude
            amplitude *= 0.55
        }
        return 0.35 + 0.65 * (value / total)
    }

    /// **Coarse rough paper whose valleys reach the floor** — the sheet a Texture-group brush lays
    /// its ink through.
    ///
    /// What separates it from `grain` is the **steep S**: the field is pushed to its ends, so what
    /// comes out is pits at 0.04 and flats at 1 rather than an even mottle around a mean. MEASURED
    /// over the sheet, 34% of it is below 0.2 and 25% above 0.8, against `grain`'s 0% below 0.2.
    ///
    /// The floor is 0.04 and not 0, which is the one thing kept from `grain`'s argument: a sheet
    /// that reached exactly 0 would make a stroke's holes independent of `depth` at the bottom of
    /// the range, and a knob whose end is unreachable is worse than one whose end is dull.
    ///
    /// **The octave set starts at eight cells and not four, and the first render of §12 stage 11's
    /// sheet is why.** A four-cell octave is one 64 px blob per sheet, which at a tile of 40 points
    /// on a 30 point brush is a *recognisable shape repeating every 40 points* — the tiling became
    /// visible as a row of identical marks along the stroke rather than as paper. Starting one
    /// octave finer leaves no single dominant feature for the eye to lock onto, and the presets
    /// that use this lay it at 150–190 points so a repeat spans several stroke widths as well.
    private static func tooth(x: Int, y: Int) -> Double {
        var value = 0.0, amplitude = 1.0, total = 0.0
        for cells in [8, 16, 32, 64] {
            value += amplitude * valueNoise(x: x, y: y, cells: cells)
            total += amplitude
            amplitude *= 0.62
        }
        let n = value / total
        return 0.04 + 0.96 * smoothstep(min(max((n - 0.34) / 0.28, 0), 1))
    }

    /// A woven over/under. The pitch is 16 px, so one repeat of the weave itself is 32 px and 256 is
    /// eight of them — which is why the sheet wraps.
    private static func weave(x: Int, y: Int) -> Double {
        let cell = 16
        let warpOnTop = ((x / cell) + (y / cell)) % 2 == 0
        let across = Double(x % cell) / Double(cell)
        let along = Double(y % cell) / Double(cell)
        // A thread's crown is the middle of its own cell; the value falls to the gap at both edges.
        let height = warpOnTop ? sin(.pi * across) : sin(.pi * along)
        return 0.3 + 0.7 * pow(max(height, 0), 0.6)
    }

    /// Value noise on a `cells × cells` lattice that **wraps**, smoothstep-interpolated.
    private static func valueNoise(x: Int, y: Int, cells: Int) -> Double {
        let step = Double(side) / Double(cells)
        let fx = Double(x) / step, fy = Double(y) / step
        let ix = Int(floor(fx)), iy = Int(floor(fy))
        let tx = smoothstep(fx - Double(ix)), ty = smoothstep(fy - Double(iy))
        let a = lattice(ix, iy, cells), b = lattice(ix + 1, iy, cells)
        let c = lattice(ix, iy + 1, cells), d = lattice(ix + 1, iy + 1, cells)
        return (a + (b - a) * tx) + ((c + (d - c) * tx) - (a + (b - a) * tx)) * ty
    }

    private static func smoothstep(_ t: Double) -> Double { t * t * (3 - 2 * t) }

    /// One lattice corner, `0…1`. The `% cells` is what makes the field periodic; the hash is a
    /// written-down integer mix so the same corner is the same number in every process.
    private static func lattice(_ x: Int, _ y: Int, _ cells: Int) -> Double {
        let wx = UInt64(((x % cells) + cells) % cells)
        let wy = UInt64(((y % cells) + cells) % cells)
        var h = wx &* 0x9E37_79B9_7F4A_7C15 &+ wy &* 0xBF58_476D_1CE4_E5B9 &+ UInt64(cells) &* 0x94D0_49BB_1331_11EB
        h ^= h >> 30; h = h &* 0xBF58_476D_1CE4_E5B9
        h ^= h >> 27; h = h &* 0x94D0_49BB_1331_11EB
        h ^= h >> 31
        return Double(h >> 11) / Double(UInt64(1) << 53)
    }
}

/// **The artist's own PNG, turned into a tip.** BRUSH.md §12 stage 5's import half.
///
/// Everything downstream of `BrushTextureRef` reads a mask's **alpha** as the dab's coverage — that
/// is what `DabImageCache` tints and what the committed square is. So the one rule this type exists
/// to enforce is that *a file in the brush library is a mask*, in exactly the
/// sense the built-in square is, whatever the artist picked. The renderer then has one meaning for a
/// tip's pixels rather than two, and `BuiltInBrushTexture.square`'s own description doubles as the
/// specification for every import.
///
/// Three things happen on the way in, and each is a ruling rather than a convenience:
///
/// 1. **Square, by `BuiltInBrushTexture`'s ruling.** A non-square picture is letterboxed into a
///    square mask with transparent margins, because a dab's size is one scalar everywhere below
///    `stampImage` and an aspect ratio would put a second number into `DabPose`, `BakedDab` and the
///    dirty-rect bound for a shape the artist can express by leaving the margins clear anyway.
/// 2. **256², at a 2 px transparent border** — the same as the committed square, and the border for
///    the same reason it has one: it is what a rotated or downscaled draw antialiases *into*. A
///    photo letterboxed edge-to-edge would alias along whichever side filled the frame. 256 is also
///    what every §3.5 measurement was taken at, and what bounds `BrushTextureStore`'s resident cost
///    — a 12 MP import held at source resolution would be 48 MB of mask.
/// 3. **An opaque picture is read as ink-on-white, not as a solid square.** This is the one
///    inference here, and without it the feature is unusable for the format artists' stamps
///    actually come in: `.abr`-style stamps and everything scanned are grayscale with no alpha
///    channel at all, and a photo picked out of Photos is opaque by construction. Read as alpha,
///    every one of them is a filled square — the brush draws a block whatever the picture was.
///    Read as `1 - luminance` they are the stamp the artist sees, which is also what Procreate's
///    Shape Source does with an imported image and what a `.abr` brush's grayscale means.
///
///    **The test is on the pixels rather than on the file's metadata**: alpha is examined inside the
///    letterbox, and only a picture that is opaque *there* is read by luminance. A PNG that carries
///    real transparency keeps its alpha, so the rule cannot silently invert a mask that was already
///    a mask.
enum BrushTipImport {

    /// The pixel side every imported mask is normalised to — `BuiltInBrushTexture.square`'s.
    static let maskSide = 256
    /// The transparent margin left around the picture, in mask pixels. `BuiltInBrushTexture.square`
    /// carries the measurement for why it is not padding.
    static let border = 2

    enum Failure: Error {
        /// The picked item could not be drawn at all.
        case unreadableImage
        /// It could be drawn and every pixel of the result is clear — a white-on-white scan, or a
        /// blank page. Named rather than folded into the above because the artist can act on it,
        /// and because a brush that silently draws nothing is the failure this stage is most likely
        /// to ship: it looks exactly like a broken renderer.
        case blankMask
        case couldNotWrite(Error)
    }

    /// Normalises `image`, writes it into the brush library, and answers the tip that stamps it. The
    /// whole of what "importing a brush" means, in one call, so the import UI holds no part of the
    /// rule.
    ///
    /// **`BrushStorage.shared` rather than an injected storage, and that is deliberate** — BRUSH.md
    /// §2.27. The tip this hands back is resolved later by `BrushTextureStore`, which reads the
    /// app's one library; a storage parameter here would let an import land somewhere the renderer
    /// never looks, which is a state the global it replaced could not express either.
    static func importTip(from image: UIImage) throws -> BrushTip {
        guard let data = UIImage(cgImage: try mask(from: image)).pngData() else {
            throw Failure.unreadableImage
        }
        // **The name carries which of §2.26's two collections this belongs to** — see
        // `BrushAssetKind`, and note the tip's prefix is still `custom-`, so nothing already on an
        // artist's device is orphaned by the split.
        let fileName = BrushAssetKind.tip.newFileName()
        do {
            try BrushStorage.shared.write(data, to: fileName)
        } catch {
            throw Failure.couldNotWrite(error)
        }
        return .stamp(.imported(fileName: fileName))
    }

    /// The normalisation itself, with no filesystem in it: `image` as a square straight-alpha mask.
    ///
    /// It throws rather than answering nil because the two ways to have no mask are not the same
    /// news for the artist — "that would not open" and "that is blank" call for different fixes —
    /// and a nil that means both is exactly the collapse `BrushTip` removed from the model.
    static func mask(from image: UIImage) throws -> CGImage {
        let side = maskSide
        guard image.size.width > 0, image.size.height > 0 else { throw Failure.unreadableImage }
        guard let ctx = CGContext(data: nil, width: side, height: side, bitsPerComponent: 8,
                                  bytesPerRow: side * 4, space: PixelOps.deviceRGBColorSpace,
                                  bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)
        else { throw Failure.unreadableImage }
        ctx.interpolationQuality = .high
        let fit = letterbox(width: image.size.width, height: image.size.height)
        // Flipped to UIKit's top-left space so `UIImage.draw` lands the picture the way the artist
        // saw it — orientation metadata included, which `image.cgImage` alone would drop.
        ctx.translateBy(x: 0, y: CGFloat(side))
        ctx.scaleBy(x: 1, y: -1)
        UIGraphicsPushContext(ctx)
        image.draw(in: fit)
        UIGraphicsPopContext()

        guard let raw = ctx.data else { throw Failure.unreadableImage }
        let bytes = raw.bindMemory(to: UInt8.self, capacity: side * side * 4)
        let byLuminance = isOpaque(bytes, side: side, inside: fit)
        var inked = false
        for i in stride(from: 0, to: side * side * 4, by: 4) {
            let a = Int(bytes[i + 3])
            var coverage = a
            if byLuminance, a > 0 {
                // The buffer is premultiplied, so un-premultiply before taking the picture's own
                // luminance, then re-apply the draw's own coverage at the letterbox edge.
                let luminance = (299 * Int(bytes[i]) + 587 * Int(bytes[i + 1]) + 114 * Int(bytes[i + 2])) / 1000
                coverage = (255 - luminance * 255 / a) * a / 255
            }
            coverage = max(0, min(coverage, 255))
            bytes[i] = 0; bytes[i + 1] = 0; bytes[i + 2] = 0
            bytes[i + 3] = UInt8(coverage)
            if coverage > 0 { inked = true }
        }
        guard inked else { throw Failure.blankMask }
        guard let mask = ctx.makeImage() else { throw Failure.unreadableImage }
        return mask
    }

    /// The rect, in the mask's own top-left space, that `image` is drawn into: the largest
    /// aspect-preserving fit inside the bordered square, centred.
    static func letterbox(width: CGFloat, height: CGFloat) -> CGRect {
        let inner = CGFloat(maskSide - 2 * border)
        let k = min(inner / width, inner / height)
        let w = width * k, h = height * k
        return CGRect(x: (CGFloat(maskSide) - w) / 2, y: (CGFloat(maskSide) - h) / 2, width: w, height: h)
    }

    /// Whether the drawn picture carries no transparency of its own, judged **inside** the letterbox
    /// and inset by two pixels so the resample's own antialiased boundary is not mistaken for the
    /// artist's alpha. A degenerate fit answers false, which keeps the alpha as it stands — the
    /// conservative direction, since misreading a real mask as opaque would invert it.
    private static func isOpaque(_ bytes: UnsafeMutablePointer<UInt8>, side: Int, inside fit: CGRect) -> Bool {
        let box = fit.insetBy(dx: 2, dy: 2).intersection(CGRect(x: 0, y: 0, width: side, height: side))
        guard box.width >= 1, box.height >= 1 else { return false }
        for y in Int(box.minY.rounded(.up))..<Int(box.maxY.rounded(.down)) {
            for x in Int(box.minX.rounded(.up))..<Int(box.maxX.rounded(.down)) {
                if bytes[(y * side + x) * 4 + 3] != 255 { return false }
            }
        }
        return true
    }
}

// MARK: - BRUSH.md §2.25 — the canvas-anchored texture a stroke merges through

extension BrushTextureRef {
    /// The file this ref needs the brush library to hold, or nil for one the app bundle carries.
    ///
    /// `BrushTip.importedTextureFileName` is this question asked of a *tip*; a brush's texture asks
    /// it of the same enum, so the rule that decides which files a saved package has to carry is
    /// stated once and both consumers read it. Adding the texture without this was the shape of
    /// BUGS.md's *"copied by the palette, not by what is drawn"* — a reopened document whose ink
    /// names a file that never travelled.
    var importedFileName: String? {
        guard case .imported(let fileName) = self else { return nil }
        return fileName
    }
}

/// **The texture a brush lays its ink through — BRUSH.md §2.25.**
///
/// The owner: *"its a texture that gets applied over your brush ... Texture is applied relative to
/// canvas, and uses the untextured brush as a transparency mask, then is scaled with opacity."*
///
/// So this is not a tip and not grain. A tip is *one dab's* shape and travels with the dab; this is
/// **paper**, fixed to the canvas, and the ink is what shows it. It is applied once, where a stroke
/// merges (`DabTarget.beginStrokeGroup`), by multiplying the mask's alpha into the alpha the whole
/// walk accumulated — which is exactly *"uses the untextured brush as a transparency mask"* — and
/// the stroke's own opacity then scales the result, because the merge is where that opacity is
/// applied anyway.
///
/// **§2.4 deleted grain and this reverses it, in a different place and by a different mechanism.**
/// §2.4's reason was structural: *"a sprite travels with the stroke, paper does not"*, and with the
/// ink composited dab by dab straight onto the layer there was no moment at which the whole stroke
/// existed as a mask, so paper could only ever have been faked per dab. §12 stage 8 built that
/// moment. Nothing here is per dab, nothing here is in a dab cache's key, and nothing here is
/// stored on a sample — which is the whole of why it is affordable now and was not then.
///
/// **Three fields, and §9.2 is why there are not more.** *"None of them is speculative generality,
/// and none should be built beyond what §12's stages need."* An offset, a rotation, a contrast, an
/// invert and a per-tip variant were all candidates and are all absent: the arithmetic below reads
/// `mask`, `tileSize` and `depth` and nothing else, so nothing else exists.
struct BrushTextureSettings: Codable, Hashable {
    /// Which bitmap. The **same** enum a tip names, resolved by the **same**
    /// `BrushTextureStore.mask(for:)`, written by the same import — BRUSH.md §12 stage 5 built one
    /// route for a brush's pixels to reach the renderer and this is a second consumer of it, not a
    /// second scheme.
    var mask: BrushTextureRef

    /// **The side of one repeat, in canvas points.** Not a multiplier on the mask's own resolution:
    /// a number that means "canvas points" is the number the anchoring is expressed in, and it makes
    /// the tiling independent of what a given asset happens to be authored at.
    ///
    /// Rounded to whole points where it is used. Tiles laid on a fractional grid are drawn into
    /// fractional rectangles, and CoreGraphics antialiases those — which under `.destinationIn`
    /// carves a faint grid of *seams* out of the ink rather than merely blurring one. The same
    /// argument `endStrokeGroup`'s `.integral` clip already makes, one level down.
    var tileSize: CGFloat

    /// **The smallest repeat the merge will lay, and it is a cost floor rather than a taste one.**
    ///
    /// `BrushTextureMerge` draws one tile per repeat over the stroke's own clip, so the draw count is
    /// `(clip / tileSize)²`. A stroke that crosses a 16383² canvas — which this app allows, and
    /// `StrokeScratch`'s whole existence is about — is 1M tiles at 16 points and 268M at 1. The
    /// pixels are the same either way; it is the per-draw overhead that is not, which is why the
    /// floor is on the *count* rather than on the blitting.
    ///
    /// 16 points is also about where a 256-pixel sheet stops being legible as paper under a
    /// downscale, so nothing expressible is being taken away. **If the editor's slider ever wants to
    /// go below it, the fix is not to lower this** — it is to cache the sheet pre-repeated `n×n` so
    /// one draw lays `n²` tiles, which is exact because a repeat of a repeat is the same field.
    static let minimumTileSize: CGFloat = 16

    /// `0…1` — how much of the texture's shortfall is taken out of the ink. The mask's own alpha `a`
    /// becomes `1 - depth·(1 - a)`, so **0 is exactly no texture** (every pixel survives) and 1 is
    /// the mask as authored.
    ///
    /// That `0` is the identity is not a nicety: it is what lets one arithmetic serve the whole
    /// range without a second path, and it is asserted rather than assumed.
    var depth: Double

    init(mask: BrushTextureRef, tileSize: CGFloat = 256, depth: Double = 1) {
        self.mask = mask
        self.tileSize = tileSize
        self.depth = depth
    }
}

extension BrushTextureSettings {
    private enum CodingKeys: String, CodingKey { case mask, tileSize, depth }

    /// `mask` is strict — a texture that names no bitmap is not a texture, and the field is optional
    /// on `Brush` precisely so "no texture" has its own spelling. The other two default, which is
    /// §6's grouping doctrine: a setting added inside here later is one field rather than a
    /// decode-compatibility question.
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        mask = try c.decode(BrushTextureRef.self, forKey: .mask)
        tileSize = try c.decodeIfPresent(CGFloat.self, forKey: .tileSize) ?? 256
        depth = try c.decodeIfPresent(Double.self, forKey: .depth) ?? 1
    }
}

/// **The depth-adjusted, pre-flipped masks a merge tiles, loaded and adjusted once per process.**
///
/// `BrushTextureStore` holds the mask as the file has it. This holds `1 - depth·(1 - a)` of that
/// mask, flipped for a UIKit-space context, which is the image the merge actually draws — and both
/// of those are per *brush*, not per dab or per stroke, so one entry serves every stroke ever drawn
/// with that brush.
///
/// **The key names the texture and the depth, and it does not name a size.** RENDER.md §3.8 records
/// three memos in this repo keyed on a buffer's size alone, each of which silently serves one
/// content's pixels for another's; this one cannot be the fourth, because size is not in it at all —
/// an entry is always the mask's own resolution and the tiling scales at draw time.
enum BrushTextureMaskCache {

    private struct Key: Hashable {
        let mask: BrushTextureRef
        /// Quantised to a thousandth so a slider's float noise cannot mint an entry per frame. Far
        /// finer than a byte of alpha, which is all the adjustment can express.
        let depthThousandths: Int
    }

    private static let lock = NSLock()
    private static var entries: [Key: CGImage?] = [:]
    /// Ceiling on distinct entries, on `DabImageCache`'s contract: texture and depth change at human
    /// speed, so this is never approached, and something pathological degrades to "rebuild
    /// sometimes" rather than growing without bound.
    private static let limit = 16

    /// The image the merge tiles, or nil when the mask's file is missing or unreadable.
    ///
    /// **Nil draws nothing rather than drawing everything**, and the direction matters more here
    /// than it does for a tip: the merge multiplies with `.destinationIn`, so a mask that came back
    /// as "no coverage anywhere" would delete the stroke. The caller leaves the ink untextured
    /// instead — a brush whose texture file the artist deleted paints, which is the same honest
    /// failure `BrushTextureStore` gives a missing tip, pointed the safe way.
    static func entry(for settings: BrushTextureSettings) -> CGImage? {
        let key = Key(mask: settings.mask,
                      depthThousandths: Int((min(max(settings.depth, 0), 1) * 1000).rounded()))
        lock.lock()
        defer { lock.unlock() }
        if let cached = entries[key] { return cached }
        let built = build(mask: settings.mask, depth: CGFloat(key.depthThousandths) / 1000)
        if entries.count >= limit { entries.removeAll(keepingCapacity: true) }
        entries[key] = built
        return built
    }

    /// Drops everything held. Tests that write a mask file and then rewrite it need this; nothing in
    /// the app calls it, for the same reason nothing clears `BrushTextureStore`.
    static func removeAll() {
        lock.lock()
        defer { lock.unlock() }
        entries.removeAll()
    }

    private static func build(mask ref: BrushTextureRef, depth: CGFloat) -> CGImage? {
        guard let mask = BrushTextureStore.mask(for: ref), mask.width > 0, mask.height > 0 else { return nil }
        let width = mask.width, height = mask.height
        guard let ctx = CGContext(data: nil, width: width, height: height, bitsPerComponent: 8,
                                  bytesPerRow: width * 4, space: PixelOps.deviceRGBColorSpace,
                                  bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)
        else { return nil }
        // **Pre-flipped, because every context a merge runs in is flipped to UIKit's top-left
        // space** (`RasterLayerTexture.ensureContext`, `UIGraphicsImageRenderer`). A `CGContext.draw`
        // there lands an image upside down; doing the flip once, here, is what makes the paper the
        // artist authored the paper that lands. `DabImageCache` does not bother because a tip's mask
        // is drawn through a rotation anyway and the committed square is symmetric — a tiling sheet
        // is neither.
        ctx.translateBy(x: 0, y: CGFloat(height))
        ctx.scaleBy(x: 1, y: -1)
        ctx.draw(mask, in: CGRect(x: 0, y: 0, width: width, height: height))
        guard let raw = ctx.data else { return nil }
        let bytes = raw.bindMemory(to: UInt8.self, capacity: width * height * 4)
        // `1 - depth·(1 - a)`, in bytes. Colour is irrelevant — `.destinationIn` reads source alpha
        // only — and is left at the premultiplied black the draw produced.
        for i in stride(from: 0, to: width * height * 4, by: 4) {
            let a = CGFloat(bytes[i + 3]) / 255
            let survives = 1 - depth * (1 - a)
            bytes[i] = 0; bytes[i + 1] = 0; bytes[i + 2] = 0
            bytes[i + 3] = UInt8(max(0, min(255, (survives * 255).rounded())))
        }
        return ctx.makeImage()
    }
}

/// **Multiplies a brush's texture into whatever alpha is already in `ctx`, in canvas coordinates.**
///
/// The one place BRUSH.md §2.25 happens, called from every merge: the two `endStrokeGroup`s and
/// `StrokeScratch`'s window pass. `clip` is the region being merged, **in the context's own space**;
/// `canvasOrigin` is the canvas point that space's `(0, 0)` sits on, which is `.zero` for a cel and
/// the window's origin for a `StrokeScratch`.
///
/// **`canvasOrigin` is the whole of "canvas-anchored", and it is why the phase is a parameter rather
/// than an assumption.** A live stroke draws into a window whose origin is wherever the pen started
/// and which *moves* as the stroke grows; anchoring to the context would make the paper slide under
/// the ink and would differ between the live tier and the replay. Anchoring to the canvas makes the
/// same canvas point sample the same texel however the stroke was drawn, which is the property that
/// makes this paper rather than a sprite, and is what the tests discriminate on.
///
/// `.destinationIn` is `R = D · Sa`, so this scales the accumulated ink by the mask and touches
/// nothing the ink did not already reach — the texture cannot appear outside the stroke, by
/// construction rather than by clipping.
enum BrushTextureMerge {
    static func apply(_ settings: BrushTextureSettings?, into ctx: CGContext,
                      over clip: CGRect, canvasOrigin: CGPoint) {
        guard let settings, settings.depth > 0, !clip.isNull, !clip.isEmpty,
              let entry = BrushTextureMaskCache.entry(for: settings) else { return }
        // Whole points, so every tile lands on the pixel grid — see `BrushTextureSettings.tileSize`
        // — and never below the floor, which is a bound on the number of draws this loop makes.
        let side = max(BrushTextureSettings.minimumTileSize, settings.tileSize.rounded())
        let phase = CGPoint(x: canvasOrigin.x.rounded(), y: canvasOrigin.y.rounded())
        // The clip, expressed in canvas points, is what decides which tiles of the sheet are needed.
        let inCanvas = clip.offsetBy(dx: phase.x, dy: phase.y)
        let firstColumn = Int(floor(inCanvas.minX / side)), lastColumn = Int(floor((inCanvas.maxX - 0.001) / side))
        let firstRow = Int(floor(inCanvas.minY / side)), lastRow = Int(floor((inCanvas.maxY - 0.001) / side))
        ctx.saveGState()
        ctx.setBlendMode(.destinationIn)
        // `.high` for `DabImageCache`'s reason: an entry is at its own native resolution and a tile
        // is usually smaller, and point-sampling that downscale aliases the paper into a moiré.
        ctx.interpolationQuality = .high
        // **One draw per tile, and the two things that costs are written down rather than assumed
        // away.** The count grows with the clip's area over `tileSize²`, which is what
        // `minimumTileSize` bounds. And each tile is resampled with its edges *clamped*, so a sheet
        // laid at less than its native resolution does not blend across a tile boundary — INFERRED
        // from how `CGContext.draw(_:in:)` samples, not measured in the app, and the same
        // pre-repeated cache entry that would fix the count would remove it.
        for column in firstColumn...max(firstColumn, lastColumn) {
            for row in firstRow...max(firstRow, lastRow) {
                ctx.draw(entry, in: CGRect(x: CGFloat(column) * side - phase.x,
                                           y: CGFloat(row) * side - phase.y,
                                           width: side, height: side))
            }
        }
        ctx.restoreGState()
    }
}
